### ISSUE TITLE
Create new chapter Node Editor by tools

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Manual#11]
Blender manual lacks of description of the single menu items in most cases, and has many outdated or no images at all. Plus other flaws. Like that they avoid to explain existing menus, since "they change too fast". Which makes it imho more a loose collection of explanations instead of a real manual. Which can be useful and fitting, or not.

Bforartists manual philosophy is to explain the UI and useage by the available tools and menus in the editors. One by one.

Task. Create new chapter Node Editor by tools.

**Comment by Draise14** [comment]
Question, the workflow to create these documents is.. copy the format from one former ODT then begin writing?

**Comment by ReinerBforartists** [comment]
You can create the odt file from scratch, then use git or tortoisegit to add the file to the repo :)

**Comment by Draise14** [comment]
Dibs on this one. 

I'll be pushing this into the **Draises_Edits** branch as the file "3.7.1 Editors - Node Editor by tools.odt". 
I have duplicated an *.odt to preserve the styling established. My only concern is some of the copied data is "locked" (the Node editor index).

**Comment by Draise14** [comment]
Ok, started the work. Will do this off and on between work. 

-Area I'm working on: Header

Just a question @ReinerBforartists  should I also list every single node type that is used in the different editor types? I'm still wondering how to structure this. Also, should I document every tool within the side bar tabs in detail in this document?  

Current structure I'll propose:
Tool areas:
- Toolshelf
  - Panels
- Properties Region
  - Gpencil Tab
  - Input Tab
    - Nodes Shader
    - Nodes Composite
    - Nodes Texture
  - Modify Tab
    - Nodes Shader
    - Nodes Composite
    - Nodes Texture
  - Relations Tab
    - Nodes
- Header

**Comment by ReinerBforartists** [comment]
Yes please. To document really everything is the purpose of a reference manual ;)

I am just not sure if it's a good idea to start this chapter now. Node editor will massively change with the 2.8 port. They have split the sub editors apart now. And the first 2.8 port will definitely not come with our changes. That's too much changes at once for the merge. So what you want to do here might be for the birds ...

**Comment by Draise14** [comment]
haha, ok. I'll postpone this task.

**Comment by ReinerBforartists** [comment]
Good idea. I'll have a look at the other chapters which ones to postpone too :)

**Comment by ReinerBforartists** [comment]
Not longer valid. Closing.
