### ISSUE TITLE
PDF table of content confusion - add a master odt file

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Manual#157]
We need to have a look if we find a better way to merge our pdf files. The table of content should start with the chapters, not with the headlines of the content.

![tableofcontent](https://user-images.githubusercontent.com/13919702/70378474-006d4e00-1921-11ea-9bb6-899f894aa3f7.jpg)

![structure](https://user-images.githubusercontent.com/13919702/70378471-fcd9c700-1920-11ea-8dd3-aff603f13587.jpg)

**Comment by ReinerBforartists** [comment]
Changing this one to a bug. That's not how it was in the past.

**Comment by ReinerBforartists** [comment]
Quote from Narayan:

I have faced the issue you mentioned (outline numbers do not show up in TOC/bookmarks).
But that was in OpenOffice days (more than a decade ago).

Now apparently LibreOffice has solved the case, by introducing a separate outline: Tools > Chapter numbering.

In addition, you need to play some tricks:
1. Use File > Properties... menu. Switch to Description tab. In the Title field, copy the file's name.
2. Use the Tools > Chapter numbering... menu.
    By default, it starts with all paragraph headings.
    But insert the Title field at level 1.
    Thus the headings are pushed down by one level (H1 appears at Level 2, etc)
    Now for all of them, set the Number field as "1,2,3...",
   
     Then set the sublevels for all headings, so that the Heading n has a sublevel of (n+1) 
      (for example, Heading 2 has sublevel of 3.)

![numbering](https://user-images.githubusercontent.com/13919702/70391223-f86de680-19d2-11ea-9e2f-367dd537670d.jpg)

After this, check the odt file. 
Some of the headings will not show the outline numbers. This is a bug.

To solve that bug, click on each defective heading, and then press CTRL+0 (which resets it to text).
Immediately press CTRL+n (where n is the level of the header).
Now the outline number shows correctly,

Now go to the TOC of the file, click anywhere in it, and 
right-click.
From the context menu, select Update index.
The TOC will start showing the outline numbers.

You have to correct all the odt files like this.
Then refresh the master file (or probably you have to make another fresh master file).
Now the TOC will appear as expected.

Now export the master file to pdf.

**Comment by raindropsfromsky** [comment]
I think if the chapters themselves have a number like 7.1.10, then three levels are wasted at the top.

IMHO all the subdocuments in the master document (which form chapters in the book) should have only one level. Otherwise, the hierarchy will become too deep.  Deep hierarchies do not look pretty, because we have to use a different font size for each.

For example, suppose we have seven levels of headings (H1 to H7).
We have to keep a minimum difference of 2 font sizes between two successive heading levels.

So, if the font size for "default text" is 12, then-
font size for H7 = 14
font size for H6 = 16
font size for H5 = 18
font size for H4 = 20
font size for H3 = 22
font size for H2 = 24
font size for H1 = 26
font size for Title = 28

Further, most of the time, you see the last 3-4 headings in the text, which are in very small font.
This turns the manual ugly.

**Suggested remedy: Flatten the manual!** 
1. Introduce the idea of "Manual sections". Each section begins with a blank page with a title.
    Effectively, it resets the chapters under it to level 1.
    In addition, the section does not claim any level for itself.

2. Instead of splitting the topics accurately as in a _mindmap_, just combine 2-3 levels in a paragraph.
    For example, the **3D Viewport** can be covered in a single chapter.

3.  Not everything deserves to have a numbered (outlined) paragraph, as in legal documents.
     Just take a screenshot of a whole screen, and annotate various parts with numbers.
     Go on describing all numbered parts.
     These numbers have nothing to do with outline numbers. 

4.  If necessary, divide the chapter in "Parts".
    "Parts" are an extension of the "sections" idea: Everything under a "Part" is promoted to level 2.

5. The narrative about any given topic should be contained in a single uninterrupted chapter. 
    When it is divided into separate chapters, it becomes mathematically precise, but loses its flavor.

    This is just like chopping a paragraph into separate lines by entering ENTER after every period.
    The reader will never get the fluent experience of reading a paragraph!

How
would 
you 
react 
to 
this 
sentence, 
which 
is 
chopped 
in 
separate 
words
?

**Comment by ReinerBforartists** [comment]
Thanks for the detailed answer. I think it should go into this issue https://github.com/Bforartists/Manual/issues/158
since this issue here is about the bug to show all levels in a pdf file.

Could you give me a real life example please? How would you rewrite let's say 7.1.10?

**Comment by ReinerBforartists** [comment]
The solution to this problem here is to create a master document in Libre Office. This makes the usage of pdfsam obsolete then.

**Comment by ReinerBforartists** [comment]
Haha, i was just too stupid to use the right settings in pdfsam  XD

It would work now. But now this thread has turned into using a master file in libre office instead of pdfsam. So i'll keep this task open as a playground for future experiments.

![wrongsettings](https://user-images.githubusercontent.com/13919702/70455413-8d90de00-1aac-11ea-93fa-09b78c770ad9.jpg)

**Comment by ReinerBforartists** [comment]
Not a happy bunny with some first tests here. We loose our breadcrumbs. The formatting is shot down, the one from the master file is chosen. I haven't found a way to add a table of content for the sub chapters yet. And the bookmarks in a pdf file are messed up.

On top of that, it always asks me if i want to refresh the shortcuts when i open the file, Saving it after this step doesn't help anything.

All in all this is a worse solution compared to have them single files and merge them with PDF Sam.

Testfile is attached here:  [manual_structure.zip](https://github.com/Bforartists/Manual/files/3955262/manual_structure.zip)

![globalproblems](https://user-images.githubusercontent.com/13919702/70705205-e42c3100-1cd3-11ea-8595-cbfe57165e32.jpg)

![bookmarks](https://user-images.githubusercontent.com/13919702/70705212-e8584e80-1cd3-11ea-91f3-afa428bb6e0d.jpg)

**Comment by ReinerBforartists** [comment]
Oh my, what a unfinished can of worms is this? :D

I tried again, and saved the master file from one of the chapters by send. The formatting is now the style from the documents. I have a breadcrumb now. But the one from the first file, everywhere. The table of contents are now missing. It introduces tables in the design. And so on.

I call this feature broken. Narayan, maybe you have an idea here. I may overlook something. But i would say we keep our fingers away from this global document idea. And continue to merge the single PDF files with PDF Sam. Ways less trouble, and already working.

**Comment by raindropsfromsky** [comment]
Actually this behavior is well-documented.

1. If you have defined a style in subdocuments and also in master, then the
style in master is used.

2. If the master does not have a style with the same name, then it is taken
from the first subdocument.

3. Multiple subdocuments may have the named style (but with different
definitions).
    In that case, the definition from the first subdocument is used.
    The subsequent subdocuments are ignored.

   Therefore, if you change the sequence of subdocuments, some other
subdocument comes to the top of order.
   Then the master borrows the style definition from that subdocument.

When using Master and subdocuments, we need to observe the rules strictly,
and plan ahead.

LibreOffice has six types of styles: paragraph, character, page, frame,
list and table.
For best results, define all of them in the master itself.
And then whenever you start a new subdocument, the first thing you do is to
import all styles from the master.

*Step-1: In thr Styles section, use the "+" drop-down, and select "Load
styles..."*
[image: image.png]



*Step-2: Click on "From file..." button, at bottom*
[image: image.png]

*Step-3:*
Browse the file system and select the *Master*.
(Or any odt file that you have reserved as a style template).


I haven't studied what happens to the *field variables*, but I guess the
same logic is followed.
For example, if you insert *page number *in header/footer, the *page number*
is a global variable within the entire set.

So, you have to select a variable that pertains to the subdocument, and not
the master.
For example, you can insert the current heading (or title of the
subdocument) in the header/footer.
So you get a unique string for each chapter.

**Comment by ReinerBforartists** [comment]
Thanks for explanation. I still can'get it to work :)

The documentation of the Master document is very thin to say the least ^^

https://help.libreoffice.org/Writer/Master_Documents_and_Subdocuments

The german manual has a bit more information, but that's basically it. Without a youtube tutorial i wouldn't have found out how to do it. A good example of how i don't want to have our manual. It describes what it is, but how to use it is not described at all.

I have tried the field variables. And couldn't get the header or footer information from the single chapters. We are in the master document, so it uses the master document numbering and information.

> When using Master and subdocuments, we need to observe the rules strictly, and plan ahead.

This is all ways too much hassle. With PFDsam i drag the files into the software, change one setting, press the start button and i am done. This is the easier and more accurate solution. Since it arrives how i have created it. No overriding problem, no secret settings, no undocumented workflows to follow.

Closing this issue now. It was a nice and logical idea. But the conclusion after several tests is that we will officially continue with PDFSam.

You are still welcome to try to create a working Master document. But i give up here, and i most probably won't use it, even when you can get it to work. When there would be a single benefit over the PFDsam route, then this would be a different story. But i can't see one yet. We have just drawbacks. Style is already defined. Footer and header fits, and the result fits ( in case i don't forget to turn on the right setting, which i unfortunately forget from time to time ^^). Biggest drawback is: we loose the breadcrumbs from the header. And i don't want to loose this breadcrumbs under no circumstances. It is the guarantee to have a navigatable manual.
