### ISSUE TITLE
New structure of the reference manual

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Manual#158]
Narayan poked me to think about the current manual structure. And suggested some improvements.

We will try to create a new manual structure draft here.

> This 5th section would describe all editors:
> 
>     Editors for General use:
>         3D Viewport
>         Image Editor
>         UV Editor
>         Shader Editor
>         Compositor
>         Texture Node Editor
>         Video Sequencer
>         Movie Clip Editor
> 
>     Editors for Animation:
>         Dope Sheet
>         Timeline
>         Graph Editor
>         Drivers
>         Nonlinear Animation
> 
>     Editots for Scripting
>         Text editor
>         Python Console
>         Info
> 
>     Editors for Data handling:
>         Outliner
>         Properties
>         file Browser
>         Preferences

**Comment by ReinerBforartists** [comment]
What we currently have is this. As a next step i will add the still missing chapters to this list. And then we can start to throw things around a bit.

1 Installing Bforartists.pdf - 150 Kb
2 Standard Keymap.pdf - 350 Kb
3 Interface.pdf - 566 Kb
4 Workspaces.pdf - 1.14 Mb
5 Topbar and Statusbar.pdf - 1.76 Mb
6 Editors introduction.pdf - 894 kB
7 Editors - 3D View - 292 kB
7.1 Editors - 3D View - Tool Shelf.pdf - 346 kB
7.1.1 Editors - 3D View - Tool Shelf - Object Mode.pdf - 562 kB
7.1.2 Editors - 3D View - Tool Shelf - Mesh - Edit Mode.pdf - 1.17 Mb
7.1.3 Editors - 3D View - Tool Shelf - Mesh - Sculpt Mode.pdf - 246 kb
7.1.4 Editors - 3D View - Tool Shelf - Mesh - Vertex Paint Mode.pdf - 191 kb
7.1.5 Editors - 3D View - Tool Shelf - Mesh - Weight Paint Mode.pdf - 310 kb
7.1.6 Editors - 3D View - Tool Shelf - Mesh - Texture Paint Mode.pdf - 240 kb
7.1.7 Editors - 3D View - Tool Shelf - Mesh - Particle Edit Mode.pdf - 138 kb
7.1.8 Editors - 3D View - Tool Shelf - Curve - Edit Mode.pdf - 308 kb
7.1.9 Editors - 3D View - Tool Shelf - Surface - Edit Mode.pdf - 35 kb
7.1.10 Editors - 3D View - Tool Shelf - Metaball - Edit Mode.pdf - 35 kb
7.1.11 Editors - 3D View - Tool Shelf - Text - Edit Mode.pdf - 35 kb
7.1.12 Editors - 3D View - Tool Shelf - Grease Pencil - Edit Mode.pdf - 216 kb
7.1.13 Editors - 3D View - Tool Shelf - Grease Pencil - Sculpt Mode - 70 kb
7.1.14 Editors - 3D View - Tool Shelf - Grease Pencil - Draw Mode.pdf - 212 kb
7.1.15 Editors - 3D View - Tool Shelf - Grease Pencil - Weight Paint Mode - 44 kb
7.1.16 Editors - 3D View - Tool Shelf - Armature - Edit Mode.pdf - 356 kb
7.1.17 Editors - 3D View - Tool Shelf - Armature - Pose Mode.pdf - 117 kb
7.1.18 Editors - 3D View - Tool Shelf - Lattice - Edit Mode - 35 kb
7.2 Editors - 3D View - Header.pdf - 337 kB
7.2.1 Editors - 3D View - Header tools and Options.pdf - 1.79 Mb
7.2.2 Editors - 3D View - Header - Quick Menu.pdf - 100 Kb
7.2.3 Editors - 3D View - Header - View Menu.pdf - 763 Kb
7.2.4 Editors - 3D View - Header - Navigation Menu.pdf - 140 Kb
7.2.5 Editors - 3D View - Header - Select Menu.pdf - 1.12 Mb
7.2.6 Editors - 3D View - Header - Add Menu.pdf - 67.5 Kb
7.2.7 Editors - 3D View - Header - Object menu.pdf - 2.1 Mb
7.2.8 Editors - 3D View - Header - Edit mode - Add menu.pdf - 68 Kb
7.2.9 Editors - 3D View - Header - Mesh - Edit mode - Mesh menu.pdf - 1.3 Mb
7.2.10 Editors - 3D View - Header - Mesh - Edit Mode - Vertex Menu.pdf - 495 kb
7.2.11 Editors - 3D View - Header - Mesh - Edit mode - Edge Menu.pdf - 520 kb
7.2.12 Editors - 3D View - Header - Mesh - Edit mode - Faces menu.pdf - 360 kb
7.2.13 Editors - 3D View - Header - Mesh - Edit mode - UV menu.pdf - 200 kb
7.2.14 Editors - 3D View - Header - Mesh - Sculpt mode - Sculpt menu.pdf - 50 kb
7.2.15 Editors - 3D View - Header - Mesh - Sculpt mode - Brush menu.pdf - 35 kb
7.2.16 Editors - 3D View - Header - Mesh - Sculpt mode - Mask menu.pdf - 69 kb
7.2.17 Editors - 3D View - Header - Mesh - Vertex Paint mode - Paint menu.pdf - 100 kb
7.2.18 Editors - 3D View - Header - Mesh - Vertex Paint mode - Brush menu.pdf - 35 kb
7.2.19 Editors - 3D View - Header - Mesh - Weight Paint mode - Weights menu.pdf - 335 kb
7.2.20 Editors - 3D View - Header - Mesh - Weight Paint mode - Brush menu.pdf - 32 kb
7.2.21 Editors - 3D View - Header - Mesh - Texture Paint mode - Brush menu.pdf - 38 kb
7.2.22 Editors - 3D View - Header - Curve - Edit mode - Curve menu.pdf - 577 kb
7.2.23 Editors - 3D View - Header - Curve & Surface - Edit mode - Control points menu.pdf - 228 kb
7.2.24 Editors - 3D View - Header - Curve & Surface - Edit mode - Segments menu.pdf - 64 kb
7.2.25 Editors - 3D View - Header - Metaball - Edit mode - Metaball menu.pdf - 488 kb
7.2.26 Editors - 3D View - Header - Text - Edit mode - Edit menu.pdf - 34 kb
7.2.27 Editors - 3D View - Header - Text - Edit mode - Font menu.pdf - 86 kb
7.2.28 Editors - 3D View - Header - Grease Pencil - Edit mode - Grease Pencil menu.pdf - 366 kb
7.2.29 Editors - 3D View - Header - Grease Pencil - Edit mode - Stroke menu.pdf - 271 kb
7.2.30 Editors - 3D View - Header - Grease Pencil - Edit mode - Points menu.pdf - 101 kb
7.2.31 Editors - 3D View - Header - Grease Pencil - Draw mode - Draw menu.pdf - 123 kb
7.2.32 Editors - 3D View - Header - Grease Pencil - Weight Paint Mode - Weights Menu.pdf - 94 kb
7.2.33 Editors - 3D View - Header - Armature - Edit mode - Armature menu.pdf - 627 kb
7.2.34 Editors - 3D View - Header - Armature - Pose mode - Pose menu.pdf - 818 kb
7.2.35 Editors - 3D View - Header - Lattice - Edit mode - Lattice menu.pdf - 515 kb
7.2.36 Editors - 3D View - Header - Particle - Particle mode - Particle menu.pdf - 98 kb
7.3 Editors - 3D View - Sidebar.pdf - 719 Kb
7.3.1 Editors - 3D View - Sidebar - Mini Lightlib.pdf - 574 Kb
8 Editors - Image Editor.pdf - 215 Kb
8.1 Editors - Image Editor - Header.pdf - 90 Kb
8.1.1 Editors - Image Editor - Header - View menu.pdf - 212 Kb
8.1.2 Editors - Image Editor - Header - Image menu.pdf - 158 Kb
8.1.3 Editors - Image Editor - Header - Select menu.pdf - 40 Kb
8.1.4 Editors - Image Editor - Header - Add menu.pdf - 55 Kb
8.1.5 Editors - Image Editor - Header - Mask menu.pdf - 128 Kb
8.1.6 Editors - Image Editor - Header - Header Tools.pdf - 180 Kb
8.2 Editors - Image Editor - Tool Shelf.pdf - 180 Kb
8.3 Editors - Image Editor - Sidebar.pdf - 75Kb 
8.3.1 Editors - Image Editor - Sidebar - Tools Tab in Paint Mode.pdf - 900 Kb
20 Editors - Text Editor.pdf - 334 Kb
21 Editors - Python Console.pdf - 66 Kb
22 Editors - Info Editor.pdf - 66 Kb
23 Editors - Toolbar.pdf - 1.27 Mb
24 Editors - Outliner.pdf - 660 Kb
25 Editors - Properties Editor.pdf - 660 Kb
25.1 Editors - Properties Editor - Tools Tab.pdf - 230 Kb
25.1.1 Editors - Properties Editor - Tools Tab - Object Mode.pdf - 40 Kb
25.1.2 Editors - Properties Editor - Tools Tab - Edit Mode.pdf - 170 Kb
25.1.3 Editors - Properties Editor - Tools Tab - Pose mode.pdf - 33 Kb
25.1.4 Editors - Properties Editor - Tools Tab - Sculpt Mode.pdf - 969 Kb
25.1.5 Editors - Properties Editor - Tools Tab - Vertex Paint Mode.pdf - 992 Kb
25.1.6 Editors - Properties Editor - Tools Tab - Weight Paint Mode.pdf - 917 Kb
25.1.7 Editors - Properties Editor - Tools Tab - Texture Paint Mode.pdf - 1.6 Mb
25.1.8 Editors - Properties Editor - Tools Tab - Particle Edit Mode.pdf - 155 Kb
25.1.9 Editors - Properties Editor - Tools Tab - Grease Pencil Object.pdf - 388 Kb
25.2 Editors - Properties Editor - Render Tab.pdf - 1 Mb
25.16 Editors - Properties Editor - Bone Constraints.pdf - 756 Kb
26 Editors - File browser.pdf - 370 Kb
27 Editors - Preferences.pdf - 2.05 Mb
28 Data System.pdf - 93 Kb
29 Advanced - Command Line.pdf - 70 Kb
30 Advanced - Scripting & Extending Bforartists.pdf - 160 Kb
31 Advanced - Working Limits.pdf - 46 Kb
32 Troubleshooting.pdf - 93 Kb
33 Glossary.pdf - 82 Kb
34 About this Manual.pdf - 38 Kb
35 Bforartists History.pdf - 100 Kb
36 Manual Update History.pdf - 20 Kb

**Comment by ReinerBforartists** [comment]
Okay, done. The exact estimated numbers of chapters that are not written yet cannot be told at this point. We need to write the chapters to tell what sub chapters we need. PDF means this chapter is already online.

---------------------


1 Installing Bforartists.pdf
2 Standard Keymap.pdf
3 Interface.pdf
4 Workspaces.pdf
5 Topbar and Statusbar.pdf
6 Editors introduction.pdf

7 Editors - 3D View.pdf
7.1 Editors - 3D View - Tool Shelf.pdf
7.1.1 Editors - 3D View - Tool Shelf -Object Mode.pdf
7.1.10 Editors - 3D View - Tool Shelf - Metaball - Edit Mode.pdf
7.1.11 Editors - 3D View - Tool Shelf - Text - Edit Mode.pdf
7.1.12 Editors - 3D View - Tool Shelf - Grease Pencil - Edit Mode.pdf
7.1.13 Editors - 3D View - Tool Shelf - Grease Pencil - Sculpt Mode.pdf
7.1.14 Editors - 3D View - Tool Shelf - Grease Pencil - Draw Mode.pdf
7.1.15 Editors - 3D View - Tool Shelf - Grease Pencil - Weight Paint Mode.pdf
7.1.16 Editors - 3D View - Tool Shelf - Armature - Edit Mode.pdf
7.1.17 Editors - 3D View - Tool Shelf - Armature - Pose Mode.pdf
7.1.18 Editors - 3D View - Tool Shelf - Lattice - Edit Mode.pdf
7.1.2 Editors - 3D View - Tool Shelf - Mesh - Edit Mode.pdf
7.1.3 Editors - 3D View - Tool Shelf - Mesh - Sculpt Mode.pdf
7.1.4 Editors - 3D View - Tool Shelf - Mesh - Vertex Paint Mode.pdf
7.1.5 Editors - 3D View - Tool Shelf - Mesh - Weight Paint Mode.pdf
7.1.6 Editors - 3D View - Tool Shelf - Mesh - Texture Paint Mode.pdf
7.1.6 Editors - 3D View - Tool Shelf - Mesh - Textute Paint Mode.pdf
7.1.7 Editors - 3D View - Tool Shelf - Mesh - Particle Edit Mode.pdf
7.1.8 Editors - 3D View - Tool Shelf - Curve - Edit Mode.pdf
7.1.9 Editors - 3D View - Tool Shelf - Surface - Edit Mode.pdf
7.2 Editors - 3D View - Header.pdf
7.2.1 Editors - 3D View - Header tools and Options.pdf
7.2.10 Editors - 3D View - Header - Mesh - Edit Mode - Vertex Menu.pdf
7.2.11 Editors - 3D View - Header - Mesh - Edit mode - Edge Menu.pdf
7.2.12 Editors - 3D View - Header - Mesh - Edit mode - Faces menu.pdf
7.2.13 Editors - 3D View - Header - Mesh -Edit mode - UV menu.pdf
7.2.14 Editors - 3D View - Header - Mesh - Sculpt mode - Sculpt menu.pdf
7.2.15 Editors - 3D View - Header - Mesh - Sculpt mode - Brush menu.pdf
7.2.16 Editors - 3D View - Header - Mesh - Sculpt mode - Mask menu.pdf
7.2.17 Editors - 3D View - Header - Mesh - Vertex Paint mode - Paint menu.pdf
7.2.18 Editors - 3D View - Header - Mesh - Vertex Paint mode - Brush menu.pdf
7.2.19 Editors - 3D View - Header - Mesh - Weight Paint mode -Weights menu.pdf
7.2.2 Editors - 3D View - Header - Quick Menu.pdf
7.2.20 Editors - 3D View - Header - Mesh - Weight Paint mode - Brush menu.pdf
7.2.21 Editors - 3D View - Header - Mesh - Texture Paint mode - Brush menu.pdf
7.2.22 Editors - 3D View - Header - Curve -Edit mode - Curve menu.pdf
7.2.23 Editors - 3D View - Header - Curve & Surface - Edit mode - Control points menu.pdf
7.2.24 Editors - 3D View - Header - Curve & Surface - Edit mode - Segments menu.pdf
7.2.25 Editors - 3D View - Header - Metaball -Edit mode - Metaball menu.pdf
7.2.26 Editors - 3D View - Header - Text - Edit mode - Edit menu.pdf
7.2.27 Editors - 3D View - Header - Text - Edit mode - Font menu.pdf
7.2.28 Editors - 3D View - Header - Grease Pencil - Edit mode - Grease Pencil menu.pdf
7.2.29 Editors - 3D View - Header - Grease Pencil - Edit mode - Stroke menu.pdf
7.2.3 Editors - 3D View - Header - View Menu.pdf
7.2.30 Editors - 3D View - Header - Grease Pencil - Edit mode - Points menu.pdf
7.2.31 Editors - 3D View - Header - Grease Pencil - Draw mode - Draw menu.pdf
7.2.32 Editors - 3D View - Header - Grease Pencil - Weight Paint Mode - Weights Menu.pdf
7.2.33 Editors - 3D View - Header - Armature - Edit mode - Armature menu.pdf
7.2.34 Editors - 3D View - Header - Armature -Pose mode - Pose menu.pdf
7.2.35 Editors - 3D View - Header - Lattice - Edit mode - Lattice menu.pdf
7.2.36 Editors - 3D View - Header - Particle - Particle mode - Particle menu.pdf
7.2.4 Editors - 3D View - Header - Navigation Menu.pdf
7.2.5 Editors - 3D View - Header - Select Menu.pdf
7.2.6 Editors - 3D View - Header - Add Menu.pdf
7.2.7 Editors - 3D View - Header - Object menu.pdf
7.2.8 Editors - 3D View - Header - Edit mode - Add menu.pdf
7.2.9 Editors - 3D View - Header - Mesh - Edit mode - Mesh menu.pdf
7.3 Editors - 3D View - Sidebar.pdf
7.3.1 Editors - 3D View - Sidebar - Mini Lightlib.pdf

8 Editors - Image Editor.pdf
8.1 Editors - Image Editor - Header.pdf
8.1.1 Editors - Image Editor - Header - View menu.pdf
8.1.2 Editors - Image Editor - Header - Image menu.pdf
8.1.3 Editors - Image Editor - Header - Select menu.pdf
8.1.4 Editors - Image Editor - Header - Add menu.pdf
8.1.5 Editors - Image Editor - Header - Mask menu.pdf
8.1.6 Editors - Image Editor - Header - Header Tools.pdf
8.2 Editors - Image Editor - Tool Shelf.pdf
8.3 Editors - Image Editor - Sidebar.pdf
8.3.1 Editors - Image Editor - Sidebar - Tools Tab in Paint Mode.pdf

9 Editors - UV Editor
9.1 Editors - UV Editor – Header
9.1.xx Editors - UV Editor - Header - XXX menu
9.1.xx Editors - UV Editor - Header - XXX menu
9.1.xx Editors - UV Editor - Header - XXX menu
9.1.xx Editors - UV Editor - Header - XXX menu
9.1.xx Editors - UV Editor - Header - XXX menu
9.1.xx Editors - UV Editor - Header - XXX menu
9.1.xx Editors - UV Editor - Header - Header Tools
9.2 Editors - UV Editor - Tool Shelf
9.3 Editors - UV Editor – Sidebar
9.3.x Editors - UV Editor - XXX tab in …
9.3.x Editors - UV Editor - XXX tab in …
9.3.x Editors - UV Editor - XXX tab in ...
10 Editors - Shader Editor
10.1 Editors - Shader Editor – Header
10.1.x Editors - Shader Editor - Header - XXX menu
10.1.x Editors - Shader Editor - Header - XXX menu
10.1.x Editors - Shader Editor - Header - XXX menu
10.1.x Editors - Shader Editor - Header - XXX menu
10.1.x Editors - Shader Editor - Header - Header Tools
10.2 Editors - Shader Editor - Tool Shelf
10.3 Editors - Shader Editor - Sidebar - XXX Tab
10.3 Editors - Shader Editor - Sidebar - XXX Tab
10.3 Editors - Shader Editor - Sidebar - XXX Tab
10.3 Editors - Shader Editor - Sidebar - XXX Tab
10.3 Editors - Shader Editor - Sidebar - XXX Tab
10.3 Editors - Shader Editor - Sidebar - XXX Tab
10.3 Editors - Shader Editor - Sidebar - XXX Tab
10.3 Editors - Shader Editor - Sidebar - XXX Tab
11 Editors - Compositor Editor
11.1 Editors - Compositor Editor – Header
11.1.x Editors - Compositor Editor - Header - XXX menu
11.1.x Editors - Compositor Editor - Header - XXX menu
11.1.x Editors - Compositor Editor - Header - XXX menu
11.1.x Editors - Compositor Editor - Header - XXX menu
11.1.x Editors - Compositor Editor - Header - Header Tools
11.2 Editors - Compositor Editor - Tool Shelf
11.3 Editors - Compositor Editor - Sidebar - XXX Tab
11.3 Editors - Compositor Editor - Sidebar - XXX Tab
11.3 Editors - Compositor Editor - Sidebar - XXX Tab
11.3 Editors - Compositor Editor - Sidebar - XXX Tab
11.3 Editors - Compositor Editor - Sidebar - XXX Tab
11.3 Editors - Compositor Editor - Sidebar - XXX Tab
11.3 Editors - Compositor Editor - Sidebar - XXX Tab
11.3 Editors - Compositor Editor - Sidebar - XXX Tab
12 Editors - Texture Node Editor
12.1 Editors - Texture Node  Editor – Header
12.1.x Editors - Texture Node  Editor - Header - XXX menu
12.1.x Editors - Texture Node  Editor - Header - XXX menu
12.1.x Editors - Texture Node  Editor - Header - XXX menu
12.1.x Editors - Texture Node  Editor - Header - XXX menu
12.1.x Editors - Texture Node  Editor - Header - Header Tools
12.2 Editors - Texture Node  Editor - Tool Shelf
12.3 Editors - Texture Node  Editor - Sidebar - XXX Tab
12.3 Editors - Texture Node  Editor - Sidebar - XXX Tab
12.3 Editors - Texture Node  Editor - Sidebar - XXX Tab
12.3 Editors - Texture Node  Editor - Sidebar - XXX Tab
12.3 Editors - Texture Node  Editor - Sidebar - XXX Tab
12.3 Editors - Texture Node  Editor - Sidebar - XXX Tab
12.3 Editors - Texture Node  Editor - Sidebar - XXX Tab
12.3 Editors - Texture Node  Editor - Sidebar - XXX Tab
13 Editors - Video Sequence Editor
13.1 Editors - Video Sequence Editor – Header
13.1.x Editors - Video Sequence Editor - Header - XXX menu
13.1.x Editors - Video Sequence Editor - Header - XXX menu
13.1.x Editors - Video Sequence Editor - Header - XXX menu
13.1.x Editors - Video Sequence Editor - Header - XXX menu
13.1.x Editors - Video Sequence Editor - Header - XXX menu
13.1.x Editors - Video Sequence Editor - Header - XXX menu
13.1.x Editors - Video Sequence Editor - Header - XXX menu
13.1.x Editors - Video Sequence Editor - Header - XXX menu
13.1.x Editors - Video Sequence Editor - Header - Header Tools
13.2 Editors - Video Sequence Editor - Sidebar- XXX Tab
13.2 Editors - Video Sequence Editor - Sidebar- XXX Tab
14 - Movie Clip Editor
14.1 - Movie Clip Editor – Header
14.1.X - Movie Clip Editor - Header - XXX menu
14.1.X - Movie Clip Editor - Header - XXX menu
14.1.X - Movie Clip Editor - Header - XXX menu
14.1.X - Movie Clip Editor - Header - XXX menu
14.1.X - Movie Clip Editor - Header - XXX menu
14.1.X - Movie Clip Editor - Header - Header Tools
14.1.X - Movie Clip Editor - Header - Tool Shelf
14.1.X - Movie Clip Editor - Sidebar- XXX Tab
14.1.X - Movie Clip Editor - Sidebar- XXX Tab
15 - Dope Sheet Editor
15 - Dope Sheet Editor
15 - Dope Sheet Editor
15 - Dope Sheet Editor
15 - Dope Sheet Editor
15 - Dope Sheet Editor
15 - Dope Sheet Editor
15 - Dope Sheet Editor
15 - Dope Sheet Editor
15 - Dope Sheet Editor
15 - Dope Sheet Editor
15 - Dope Sheet Editor
15 - Dope Sheet Editor

16 - Timeline Editor
16 - Timeline Editor
16 - Timeline Editor
16 - Timeline Editor
16 - Timeline Editor
16 - Timeline Editor
16 - Timeline Editor
16 - Timeline Editor
16 - Timeline Editor
17 Graph Editor
17 Graph Editor
17 Graph Editor
17 Graph Editor
17 Graph Editor
17 Graph Editor
17 Graph Editor
17 Graph Editor
17 Graph Editor
17 Graph Editor
17 Graph Editor
17 Graph Editor
17 Graph Editor
17 Graph Editor
18 Drivers Editor
18 Drivers Editor
18 Drivers Editor
18 Drivers Editor
18 Drivers Editor
18 Drivers Editor
18 Drivers Editor
18 Drivers Editor
18 Drivers Editor
19 NLA Editor
19 NLA Editor
19 NLA Editor
19 NLA Editor
19 NLA Editor
19 NLA Editor
19 NLA Editor
19 NLA Editor
19 NLA Editor
19 NLA Editor


20 Editors - Text Editor.pdf
21 Editors - Python Console.pdf
22 Editors - Info Editor.pdf
23 Editors - Toolbar.pdf
24 Editors - Outliner.pdf
25 Editors - Properties Editor.pdf
25.1 Editors - Properties Editor - Tools Tab.pdf
25.1.1 Editors - Properties Editor - Tools Tab - Object Mode.pdf
25.1.2 Editors - Properties Editor - Tools Tab- Edit Mode.pdf
25.1.3 Editors - Properties Editor - Tools Tab - Pose mode.pdf
25.1.4 Editors - Properties Editor - Tools Tab - Sculpt Mode.pdf
25.1.5 Editors - Properties Editor - Tools Tab - Vertex Paint Mode.pdf
25.1.6 Editors - Properties Editor - Tools Tab - Weight Paint Mode.pdf
25.1.7 Editors - Properties Editor - Tools Tab - Texture Paint Mode.pdf
25.1.8 Editors - Properties Editor - Tools Tab - Particle Edit Mode.pdf
25.1.9 Editors - Properties Editor - Tools Tab - Grease Pencil Object.pdf
25.16 Editors - Properties Editor - Bone Constraints.pdf
25.2 Editors - Properties Editor - Render Tab.pdf
25.7 Editors - Properties Editor - Object Tab.pdf
26 Editors - File browser.pdf
27 Editors - Preferences.pdf


28 Data System.pdf
29 Advanced - Command Line.pdf 
30 Advanced - Scripting & Extending Bforartists.pdf
31 Advanced - Working Limits.pdf
32 Troubleshooting.pdf
33 Glossary.pdf
34 About this Manual.pdf
35 Bforartists History.pdf
36 Manual Update History.pdf

**Comment by ReinerBforartists** [comment]
Narayan, could you please give me a real life example? How would you rewrite let's say 7.1.10?

**Comment by raindropsfromsky** [comment]
Sure, but I am traveling. So will be able to do this after 2 days.

BTW are you using a "master+sub-documents" document structure?
I am not able to find the master in the list.

So how do you convert them all into a single pdf?
Do you make individual pdfs and then stitch them together with Briss/pdfsam?
Or make a master odt (with all subfolders in it), and then export a pdf?

**Comment by ReinerBforartists** [comment]
No hurry. You decide if and when :)

There is indeed no master file. That would be too unhandy for me. It's single odt files, and i export them to single pdf files. Which i merge with pdfsam then.

**Comment by raindropsfromsky** [comment]
> There is indeed no master file. That would be too unhandy for me. It's single odt files, and i export them to single pdf files. Which i merge with pdfsam then.

Ah! That's a basic reason why the bookmarks are messed up: When pdfsam joins the individual chapter pdf files, it simply joins the lists of bookmarks also. Thus, even if a pdf file is designed at the third level, its bookmarks will be placed at level-1. 

For example, take this file:
7.2.18 Editors - 3D View - Header - Mesh - Vertex Paint mode - Brush menu.pdf
- It begins at level#3 from the top of the manual.
- In other words, its **Title** should be at Level#3 of the RM.
- And its **H1 headings** should be at Level#4 of the RM.
- Similarly, its **H2 headings** should be at level#5 of the RM.

But when you export this file, this does NOT happen!
What happens actually is this:
- Its **Title** has no value. </br>(This is only because you haven't yet added the Title to the chapter outline) 
- Its  **H1 headings** are at Level#1 of the RM.
- Its  **H2 headings** are at Level#2 of the RM.
- Its  **H3 headings** are at Level#3 of the RM.

This repeats with all individual pdf files.

In other words, your hierarchy is lost, not only in TOC+bookmarks, but also in the formatting of your headings!

That's why it is best to use the master+sub-document structure.
It's simple to implement.

Of course, using chapter outline will also salvage the situation.
But that's not an elegant solution.

**Comment by ReinerBforartists** [comment]
So we must merge all odt files into one file? Phew O_O

**Comment by raindropsfromsky** [comment]
No. The master is just a placeholder. All sub-documents retains their own form.
They get edited independently.

If you combine all odts, LibreOffice will start crashing, and believe me, you will lose most of the content and/or formatting. And it is not predictable, either. I have lost months of hard work that way.

**Comment by ReinerBforartists** [comment]
Yeah, learning the hard way is very unfunny ^^

How does this master feature work? Is this done from a specific odt document?

**Comment by raindropsfromsky** [comment]
There's a simple process to be followed.
The existing odt files are simply treated s sub-documents.
Insert them in the master document, along just like inserting a table/image/object.
But it remains linked (not physically inserted)

**Comment by ReinerBforartists** [comment]
I see. You never stop learning. Thanks :)

I guess this also makes the step to merge the single pdf files with pdfsam obsolete then?

**Comment by raindropsfromsky** [comment]
In your LibreOffice help, the **master documents** are explained here:
file:///C:/Program%20Files/Util/LibreOffice/help/en-US/text/swriter/guide/globaldoc_howtos.html

(Your installation path would be a little different)

**Comment by raindropsfromsky** [comment]
Yes, when you export the master document, you get a fully integrated pdf file.

**Comment by ReinerBforartists** [comment]
Perfect :)

**Comment by raindropsfromsky** [comment]
BTW it does not end there!
LibreOffice writer allows you to promote/demote chapters, using the controls in the Navigation bar.
Or move the whole document up/down in the sequence.

**Comment by ReinerBforartists** [comment]
That's indeed quite handy :)

Now back to our general structure problem. As told, i am looking forward to the real life example.

**Comment by raindropsfromsky** [comment]
Sure!

**Comment by raindropsfromsky** [comment]
BTW I am not quite sure what the chapter's long name actually conveys.
Does it reflect the sequence to be followed to come up to that GUI?
I guess not.

For example, 
25.1.6 Editors - Properties Editor - Tools Tab - Weight Paint Mode.pdf

How do I start, and how do I land at the **Weight Paint Mode**?

Besides, in many cases, the same GUI pops up with a hotkey also.
(Although B4a has removed many hotkeys, this is still true of many controls.)

In that case, the user will not be able to know the equivalent menu path.
And therefore he won't be able to locate the chapter to look up.

To conclude, the chapter's names may not help the user (not 100% of the time).
Therefore there should be other ways to pinpoint the location within the RM.

**Comment by ReinerBforartists** [comment]
It's a breadcrumb. As told before, that way you will find the content in the manual, and vice versa, from the manual the UI lcoation.

The editor type is the Properties editor. The tab where the content is is the Tools tab. And the content schows when you are in Weight Painting in the 3D view.

The 3D view has modes. The content of the UI changes, dependant of in what mode you are.

**Comment by ReinerBforartists** [comment]
I have created a test file now to toy around with possible changes.

[manual_structure.zip](https://github.com/Bforartists/Manual/files/3955270/manual_structure.zip)

Not a happy bunny with a globals document yet. See this issue here: PDF table of content confusion - add a master odt file #157

**Comment by ReinerBforartists** [comment]
Thanks for all the input and the ideas so far. I am closing this task now since it contains too much much mixed topics to be useful for further improvements.

Please make a single tracker issue for single improvements. The manual is now feature complete. And this means we can toy around at it at a one by one base.
