### ISSUE TITLE
Branch Proposal - Publicity for Social Networks

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#16]
# Branch Proposal - Publicity Archive for Social Networks

### Case 
I store image files locally and manage the facebook page with them. It has been fun managing that page and I think I've been organized and have an alright strategy - though frequency has lacked. Iterations have been slow due to slow activity online - and busy personal life. 
But with that said, this archive could easily be pushed to Twitter and Instagram too. 
The problem is, if I have a harddrive glitch, or I loose access or something - then these files and workflow could get lost. 
I thought it would be a good idea to store these online in the documentation community of Bforartists instead of a propriety online server that Bforartists has no access too, to keep it opensource and open to community input/tasks. 
I also want to create more power to the leaders of Bforartists to delegate publicity to Facebook, Twitter and/or Instagram by creating tasks that I can work with in the documentation tracker. I often check the news part of the forums, but sometimes my coordination is off and I publish late. So.. I think this could be a good workaround.

### Task
Create a Branch with Publicity Archive 

### Details
Branch Name: **Publicity_Archive**

**Comment by ReinerBforartists** [comment]
Hey Draise,

Hm, i thought this is all in the planning and under discussion. Where exactly have you created a branch now? I can't find a new branch online.

I personally would not be so happy with promotional material inside of the manual repository. It doesn't belong there. Shall i create a repository for the promotional material instead? That would imho be the better solution.

**Comment by Draise14** [comment]
Hmm.. it's uploading? I did the "Create Branch" from Tortoise Git. 

A new repository for Publicity? That would be organized yeah. 

I do like the splitting of repositories based on workflows for the concept of Bforartists. Tidy, clean.

### Repositories
- Software
- Documentation
- Publicity
- Education/Tutorials? ([Task](https://github.com/Bforartists/Bforartists/issues/241))

**Comment by ReinerBforartists** [comment]
Yeah, but to what repository? We have currently two. Bforartists, and the manual :)

Okay, i'll create a new repository tomorrow. I think that we can manage publicity and educational material and turorials in one repository, divided by folders.

**Comment by Draise14** [comment]
The manual one, as this is a task in the manual repository.

**Comment by Draise14** [comment]
hahaha, sure, I'll clean up and close this. Should we make a task in the main area to make the Publicity/Tutorial repository?

**Comment by ReinerBforartists** [comment]
Not necessary. I need to invite you then anyways.
