### ISSUE TITLE
Grant contributor access to @cyberfoxhax

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#164]
@cyberfoxhax would like to contribute to the documentation, but is not a contributor. 

Can we give him access?

**Comment by ReinerBforartists** [comment]
Yeah, sure :)

**Comment by ReinerBforartists** [comment]
Invitation is on its way

**Comment by CyberFoxHax** [comment]
thanks, though putting the... enthusiasm in #163, not sure what i should be doing from this point on.

**Comment by ReinerBforartists** [comment]
Didn't want to discourage you. You could still help with writing chapters and correcting my bad english :)

Now you have invested lots of work into your idea, and this makes you of course demotivated to try anything again :/

For such vital things it is best to ask beforehand. Then we can discuss all aspects before you spend hours of work at it. That's what the tracker is good for. Please make a tracker issue for any idea you have.

The discussion is still open by the way. Final decision is not done yet.
