### ISSUE TITLE
Please use the bookmarks at 150% zoom (not at "whole page" zoom level)

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Manual#169]
The current default zoom factor of the pdf manual is set at "full page". If the reader clicks on any bookmark, the page opens with this zoom factor. Each time the reader has to zoom in again to 150% for comfortable reading. This is tedious.

Instead, the pdf file should _always_ open at 150% zoom, and the bookmark panel should be open by default. Please select the export settings of LibreOffice accordingly.

(Most laptop screens are FHD nowadays, and they can simultaneously show the pdf manual at 150% zoom and also the bookmark panel.)

**Comment by ReinerBforartists** [comment]
Thanks for the idea. I'll have a look if this is is possible. First experiments has unfortunately not shown any differences in my browser and Foxit Reader so far, no matter what settings i choose. Seems that those settings are ignored. We will see.

**Comment by raindropsfromsky** [comment]
Have you tried the correct settings?

First, select the menu:  **File > Export as... > Export as pdf**

A multitab window pops up.

**In the "General" tab:**
![image](https://user-images.githubusercontent.com/9047168/75625685-84fcff00-5be6-11ea-8718-41e6248aa62d.png)

(Untick the "Create pdf form" option)

**In the "Initial view" tab:**
![image](https://user-images.githubusercontent.com/9047168/75625720-e329e200-5be6-11ea-9d5b-f40bdabd649e.png)
These are NOT the default options,. You will have to change them all!

**Comment by ReinerBforartists** [comment]
Thanks for the shots. I haven't tried anything fancy so far, just made a first test. I am not assigned here yet. I can't fix all issues at once, just one by one ^^

Does this changes stick with the odt file then? Or do we need to repeat this steps again and again with every export? In first case you can assign and make the changes if you want.

**Comment by raindropsfromsky** [comment]
I did some experiments and concluded that the settings get saved at application level.
(In other words, LibreOffice remembers the last settings used for exporting the file as pdf.)

But if this task is done by multiple people, all of them should remember to change the workflow.

Secondly, I don't know if the settings change when the pdf files are combined with pdfSAM.
Logically, it should be having its own settings.

**Comment by ReinerBforartists** [comment]
Thanks for checking.  That's what i have feared ^^

In general this is more a finishing touch task, when we are through with filling in all content. First make it working, then make it nice ...

**Comment by ReinerBforartists** [comment]
I have changed the settings to your values now. Vivaldi does not care the slightest about it. And Foxit reader opens that way anyways since always.

The following chapter is exported with your settings. Could you please have a look if this makes a difference at your end?

[10 Editors - Shader Editor.pdf](https://github.com/Bforartists/Manual/files/4286242/10.Editors.-.Shader.Editor.pdf)

------------------------------------

![foxit](https://user-images.githubusercontent.com/13919702/75861337-89e7cb80-5dfd-11ea-8dcb-a0a16dd841ea.jpg)

![vivaldi](https://user-images.githubusercontent.com/13919702/75861347-8ce2bc00-5dfd-11ea-955c-16cfe2176bca.jpg)

**Comment by raindropsfromsky** [comment]
The file opens perfectly, as desired. 

I opened with some other files that have other settings (a different zoom factor, the bookmark panel is closed). They open in their own way consistently. 

Opening a file with one setting does not change the default view options of another file.

So far so good. The next question is, if all the pdf files have the same settings, what does pdfSAM do with the final file?

I could not find any free app that changes the pdf file properties. Most Internet resources talk about using Adobe Acrobat.

**Comment by ReinerBforartists** [comment]
Okay, then i will use these settings in the future. Thanks for checking :)

Let's have a look to add your two screenshots to the repository somewhere.

PDFSam, well , there is not this much that you can adjust. And there is little that we can do here. We need something to join the pdf files. The only thing that i do is to change the defaults for the bookmarks to create a entry for every file.

**Comment by ReinerBforartists** [comment]
Hrmph. The github wiki does not allow images. So let's put it at the bforartists page.

**Comment by ReinerBforartists** [comment]
A pdf with the export settings is available in the developer docs section now.

https://www.bforartists.de/developer-docs/

https://www.bforartists.de/data/tuts/Libre_Office_PDF_export_values.pdf

Fixed. Closing.
