### ISSUE TITLE
Create a new Chapter : Compiling Bforartists

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#17]
### Case 
I know there is a tutorial document in the Bforartists program tracker - with no versioning, but thought it might be a good idea to have that particular tutorial as a particular chapter in the documentation - so we can version it and branch it to edit it with clearer revision checking - maybe use it as a base for "developing" Bforartists in an artist friendly way, to share the dev load and delegate to future artists. 

### Task
Create chapter: "18.1 Compiling Bforartists"

### Details
Will contain the same material as the Compilling tutorial + Index and some fixes to update it according to @Draises nooby compiling experience.

**Comment by ReinerBforartists** [comment]
Hi Draise,

Tough one. I personally am against it. The chapter how to compile Bforartists belongs imho into the developer documentations, where it already is. The user uses the software, and will not compile it. And the second point is, that's a tutorial. The reference manual is not made for tutorials, not even Blender/Bforartists tutorials. It documents the functionality. This can include some documentation how to use the tools. But not complete tutorials.

What makes it even more complicated is that we would need tutorials for all other platforms then too. We have currently one for Windows. Blender compiles also on Linux, Mac, Android, at a Raspbian ...

Hm, here we are again at the repository for our handful tutorials. Which i think is not necessary yet. We have still just a handful ...

**Comment by Draise14** [comment]
Ah. yeah. Good point. Thanks for the documentation clarification. Also, yes, you'd need one for each platform - though I have no idea who would use BFA on Android, lol

I wish there was a place to dump tutorials/walk-throughs. I would feel more comfortable making them and pushing them to publicity if there was a place.

**Comment by Draise14** [comment]
I see. 

The website could have all the hyperlinks and UI to navigate them, as they do - in the CMS articles (which are editable). The file editing and file storage for download would be on Github. So a tutorial file can be downloaded and viewed from navigation on the website, but stored on Github? No? 

Where are they currently stored right now? How is that workflow? 

Do you have an *.odt of a PDF tutorial, then you export the PDF and upload to the server, hyperlink the file in the Wiki and there it's downloaded? 

If the filestructure of Github is the same as the server file structure , a quick "Filesync" (with wildcards filtering the editable files when they sync) to copy over the Github files to the server to then use the website hyperlinks could be an easy job to have the PDF's still locked in their server structure and be updateable pretty much automatically from the Github file structure. Adding new links to the server data would be easy for anyone who creates in the repository, as when a branch get's pulled, the merged PDF and *ODT files will have the same server structure as the Github structure - minus the editable files. 

So technically, it all could be in on one place, the server wiki and download links is just a hyperlinked reflection of the repository.

**Comment by ReinerBforartists** [comment]
A github repository syncing with my webspace? That's not how it works, unfortunately ^^

As told, tutorials is normally nothing where you collaborate. You make me with the repository for tutorials  more work than before. That's why i struggle so much to make it even a repository. But in the end, one place to collect them is as good as the other.

**Comment by Draise14** [comment]
Yeah I guess.. 

I have no idea what your internal data workflow is with the tutorials and their documentations/files and the website, or the PDF files. Thus my suggestions probably don't sound great. The one above was assumed you were using FTP from local files to your server. 
 
I am wondering if having a subfolder in the documentation/Bforartists main area would make more sense than making yet another tracker and repository - by no means was I trying to make more work for you. All I know is just some organization and opensourcing things can make less work ultimately - just trying to find a way to fit in better than message attachments in a tracker thread with no versioning and ability to sync master sources.

**Comment by ReinerBforartists** [comment]
The new repository for all other files makes more sense because the manual is one closed chapter. I don't want to have other things in this repository.
