### ISSUE TITLE
Eliminate the redundant phrase "here you can..." phrase

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Manual#177]
In the manual, many paragraphs start with "Here yo can...". 
The "yo" (instead of "you") at so many places is jarring for the reader.

In the first place, the entire expression is avoidable: Instead of saying "Here you can adjust the brush strength.", just say "Adjusts the brush strength". 

(Rather than what you can do with the control, just say what function it delivers.)

**Comment by ReinerBforartists** [comment]
Excellent catch.

**Comment by ReinerBforartists** [comment]
Fixed in master
