### ISSUE TITLE
The structure of the bookmarks needs change

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Manual#178]
The bookmarks show the entire breadcrumb path from top. As a result, most bookmarks have grown too long, and they take up 40% of the screen width.
Further, there is no hierarchical tree: All bookmarks seem to be at root level.

For example,
7.1.10 Editors - 3D View - Header - Mesh - Edit Mode - Vertex Menu
7.1.25 Editors - 3D View - Header - Curve & Surface - Edit mode - Control points menu
7.1.34 Editors - 3D View - Header - Grease Pencil - Weight Paint Mode - Weights Menu

Both factors are extremely irritating because the bookmarks fail to guide us in navigating within the book. The hyphenated words do not provide a clue about how to reach that particular object.

**Comment by ReinerBforartists** [comment]
Yes it does.
You need to know though that there are modes in some editors. And that some menus just appears when you are in this mode. This is explained in the chapter 7.1.1 Header tools and options.

We could of course add the info about the modes in the preface of each chapter. That would be a solution to the dilemma.

**Comment by raindropsfromsky** [comment]
Well, that's my point: The manual must not require prior knowledge of the software.

Secondly, if there is a related text elsewhere, there should be a hyperlink to that section (or at least refer by section number).

**Comment by ReinerBforartists** [comment]
And my point is that our manual is a reference manual about the tools, and not a CG wiki. I know where you come from, i know your intentions. But we simply cannot deliver what you ask for here.

I am not happy with links to other chapters. This is one of the things that i will not accept. When you need further information, then deliver where it is needed. If possible. When this is a whole chapter, then it would blow up the manual. But most things can be cut down to a few sentences.

**Comment by ReinerBforartists** [comment]
Won't fix this. We will not change the structure at the bookmarks.
