### ISSUE TITLE
Bookmarks are set at a tiny zoom factor

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Manual#179]
When we click on any bookmark, the page opens at 81.73%.
I wonder why such an odd zoom factor is chosen!

Every time I click on a bookmark, I have to zoom in again to be able to read the page. This is irritating.

Besides, considering the fonts used, it would be best to open the manual at a zoom factor of >125%.

**Comment by ReinerBforartists** [comment]
Dunno if we have any influence at this zoom factor at all. But is worth an investigation.

**Comment by raindropsfromsky** [comment]
It is very much possible. When you export the file from LibreOffice as pdf, just use these settings in this dialog:
![image](https://user-images.githubusercontent.com/9047168/80304282-7db33580-87d2-11ea-928e-dabbed5dd83b.png)

**Comment by ReinerBforartists** [comment]
I have :)

Not as easy as this it seems ...

![initialview](https://user-images.githubusercontent.com/13919702/80304847-0d4bea80-87b9-11ea-8505-be021c5b332d.jpg)

**Comment by raindropsfromsky** [comment]
Hmmm

**Comment by ReinerBforartists** [comment]
Hm, maybe it's because i use a bulk converter tool. But it should use the export settings. This tool makes my life much easier though. It's not funny to export 200 files by hand ^^

**Comment by raindropsfromsky** [comment]
But once you finish editing a file, you export it as pdf.
That workflow allows you to produce one-pdf-at-a-time!

**Comment by raindropsfromsky** [comment]
BTW what is the bulk export tool?
I may be able to tinker with it and find a way...

**Comment by ReinerBforartists** [comment]
It is this one here: https://sourceforge.net/projects/bulkconvertulo/

Maybe you find a better one :)

**Comment by ReinerBforartists** [comment]
I convert the files meanwhile under Linux on the command line. It *should* now arrive with the correct settings.

Either way, there is nothing really to fix for us here. So closing this task.
