### ISSUE TITLE
For any chapter, first describe how to reach that point, starting from the home screen

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Manual#180]
Controls are mentioned without location reference
When we look at a video, we are looking at the entire GUI in a particular mode.
The video always explains how to arrive at that particular mode, starting from the default flash screen.

Then it takes us to a specific part of a screen, and starts explaining a cluster of controls.

This smooth continuity is not available when we read a manual.
First of all, we do not read a manual from start. Instead, we open it at a random page by clicking at a bookmark.
So only that one bookmark must set the whole context.

Unfortunately, our bookmarks fail to achieve that same effect.

For example, take the bookmark
7.1.10 Editors - 3D View - Header - Mesh - Edit Mode - Vertex Menu

Here, I have to imagine the following visuals, as if I am intimately aware of Blender, and describe all its modes with closed eyes.

Anyhow, I have started b4a, which shows me the default screen; and I have opened this chapter.
I cannot see the menu that is shown in the chapter.

![image](https://user-images.githubusercontent.com/9047168/80285298-7a239e00-8741-11ea-96db-7c6970eda8ae.png)

I am lost. I do not have a clue how to make that menu appear!
This is like searching for a missing person in a  foreign land with just a photo!
What are my chances of coming face to face with that person?? Almost nil!

The breadcrumb structure of the bookmark is my only clue, so I try to follow it.
So I pay close attention to it, and try to make sense out of it. 

1. The 3D editor view editor. What is it? I never came across any general description that described overview of all editors, and the 3D Editor in particular.
    There is no hyperlink to tell me what to read before coming to this chapter.
2. Header  <-- I wonder what a header is. No idea. No visual clue.
3. Mesh <---- I don't know what mesh is. Is it a menu item??
4. Edit mode <---- I do not know what the Edit mode is when I am already in a menu called "mesh".
    Even as Blender user, I know that it is the other way round: When we switch between object and edit modes, all menus change.
    In other words, I have to select the mode first, and then look at its menu structure.
    Thus, I expect the mode before the menu in the breadcrumb structure 
5. Vertex menu <--- At this point, I am completely lost as to where to look in the screen, or what to do.

In software testing (and also in highschool experiments), the procedure tells us how to configure the test setup before conducting the main experiment. The configuration procedure is not counted as part of the experiment. It is just to make sure that the set up is configured properly, and all prerequisite conditions are met.

A manual is also just like that: It needs to tell the reader how to navigate to the screen and modes, that are being described in the present chapter. It must show multiple screenshots to describe this step-by-step process.

And that is missing in this manual. It's a critical lacuna!

**Comment by ReinerBforartists** [comment]
From what i understand, you explain the same dilemma like in this issue here: https://github.com/Bforartists/Manual/issues/178

We cannot explain the whole CG knowledge in the manual. This is the reference manual for our software. We describe the tools in Bforartists, we are not a CG Wiki. And some things builds on top of each other. The different object types, like a mesh, is explained in the add menu chapter. So when you don't know what a mesh object is then you are indeed in trouble.

Both is of course a dilemma. But i haven't found a good solution to this yet.

**Comment by ReinerBforartists** [comment]
As a side note. We have yet to write the manual chapter of how to use the manual ^^

**Comment by raindropsfromsky** [comment]
First, the #178 is a different problem. There, I referred to the excessive length of the bookmarks, and lack of nesting (hierrachical tree).

Here, I object to lack of meaning in the bookmark (how it fails to help me navigate).
***********
B4a has only one manual. So it should be sufficient for all users; including newbies.

We cannot ask people to read the Blender manual first and then read the B4a manual.

Therefore it should explain how B4a works in the beginning. This should include an overview of modeling process (typical workflow), and different modes of modeling (object, edit, sculpt), animation, rigging, nodes, physics, Mantaflow and video editing.

Without understanding such overview, the user will get lost in details.

It should also describe how the specially designed controls work. (e.g. click inside a field and drag left/right to change value.)

To a new user, the individual chapters make sense only after that.

The current format of manual is suitable to only experienced Blender user who has changed over to B4a. He remembers how Blender works, and he can easily use Blender documentation when needed.

**Comment by raindropsfromsky** [comment]
> We have yet to write the manual chapter of how to use the manual

This is precisely the issue: That chapter is supposed to give the user a "mile-high" view of the software, and also how the unique controls behave, and how to use them. (e.g. nodes).

**Comment by ReinerBforartists** [comment]
We will see :)

We have 100000 more points to go. I am still at point 1, filling the manual with all the needed content at all ...

**Comment by ReinerBforartists** [comment]
We have now a chapter that explains the useage. And it is now at position 1.1, right at the top of the manual. We have also a introduction chapter to each editor where the areas and modes are explained. It would be total overkill to put this information into every chapter too. And this means this thread here has fulfilled its purpose. Needed changes was made. Closing.

Related: https://github.com/Bforartists/Manual/issues/184
