### ISSUE TITLE
Develop Docs - Icon Tutorial corrupt/missing

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#181]
This tutorial is broken/missing. 

[https://www.bforartists.de/data/tuts/Icontutorial.pdf](https://www.bforartists.de/data/tuts/Icontutorial.pdf)

**Comment by ReinerBforartists** [comment]
Ouch ^^

**Comment by ReinerBforartists** [comment]
Aand fixed.

Thanks buddie :)
