### ISSUE TITLE
Update the manual to Bforartists 2 version 2.5.0

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Manual#197]
New version, new manual content that needs to be added ...

**Comment by ReinerBforartists** [comment]
Fixed

**Comment by ReinerBforartists** [comment]
The release is delayed. And so we have more content to add.

**Comment by ReinerBforartists** [comment]
One little UI change with the current merge. Task stays open since there is still no Blender 2.90 in sight.

**Comment by ReinerBforartists** [comment]
Last missing bit.

Fixed in master

**Comment by Draise14** [comment]
This is a big day! You did it.

**Comment by ReinerBforartists** [comment]
Yeah, this was a monster task. I am really glad it is finished :)
