### ISSUE TITLE
Typo - Interface> Value Editing> Units

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#209]
# Issue
![image](https://user-images.githubusercontent.com/35357409/100376046-d2bf6000-2fdc-11eb-855e-2276c5c6639e.png)

# Task
Fix the typo
Also missing something before "Means" ("**This** means"?)

**Comment by ReinerBforartists** [comment]
Yo!

**Comment by ReinerBforartists** [comment]
Fixed. Will arrive with the next commit to Update Manual to BFA 2.5.2 / 2.6.0 #205
