### ISSUE TITLE
Revert the changes at the data properties

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Manual#218]
Blender devs have changed the data properties. I have then updated the manual. Now they have reverted the changes. With an open end how and if even to repeat the procedure.

We need to revert the changes at the manual. Next official version will for sure not have them.

![dataproperties](https://user-images.githubusercontent.com/13919702/104564367-1df40780-564b-11eb-8ddb-d450ea005d6d.jpg)

**Comment by ReinerBforartists** [comment]
Ah the fun. The chapters in question does not have a separate commit. It went into the weekly update -.-

**Comment by Draise14** [comment]
Oh my.. looks like there was a lot of backlash with the "update" and now they have backpedaled it.

**Comment by ReinerBforartists** [comment]
Indeed :)
Let's hope that the same thing doesn't happen to the asset browser too. There was a statement that they think to make it a developer feature again.

**Comment by ReinerBforartists** [comment]
In hope to have catched them all - fixed in master
