### ISSUE TITLE
The manual does not draw the reader's attention to special sections like "Glossary"

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Manual#224]
Every manual has some special chapters, such as-
1. Terms and concepts
2. Glossary
3. Explanation about the structure of the manual
4. Notations used by the manual
5. How to read the chapters (e.g. alternative sequences of reading the chapters; whether newbies and seasoned users can benefit by using different sequences of chapters; which chapters are more important, and which are trivial)

Such special sections should be mentioned up-front, so that the user is mindful of the special help he can get.

The manual does mention some of this on p1, but not all.
The reader's attention should have been drawn to Glossary.

**Desired:** 
Please add these remaining details to p.1

BTW even though you may say "chapter 34", the user cannot use TOC or bookmarks panel to select it. (reason: Bug #222)
Only after you close that bug can the reader get the full benefit.

**Comment by ReinerBforartists** [comment]
Thanks for the idea. The glossary is an appendix chapter. It is imho at exact the right position in the manual.

To change this would require the rewrite of 400 chapter names. A job for several days. And adding a hint to the appendix upfront is imho wasted text. 

Closing. Thanks for the input.
