### ISSUE TITLE
The manual must include the tip about how b4a acts different from Blender (and how to revert to default behavior)

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Manual#226]
One major selling point of B4a is a lots of duplicate menus are removed, and many menus are added. Plus a lot of toolbars and buttons are added. 

But this actually weakens the basic selling point of Blender, which promises break-neck speed because the user is encouraged to work with both hands: one hand on keyboard and the other hand on mouse.

In b4a, most of the operations become mouse-based. So a question arises: Does this interrupt the user's hand-movement?
(In Blender, his nouse-hand deals with objects/geometry; and his keyboard hand deals with command-selection. (Of course, when he has to deal with the **Properties** panel, he has to use his mouse.)

But in b4a, many of his commands also shift to "mouse-only" mode. Thus his mouse is engaged much more in commands/properties and less in object-manipulation.

If we want seasoned users of Blender to break away to B4a, this concern should be addressed with some nice explanation and case studies (preferably a YouTube playlist of 1-2 minutes video each).

Also, the manual must address how the B4a GUI and operation differs from Blender, so all users who are familiar with Blender can focus on only this delta. 

For example, 
1. Which are the additional buttons in each particular screen, and what do they do? 
2. How are different toolbars positioned on the screen (how is that segregation and positioning significant)?

Further, if they think that the Blender behavior is better, they should be allowed to switch back to the Blender default (not all at once, but function-by-function basis). This method should also be explained in the manual. For example, after explaining a 3D editor function, also include the settings that allow reversal to the Blender's default way. In general, the user should expect a note at the end that explains how to revert to the Blender setting.

That said, people will not want to revert too much (otherwise they would not have to come to bfloartists anyway!)

**Comment by ReinerBforartists** [comment]
Thanks for your idea Narayan. Burt we are Bforartists. We will not explain how Blender works. 

Closing.
