### ISSUE TITLE
Add header to every chapter

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Manual#230]
Split from here: Suggestion: The manual looks flat: Add depth to it! #225

Current situation is that a chapter starts directly with a table of content.

Let's add a colored header above the table of content. Consensus was to use the first header with the little icon in front.

![image](https://user-images.githubusercontent.com/13919702/107799674-04370480-6d5e-11eb-92ef-22cfe8432b0b.png)

![image](https://user-images.githubusercontent.com/13919702/107799689-09944f00-6d5e-11eb-987b-03a7d2bad72a.png)

**Comment by ReinerBforartists** [comment]
The odt file with the winner header

[headerexperiments.zip](https://github.com/Bforartists/Manual/files/5973381/headerexperiments.zip)

**Comment by ReinerBforartists** [comment]
This one happens step by step. One piece at time. Starting with adding them to the updated chapters after a merge.

**Comment by raindropsfromsky** [comment]
Suggestion: Do not take a short heading to see how it looks. Take the
longest and see how THAT looks.
Given that you are using the entire breadcrumbs structure to compose the
heading, it will be like a sentence!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ReinerBforartists** [comment]
Thanks for the suggestion. Already tested. It is sometimes two lines. But i think we can live with that :)

**Comment by ReinerBforartists** [comment]
Finally fixed in master
