### ISSUE TITLE
Change the header of the Bforartists manual from Bforartists 2 to Bforartists 3

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Manual#262]
Overlooked ...

![bfa2](https://user-images.githubusercontent.com/13919702/162565154-eb03a1e3-ff38-4e47-b643-ced62547a1f1.jpg)

**Comment by Draise14** [comment]
Ah, overlooked this. Will go through when I do it routinely

**Comment by ReinerBforartists** [comment]
I also forget about this regularly. Well, maybe with version 4 we have all chapters marked as for version 3 :D

**Comment by Draise14** [comment]
Keep forgetting this, but updated one chapter with this.

**Comment by ReinerBforartists** [comment]
The best thing to do would to move the manual to its own repo, and start from scratch i guess. Then we could change all headers, and wouldn't blow up the repo by that.

Maybe with the next manual then, with Bforartists 4 :)

**Comment by ReinerBforartists** [comment]
I'll tackle this one now. I think we came as close as possible. But the rest that gets touched once a year needs an update at one point too.

**Comment by ReinerBforartists** [comment]
This was my least favourite job since a long time. But now it is finally fixed :)
