### ISSUE TITLE
Geometry Nodes Editor - chapter 12.1.1 - update the description for Named Attributes checkbox

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Manual#263]
Currently the checkbox is not properly documented. And it is simply not to find out what the checkbox does, or better said how to access the shown overlay. The Blender manual misses the description yet. So let's wait a bit until the manual is updated.

Blender task: https://developer.blender.org/D14618

![named](https://user-images.githubusercontent.com/13919702/163722604-7b7add54-1b04-4b25-aefb-14f92d4c5a4f.jpg)

**Comment by ReinerBforartists** [comment]
Hm. the manual is updated. Still no idea how this is meant to work.

**Comment by Draise14** [comment]
Found the relevant task which has info:
https://developer.blender.org/D14618

Updated the documentation
