### ISSUE TITLE
Geometry Nodes - Show Timing Overlay needs update

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#264]
The order changed, so check if there is a capture then update

![image](https://user-images.githubusercontent.com/35357409/167238176-d7abc4e6-8a47-4d17-9001-52129161254f.png)

**Comment by ReinerBforartists** [comment]
Image?

I know i am nagging. But you will thank me in the long run for this. It saves so much unnecessary conversation ...

**Comment by Draise14** [comment]
Sure. I have to make a new build first, which is still happening, so I'll update the task when I have it going. I like screen caps and capture often, so will include those later and hopefully soon.

**Comment by ReinerBforartists** [comment]
Pic or it didn't happen!

**Comment by Draise14** [comment]
Image added

**Comment by ReinerBforartists** [comment]
Nothing has changed here. Manual is already up to date.

Closing. Nothing to do.
