### ISSUE TITLE
Developer Documentation - Icon Tutorial needs Environment Variable update

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#267]
Following the make icon tutorial from the developer docs on the website has proven to be difficult due to an issue that pops up on Windows without the environment variables. Mentioning how to add them and why to add them is a must to run the tutorial without any problems. 

**Reference**
[https://github.com/Bforartists/Bforartists/issues/765](https://github.com/Bforartists/Bforartists/issues/765)

**Comment by ReinerBforartists** [comment]
Well, it shouldn't be an issue since normally Inkscape should add this variable automatically -.-

I'll add a note to the tutorial :)

**Comment by ReinerBforartists** [comment]
Fixed. The commit went into the File repository. 

https://github.com/Bforartists/files/commit/71a0ce73d6a7834d190563d134439264a257fb00

**Comment by Draise14** [comment]
Yeah... inkscape and blender did not add these variables when I installed - so had to do them manually. Thanks for mentioning.

**Comment by ReinerBforartists** [comment]
Mh, you need to use the msi installer for Blender. But the installer should add the variable then. Hm, maybe my memories are kidding me here though.
