### ISSUE TITLE
Node Editors - New Seperate/Combine Color nodes 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#268]
![image](https://user-images.githubusercontent.com/35357409/167507705-c0e244ff-3eb4-4813-af88-56e199f2041f.png)
![image](https://user-images.githubusercontent.com/35357409/167507777-a39559ab-f2f3-484b-b4b5-ee4a9313161a.png)

New nodes, Combine and Separate Color
Located both in compositor, shading and textures nodes

These need to be documented in the relevant editors. 

Relevant Blender task:
https://developer.blender.org/D14034

Relevant Task:
https://github.com/Bforartists/Bforartists/issues/2998

**Comment by ReinerBforartists** [comment]
Related https://github.com/Bforartists/Bforartists/issues/2998

**Comment by Draise14** [comment]
@ReinerBforartists is it ok if I take this task in my soon to be done commit? I'm on a roll now.

**Comment by ReinerBforartists** [comment]
Sure

**Comment by Draise14** [comment]
Will have lunch, then will commit this one.

**Comment by ReinerBforartists** [comment]
Oki :)
