### ISSUE TITLE
Properties Editor - Add Color Attribute dialogue needs updating

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#269]
![image](https://user-images.githubusercontent.com/35357409/167507955-4f1238c3-db58-4110-94a8-d0c7a89e23a7.png)

The Add Color Attributes (that replaced Vertex Color Add operator) has a new dialogue, should be updated. 

Check if the vertex colour entries need to change to Color Attributes also. 

Relevant Blender task:
https://developer.blender.org/D14785

**Comment by Draise14** [comment]
![soffice bin_WXYyI9Rlis](https://user-images.githubusercontent.com/35357409/168348125-ebb0da45-3d69-445a-88ff-76f67999b601.png)

Done locally, about to commit.

**Comment by ReinerBforartists** [comment]
No need to document the new chapters. This just costs time.
