### ISSUE TITLE
Image Editor - Document Gizmo Toggle from header

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#270]
![image](https://user-images.githubusercontent.com/35357409/167508847-f77cbf6f-6f37-46f1-b46d-38e4b1cbcf7b.png)

New gizmo toggle from header. Make sure this is documented:

Relevant Blender  Task:
https://developer.blender.org/rBed0964c97623a7542dab900ebda900f3953db4bb

**Comment by ReinerBforartists** [comment]
May i remind to not make a single task for every new manual entry? This will blow up the manual repository. And you add lots of extra work to yourself.

Extra tracker entries in the manual makes just sense when you have a bigger operation. Like writing a new chapter.

We have this task here for the merge issues: https://github.com/Bforartists/Manual/issues/260

The way i do this is to go through the log, add the issues that needs a fix at the code end, and fix all the things at the manual at my way through the log. Then i go through the code tracker, fix the code issues too, and fix these issues and changes also at the manual. And then i do ONE commit to the merge issue. Including all the changes that just affects this one merge.

Same goes for fixing further issues. I commit the changes at the manual once a week. Into the same merge issue.

I commit them as for example 

Update the manual to Bforartists version 3.2.0 https://github.com/Bforartists/Manual/issues/260 - **merge 24.04.2022**

And

Update the manual to Bforartists version 3.2.0 https://github.com/Bforartists/Manual/issues/260 - **development 29.04.2022**


This keeps the documentation overhead and the manual repository as small as possible.

**Comment by Draise14** [comment]
I have 2 clients (sometimes a team to manage), 1 student, and this new job. I cannot work this way that you suggest - I need to be granular to do it with tiny daily work. Maybe I can make one task with a checklist? 

How do I do checklists?

**Comment by Draise14** [comment]
Ok. Found a way. I'll consolidate the tasks then do checklists task for the weekly merge later today.

I really have to note of every single thing I have to do or else I won't do it. I have hundreds of other things to think about so I can not physically fill my head with Bforartists or a client 100% of the day. So I gotta take note somewhere to get to it after tasks and priorities. 

This will be the case till my financial model can survive without clients unfortunately.

But a checklist here might help with a single task for a single commit. 

```

### Solar System Exploration, 1950s – 1960s

- [ ] Mercury
- [x] Venus
- [x] Earth (Orbit/Moon)
- [x] Mars
- [ ] Jupiter
- [ ] Saturn
- [ ] Uranus
```

**Comment by ReinerBforartists** [comment]
I understand what you mean, but my checklist was always the list of commits. I also interrupted regularly.

 Work through it one by one. When you find a commit that needs manual update, then fix it, and on with the next issue. And when you need a break, write down which commit was the last that you progressed. And then go on from there when you come back :)

As told, you waste lots of time with this kind of documentation.

**Comment by Draise14** [comment]
The blender list of commits or the Bforartists one? 

I am noticing some of the new blender features don't become Bforartists tasks so I can't use the Bforartists tracker. I'd have to track those changes and my own progress elsewhere. If it is not on Github, it would have to be in a Kanban or excel elsewhere. I also can't do a whole chain of tasks list one after another as I only have time for parts of a task in one sitting, so I do it factory style, many small steps but the same steps for batches of work at a time. I tried to do it one feature by one as I do a task but it really is not efficient for me. Last week got behind trying to. 

I am reading that you wantnme to ping pong individual task types to get the job done (check, code, documentation, check, code, documentation, etc) , but my brian energy to switch task types is too costly for me. 

Right now I'm doing this: log to-dos, code, then documentation in blocks.

**Comment by Draise14** [comment]
I guess I could work the project kanban here on github to be tranparent also. What worked for you might not work for me in all cases. But ill try find a way to stick to one commit/task per week in the documentation while not getting lost with myself.

**Comment by ReinerBforartists** [comment]
Or to sum it up: you simply fix it immediately instead of writing down a tracker issue :)

**Comment by Draise14** [comment]
I have tried to think about this. Here is what I understand:

**Documentation Workflow:**
- Go through Blender commit list of the week (logs from tortoise help)
- Update documentation where relevant
- If a task is relevant for Bforartists in the GUI, Log and work code in Bforaritsts code tracker
- After commit of code and close/pull, update the documentation immediately, don't make a task.
- Store locally till final commit end of week to commit many in one for bandwidth of the repository

I noticed one issue, what if there are multiple people working on the documentation and same document?

**Comment by ReinerBforartists** [comment]
> I noticed one issue, what if there are multiple people working on the documentation and same document?

Don't ! 

This will also make trouble with your method. Two people cannot work at once at one document. ODT is just dealt as a whole by git. So when person A modifies the document 1, and person B also, then there can just be one version. And the commit that comes last wins ...

That's why i keep my hands away at the moment :)

**Comment by ReinerBforartists** [comment]
The problem here at the moment is that you block the Manual repository for a whole week. I have just blocked it for one or two days usually. And was the only one working at it anyways. So this was not a problem that needed a solution really.

We might need a better solution now. To need even more time with excessive documentation is not the solution to it though.
