### ISSUE TITLE
3D View - Curve Object - Edit - New operator mode to snap to surface

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#271]
![image](https://user-images.githubusercontent.com/35357409/167509406-d9383727-2444-48ae-bb5d-117d58b5a4b5.png)

There is a new operator mode "Deform" and "Nearest" when snapping to surface. So there is a new operator listed in the Curve header menu.

`snap_curves_to_surface`

Need documentation

Relevant task:
https://github.com/Bforartists/Bforartists/issues/3000

**Comment by Draise14** [comment]
Experimental Feature.

**Comment by ReinerBforartists** [comment]
Now it's in the trunk.

**Comment by ReinerBforartists** [comment]
This one is a double of https://github.com/Bforartists/Manual/issues/321
