### ISSUE TITLE
3D View - Object Mode - Convert To operator has new property: Merge UVs

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#272]
![image](https://user-images.githubusercontent.com/35357409/167509657-4fdf10cb-05da-4cc4-9b30-e847c8ba5ec4.png)

Convert To operator in Object mode has the ability to also merge UV's of the converted geometry. This should be documented.

**Comment by ReinerBforartists** [comment]
Mh, which tools are affected?

**Comment by ReinerBforartists** [comment]
Mh 2: the checkboxes needs to be aligned left ...

**Comment by ReinerBforartists** [comment]
Don't forget to update the single images for this last operator. I have aligned the checkboxes at the left now again.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/168311511-ef3b2742-115f-451d-bfea-d6b0c5e8a908.png)

Ready to commit from local.
