### ISSUE TITLE
Formatting problems in chapter 7.1.8

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Manual#287]
We have odd table of content formatting in chapter 7.1.8, various page breaks, and the header are indent without that i can find a cause for it. And we have a section here. We don't use sections.

It would be interesting to know what is shooting us down the formatting.

Draise, the last edit comes from you. What exact Libre Office version do you use? And what have you done here? ^^

Such things shouldn't happen with a vanilla version.

![section](https://user-images.githubusercontent.com/13919702/174981870-beb9a8f2-7e10-4bc4-8943-24050de5430b.jpg)
![odd](https://user-images.githubusercontent.com/13919702/174981893-f9366170-bba0-4667-baaf-5bb1cdf5562c.jpg)

**Comment by Draise14** [comment]
I would have no idea here. I am using the most recent version of Libre Office 7.3.3.2. 

I am not versed with this software so well, so there is a high chance I borked it. I wouldn't know how to fix it though. There must be something in the text that makes sections like a normal word document based on the formatting - I guess it's digging it up and fixing that.

**Comment by ReinerBforartists** [comment]
Hm, i still use 7.0 something. This could already explain the one or another thing. I'll have a look to update my version.

**Comment by ReinerBforartists** [comment]
One thing as a note, never use the developer version, but the most stable version. The developer version of Libre Office can contain some surprises ...

**Comment by Draise14** [comment]
Looks like 7.3.4 is the most stable. 

![firefox_hFZlXVRtNk](https://user-images.githubusercontent.com/35357409/175076878-7025abc1-9c5f-4e52-ac78-3485c97287c9.png)

**Comment by ReinerBforartists** [comment]
For technical enthusiasts. This is the developer version :D

**Comment by ReinerBforartists** [comment]
Indeed :D

**Comment by ReinerBforartists** [comment]
I'll grab this one and have a look what i can do here.
