### ISSUE TITLE
3D View - Make Parent (Keep Transform without Inverse) needs documentation

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#288]
![image](https://user-images.githubusercontent.com/35357409/175075115-8c476e03-2a6e-4f4f-a900-81abbc06c949.png)

Keep Transform without Inverse is an undocumented method to parent. Needs to be documented. 

**Related Task:**
https://github.com/Bforartists/Bforartists/issues/3071

**Comment by Draise14** [comment]
It's a "Last Operator" toggle that could be documented in the actual operator from the header. I would do it there, and then add a hint that there is a "shortcut" in the floating menu hotkey in the same operator in that part of the documentation.

**Comment by ReinerBforartists** [comment]
Okay :)

**Comment by Draise14** [comment]
Found the entry for the parent context menu, so added the info of this operator and updated icon to the document.
