### ISSUE TITLE
UV Editor - New "Select Similar" operator needs documentation

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#299]
![image](https://user-images.githubusercontent.com/35357409/176233248-fbddb2d3-c300-4a15-a731-4ea875d4da31.png)

New operator, new documentation needed

Relevant Task:
https://github.com/Bforartists/Bforartists/issues/3088

**Comment by ReinerBforartists** [comment]
Duplicate of Document new select similar pinned operator. #308
