### ISSUE TITLE
FCurve Editor - Slide Operators - Blend to Default Value needs documentation

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#300]
![image](https://user-images.githubusercontent.com/35357409/176233963-3fab5dfe-f417-49c1-ba3b-c3910f889290.png)

Needs to be documented

Relevant Task:
![image](https://user-images.githubusercontent.com/35357409/176233975-4163d3df-1031-46b1-94eb-0272671fe9cc.png)

**Comment by ReinerBforartists** [comment]
It already is documented. Closing.
