### ISSUE TITLE
Movie Clip Editor - New Spline Overlay settings needs to be documented

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#302]
![image](https://user-images.githubusercontent.com/35357409/176240844-4e22f334-88e6-4cea-98dc-9d2b776d273f.png)

New overlay settings for mask splines needs to be documented.

**Comment by ReinerBforartists** [comment]
There is no mask editor. But we have plenty of editors with masking functionality. Which editor is it?

**Comment by Draise14** [comment]
Ah. Gotta look that editor up. Misnamed it. Having lunch then will get to it.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/177655793-fb6fb331-ec5c-4038-b99e-ee97a0462ae6.png)

Here is how you can see it.
