### ISSUE TITLE
Spreadsheet - Filters - Color Attributes method needs to be documented

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#305]
![image](https://dev-files.blender.org/file/data/2jgmjzcdxjta4fckor7q/PHID-FILE-dsiqu743h3frj4stqvqc/Captura.png)

New filter mode for colors needs to be documented. 

Relevant blender task:
https://developer.blender.org/D15191

**Comment by ReinerBforartists** [comment]
Is this by chance an experimental feature again? :)
![experimentalornot](https://user-images.githubusercontent.com/13919702/177497667-5c7d6378-b53b-4f4e-a4ce-e860ad2e055d.jpg)

**Comment by Draise14** [comment]
Ah, you gotta establish it somewhere, like set the field with color attributes first
![image](https://user-images.githubusercontent.com/35357409/177655474-15066d98-d0a7-4acb-bb2f-68276450489a.png)

**Comment by Draise14** [comment]
Ok, found the entries, and added a quick little note
