### ISSUE TITLE
3D View - Hair Curve Object - Sculpt Mode and brushes needs documentation

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#317]
![bforartists_s9XOssc4pJ](https://user-images.githubusercontent.com/35357409/179270627-64f1d637-8dbd-4b87-a93e-2abed4d2ceb2.png)

There is a new curve object, and with the new curve object may need an entire chapter to the sculpt mode and their brushes. There are quite a few new brushes.

**Comment by ReinerBforartists** [comment]
Needs its own chapter. Not sure where to add it yet. But the particle edit mode has similar content, can be used as a starting point, and saves quite a bit of work.

7.2.7 Editors - 3D Viewport - Tool Shelf - Mesh - Particle Edit Mode.pdf

**Comment by Draise14** [comment]
Phew, that was a bunch of work.... but done. On local, will commit.
