### ISSUE TITLE
Property Editor - Scenes - New "Pin Scenes" Operator needs documentation

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#319]
![image](https://user-images.githubusercontent.com/35357409/179272552-86d76077-32d9-4fdf-bdab-df901fbdf302.png)

You can now pin scenes to the workspace, useful! Should be documented somewhere.

**Comment by ReinerBforartists** [comment]
Fixed

**Comment by ReinerBforartists** [comment]
Damn, wrong committed.
