### ISSUE TITLE
3D View - Hair Curve Object - Sculpt Mode - Select menu needs documentation

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#320]
![bforartists_AFMO8yRXYP](https://user-images.githubusercontent.com/35357409/179273025-f69aa136-e602-4fdd-a97f-b9cf2b105dc0.png)

Probably with the new chapter of the Sculpt Mode for the new Curve Objects.

**Pending Task:**
https://github.com/Bforartists/Bforartists/issues/3137

**Comment by ReinerBforartists** [comment]
Curve has still no sculpt mode. Experimental features should not be documented or touched until they are finished and officially landed in the trunk.

Postponing.

![nope](https://user-images.githubusercontent.com/13919702/179343979-1a849713-9d14-435f-aa74-71a649e4519c.jpg)

**Comment by Draise14** [comment]
Done locally, needs to be committed.
