### ISSUE TITLE
3D View - Hair Curve Object - Sculpt Mode - Curves menu needs documentation

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#321]
![bforartists_s9z6rN1DNa](https://user-images.githubusercontent.com/35357409/179273432-e5b26336-f272-4c63-aa95-e4383affce62.png)

Probably with the new chapter of the Sculpt Mode for the new Curve Objects.

**Pending Task:**
https://github.com/Bforartists/Bforartists/issues/3138

**Comment by ReinerBforartists** [comment]
Curve has still no sculpt mode. Experimental features should not be documented or touched until they are finished and officially  landed in the trunk. 

Postponing. 

![nope](https://user-images.githubusercontent.com/13919702/179343889-c32d297f-7f94-4128-8dab-2344ff6236f3.jpg)

**Comment by Draise14** [comment]
No longer experimental. It's in the hair curve object.

**Comment by ReinerBforartists** [comment]
Ah. Please update the task then ;)

**Comment by Draise14** [comment]
Should probably rename to "hair curve object". Yeah

**Comment by ReinerBforartists** [comment]
I am lost with the documentation of this new object. I can't even figure out what to sculpt. It is an empty :/

**Comment by ReinerBforartists** [comment]
This one is a new chapter. Let's investigate where to add it ...

**Comment by Draise14** [comment]
Made into a new chapter:
7.1.42 Editors - 3D Viewport - Header - Hair Curve - Sculpt mode - Curves menu

Done locally, pending commit
