### ISSUE TITLE
UV Editor - Select Similar - also works on islands.

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#328]
Should be documented.

**Comment by ReinerBforartists** [comment]
Select similar in what editor in what mode?

**Comment by ReinerBforartists** [comment]
Ah, UV Editor, Sync Selection off and with Islands as the select method. We miss icons here. So first let's add the icons.

![similarwithislands](https://user-images.githubusercontent.com/13919702/182531836-b4ab8bd1-8c29-4b12-8475-ea15337706d7.jpg)

**Comment by ReinerBforartists** [comment]
Fixed
