### ISSUE TITLE
Geometry Nodes - New node: Shortest Path

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#333]
![bforartists_UuSxa9XITx](https://user-images.githubusercontent.com/35357409/182713780-b87e38c3-59d6-4a90-8e89-03382e2db6e2.png)
New nodes, new documentation. 

**Relevant Task:**
https://github.com/Bforartists/Bforartists/issues/3170

**Comment by ReinerBforartists** [comment]
Mesh to Volume is also new ...

**Comment by Draise14** [comment]
That's weird. I already did that one.

**Comment by Draise14** [comment]
I think I already documented that one. Mesh to volume
https://github.com/Bforartists/Bforartists/issues/3081

**Comment by ReinerBforartists** [comment]
I am at it :)

**Comment by ReinerBforartists** [comment]
These nodes are crazy. I have no idea how this is meant to work. Rocket science is easier than Geometry nodes nowadays ...

**Comment by ReinerBforartists** [comment]
Either way. fixed. Please check if you find a way to improve the documentation for these nodes. I stumble completely in the dark here.

**Comment by ReinerBforartists** [comment]
Nobody checked. But nobody moaned. So let's close it.
