### ISSUE TITLE
3D View - Header - Mesh - Vertex Menu - Vertex Crease needs to be documented

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#334]
![image](https://user-images.githubusercontent.com/35357409/182714087-bab611ac-25ff-49c4-92a3-c088662f00d4.png)
The vertex crease operator is new, and should be documented. From what I know, it's not there yet. 

Pending an icon still. 

**Relevant Task:**
https://github.com/Bforartists/Bforartists/issues/3173

**Comment by ReinerBforartists** [comment]
Icon is at its way :)
