### ISSUE TITLE
Update Documentation 3.2.2 on Website

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#335]
Ok! So the documentation is now on Nextcloud in PDF format, ready to go to the website. Here are the noticeable differences for the links:
![Meld_GSxKli55bW](https://user-images.githubusercontent.com/35357409/184175656-6cf1e40a-21e3-4dad-9da0-d00a2a65e9b6.png)
![Meld_wkwSrOe8Zn](https://user-images.githubusercontent.com/35357409/184175659-83c79329-6231-485a-a739-d0a12be17541.png)

![Meld_5jdIa43f2G](https://user-images.githubusercontent.com/35357409/184175660-2b7c5c94-f722-4d91-8e2f-515ea09541ab.png)

And the obvious:
![Meld_zvoLAIZKjS](https://user-images.githubusercontent.com/35357409/184175657-7745c84a-fa12-478a-8b79-a3424b8dbefe.png)

Here is the link on Nextcloud:
https://cloud.bforartists.de/index.php/f/15445

**Comment by ReinerBforartists** [comment]
Done :)
