### ISSUE TITLE
Sculpt Mode - Sculpt Paint Brush - Gradient Mode needs documentation

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#337]
https://dev-files.blender.org/file/data/7knoeaw6nuthy5xynqdf/PHID-FILE-v4vzvb7zdo6effbcclpo/blender_IOtjkFtQV7.mp4

The Sculpt Paint brush in Sculpt mode now has a clor gradient color picker mode. This should be documented. 

Relevant task
https://developer.blender.org/D15502

**Comment by ReinerBforartists** [comment]
Fixed
