### ISSUE TITLE
3D View - Grease Pencil - Edit Mode - Stroke - Outline oprator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#343]
![bforartists_ZN8LWcqpYl](https://user-images.githubusercontent.com/35357409/188631529-873d0576-4984-4b81-b5cd-e73cc74f274b.png)

New outline operator needs documentation. 

Relevant task:
https://github.com/Bforartists/Bforartists/issues/3216

**Comment by ReinerBforartists** [comment]
Why do we have two entries here?

**Comment by ReinerBforartists** [comment]
Already documented with fixing the related task.
