### ISSUE TITLE
Geometry Nodes - Utilities - New Mix node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#344]
![image](https://user-images.githubusercontent.com/35357409/188632254-84caca47-fec1-48c8-8928-6283517c8ffd.png)

New Geometry Node, the mix node. This node has multiple modes. Needs to be documented. 

Relevant Task
https://github.com/Bforartists/Bforartists/issues/3217

**Comment by ReinerBforartists** [comment]
Closing as duplicate. It is the same node, reused in both editors.
