### ISSUE TITLE
Shader and node editor - New Mix node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#345]
![bforartists_2Py02DYBB9](https://user-images.githubusercontent.com/35357409/188632840-09536d34-3b8d-4316-b78b-9a31cc276e25.png)

New Shader Node, the Mix node. This node has multiple modes. Needs to be documented.

**Relevant Task**
https://github.com/Bforartists/Bforartists/issues/3218

**Comment by ReinerBforartists** [comment]
Float curve is also missing. in the documentation.

![floatcurve](https://user-images.githubusercontent.com/13919702/190865866-ad367cb4-55a3-474d-abd2-bef7fff20358.jpg)

**Comment by ReinerBforartists** [comment]
Related: Geometry Nodes - Utilities - New Mix node #344

**Comment by ReinerBforartists** [comment]
Fixed in master
