### ISSUE TITLE
Shader Nodes - Color - Mix RGB node exists but is deprecated

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#346]
![bforartists_NJ1QadqVRQ](https://user-images.githubusercontent.com/35357409/188635868-8df194ca-4ee5-4be5-98a9-b3d8d9e4d3db.png)

Probably should mention that in the documentation. 

Relevant Task:
https://github.com/Bforartists/Bforartists/issues/3219

**Comment by ReinerBforartists** [comment]
Remove the content from the manual. Or better said, move the information to where the new Mix nodes is now.

**Comment by ReinerBforartists** [comment]
Making it one task. And close this one as duplicate
