### ISSUE TITLE
 Mix RGB node deprecated 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#347]
![bforartists_NJ1QadqVRQ](https://user-images.githubusercontent.com/35357409/188637257-baaa70d7-38b4-4b06-9a8f-df5c1d239629.png)

Node is deprecated, but should be mentioned. It is still in the API and our GUI. 

**Relevant Task:**
https://github.com/Bforartists/Bforartists/issues/3220

**Comment by ReinerBforartists** [comment]
Deprecated content should be removed in case Blender removed it. We promised to deliver the same functionality ...

**Comment by ReinerBforartists** [comment]
The shot is from the material editor ...

**Comment by ReinerBforartists** [comment]
Fixed
