### ISSUE TITLE
Shader Nodes - Converter - Squeeze Value

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#348]
![bforartists_fgc9DCGOSz](https://user-images.githubusercontent.com/35357409/188640941-cc567f32-c42f-495f-8f6d-c4992476c0ba.png)

Needs documentation and verified it's all there. 

**Blender Documentation:**
https://docs.blender.org/manual/en/2.79/render/blender_render/materials/nodes/types/converter/sqeeze_value.html

**Comment by ReinerBforartists** [comment]
The documentation links to the Blender 2.79 manual. This node does not exist anymore.

Closing.
