### ISSUE TITLE
Geometry Nodes - New Face Set Boundaries node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#350]
![image](https://user-images.githubusercontent.com/35357409/192634342-036d5507-1fb1-411f-a92b-3f1bc54f2100.png)

New node, new iconography, add to Add shelf and documentation. 

Relevant Task: 
https://github.com/Bforartists/Bforartists/issues/3252

**Comment by ReinerBforartists** [comment]
Fixed
