### ISSUE TITLE
Geometry Nodes - New Distribute Points in Volume node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#351]
![bforartists_4joSh65KQz](https://user-images.githubusercontent.com/35357409/192634954-51940d19-4454-4867-829f-bd7a2a91a5c2.png)

New Distribute Points in Volume node means new iconography, new entry to the add shelf, and documentation.

**Relevant pending task:**
https://github.com/Bforartists/Bforartists/issues/3253

**Comment by ReinerBforartists** [comment]
Fixed
