### ISSUE TITLE
Geometry Nodes - Asset Library node groups now can be searchable in the GN editor - needs documentation

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#352]
![image](https://user-images.githubusercontent.com/35357409/192636826-cf8ae3a9-1532-40d1-98d7-c8dcb9c8b64e.png)

Using the F3 search menu, you can now search for node groups for Geometry Nodes from registered Asset Libraries for the Asset Browser. This probably should be documented.

**Comment by ReinerBforartists** [comment]
I have no idea what is meant here with editor. We have over 20 editors ...

**Comment by Draise14** [comment]
Ah. I'm the geometry nodes editor. 
Still not sure about the other two node editors.

**Comment by ReinerBforartists** [comment]
I let you investigate :)

**Comment by Draise14** [comment]
Working
