### ISSUE TITLE
NLA - New Redo Panel is available

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#354]
![image](https://user-images.githubusercontent.com/35357409/192639168-4e8a2936-31ea-42d2-8684-48746c20d572.png)

New Redo panel for the NLA Editor

**Comment by ReinerBforartists** [comment]
That's a adjust last operation transform panel when you drag keyframes.

**Comment by ReinerBforartists** [comment]
Chapter 20.1.6 NLA Editor -Edit Menu in the Transform section.  This chapter is messed up. I first need to fix it :/

Draise, i am not sure if this is from one of your first edits that slipped through. In case it is not, could you please make sure that you use the latest Libre Office version, and not your other favourite editor?


![shotdown](https://user-images.githubusercontent.com/13919702/194745839-44b8597e-8bf1-4a83-85af-75fc78b4fb1e.jpg)

**Comment by ReinerBforartists** [comment]
Chapter 16.1.7 is also shot down. Formatting wrong, section etc. 

I cannot continue until the manual is in a working state again.

**Comment by ReinerBforartists** [comment]
Fixed in master.
