### ISSUE TITLE
Geometry Nodes - New Self Object Node 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#358]
![bforartists_YV9yMz1f5J](https://user-images.githubusercontent.com/35357409/197363105-f5089b82-0c23-4aa5-9795-9629fd7b6aa2.png)

New node means new documentation, under the **input** category. 

Releted task:
https://github.com/Bforartists/Bforartists/issues/3277

**Comment by ReinerBforartists** [comment]
Starting with documentation. The images with the missing icons can be added afterwards when the corresponding tasks are tackled.

**Comment by ReinerBforartists** [comment]
Added text. Misses the screenshots with the new icon.

**Comment by ReinerBforartists** [comment]
Fixed
