### ISSUE TITLE
Geometry Nodes - remove "transfer attribute" node for to 2 new node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#359]
![bforartists_QqinioBWAU](https://user-images.githubusercontent.com/35357409/197363421-69f80c83-7b2e-4f9c-9ad8-3cac7c9467e3.png)

Old node is now two new nodes. Requires iconography, documentation, and update to the toolshelf. This also needs removing an old attribute node.

Location: Geometry Nodes>Add>Geometry

**Nodes:**
- Sample Index
- Sample Nearest

Former node to be removed: Add>Attribute>Transfer Attribute

![bforartists_6XNwz0hPSV](https://user-images.githubusercontent.com/35357409/197363426-53e11c3f-816d-454e-9dd2-34b6c73835cb.png)

Relevant Task:
https://github.com/Bforartists/Bforartists/issues/3278

**Comment by ReinerBforartists** [comment]
Added text. Needs new screenshots once the icons are implemented.

**Comment by ReinerBforartists** [comment]
Fixed
