### ISSUE TITLE
Geometry Nodes - New Sample Nearest Surface node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#360]
![bforartists_2vOdCvWRbl](https://user-images.githubusercontent.com/35357409/197363563-b232b33a-9c7c-4a80-a6b9-0c59dccbd947.png)

New node, new documentation

Location: Geometry Nodes>Add>Mesh

Relevant Task:
github.com/Bforartists/Bforartists/issues/3279

**Comment by ReinerBforartists** [comment]
There is also a new sample new uv node Will progress both.

**Comment by ReinerBforartists** [comment]
Added text. Needs update of the shots when the icons are done.

**Comment by ReinerBforartists** [comment]
Fixed
