### ISSUE TITLE
Geometry Nodes - New Set Curve Normals node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#361]
![bforartists_Oz9f3NWuTE](https://user-images.githubusercontent.com/35357409/197363790-4ac1bb3f-556f-456b-9bf0-f5b4df0635e6.png)

New node, new documentation

Location
GeometryNodes>Add>Curve

Relevant Task
https://github.com/Bforartists/Bforartists/issues/3280

**Comment by ReinerBforartists** [comment]
Fixed
