### ISSUE TITLE
Geometry Nodes - New Curve Toplogy category and 3 nodes

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#362]
![bforartists_EMU2QC2bno](https://user-images.githubusercontent.com/35357409/197363896-d389423e-4f01-4ea7-becf-d1de5f60722a.png)
Documentation for this cateogry and 3 nodes. 

**New Nodes:**
- Offset Point in Curves
- Curve of Point
- Points of Curve

Relevant Task
https://github.com/Bforartists/Bforartists/issues/3281

Relevant Blender Task
https://developer.blender.org/D16029

**Comment by ReinerBforartists** [comment]
Related: https://www.wallstreet-online.de/nachricht/16127090-bitcoin-30-000-ziel-2023

I will try to tackle these two at once. I don't want to rename the chapters twice ...

**Comment by ReinerBforartists** [comment]
Added text.

**Comment by ReinerBforartists** [comment]
Fixed
