### ISSUE TITLE
Geometry Nodes - New Sample UV Surface node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#363]
![PowerToys_akm9bVtkre](https://user-images.githubusercontent.com/35357409/197363953-f08be3bf-2733-4546-a614-4a2887414030.png)

New node, new documentation, iconography, and feature in the add shelf.

**Location:**
Geometry Nodes>Add>>Mesh

Relevant Task:
https://github.com/Bforartists/Bforartists/issues/3282

**Comment by ReinerBforartists** [comment]
Text already added in this task. Geometry Nodes - New Sample Nearest Surface node #360

**Comment by ReinerBforartists** [comment]
Fixed
