### ISSUE TITLE
User Preferences - Input - Document Touchpad  + NDOF panel

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#365]
![image](https://user-images.githubusercontent.com/35357409/197364294-cb180811-b314-4b0a-b735-202fcda320a3.png)

If this doesn't exist already, document it. 

Pending task for screen capture:
https://github.com/Bforartists/Bforartists/issues/3284

**Comment by ReinerBforartists** [comment]
Extended the task
![NDOF](https://user-images.githubusercontent.com/13919702/199185008-13a89819-a6eb-4226-91b5-9ab96c9141b4.JPG)

**Comment by ReinerBforartists** [comment]
Added text. Needs updated screenshots.

**Comment by ReinerBforartists** [comment]
Fixed
