### ISSUE TITLE
Batch Rename - Add entry and documentation for Action Clips

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#366]
![image](https://user-images.githubusercontent.com/35357409/197364531-9adfeb4b-ea16-406d-9c5d-bcd4e2ff7f92.png)

New method to batch rename, now action clips. This one was thanks to one of our own. Thank you!

**Comment by ReinerBforartists** [comment]
I have no idea where this is. Nor how to access this.

**Comment by ReinerBforartists** [comment]
Fixed
