### ISSUE TITLE
Grease Pencil - Outliner Modifier

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#367]
![image](https://user-images.githubusercontent.com/35357409/197364577-6e30cb1c-7670-4496-bfa4-43a62e1c9ca8.png)
![bforartists_CSB0Hm4QDP](https://user-images.githubusercontent.com/35357409/197364579-6b239037-e986-4a2a-84d5-c5793bb03df7.png)

New outline modifier needs documentation for the Grease Pencil object

**Comment by ReinerBforartists** [comment]
Added text. Needs new screenshot once the prop is left aligned.

**Comment by ReinerBforartists** [comment]
Fixed
