### ISSUE TITLE
Grease Pencil - New Time Offset Chain mode in the modifier

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#368]
![image](https://user-images.githubusercontent.com/35357409/197364618-2c6b5b94-485d-492c-bee2-0f40ec9800ed.png)

New time offset mode is available, the "chain" mode. Should be documented.

**Comment by ReinerBforartists** [comment]
Please make screenshots where you can see what object type it is.

**Comment by ReinerBforartists** [comment]
Fixed
