### ISSUE TITLE
Geometry Nodes - Viewport Preview

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#369]
![image](https://user-images.githubusercontent.com/35357409/197364674-073c30a3-67b0-4d98-b1d7-c84fd51dd066.png)

New **viewport preview** method and how it works needs to probably be documented, unless it's already done.

**Comment by ReinerBforartists** [comment]
This node comes with node wrangler, right? Then it is not documented yet since we don't document addons that are not activated by default.

**Comment by ReinerBforartists** [comment]
Closing. Not documented yet. We might do this in case we really activate the node wrangler addon. Which is not set into stone yet.
