### ISSUE TITLE
Sculpt Mode - New Normal Based Automasking modes for brushes 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#371]
![image](https://user-images.githubusercontent.com/35357409/197364784-23fcc046-1de8-4cc6-b4c4-853b9a970a12.png)

New automasking mode through normals should probably be documented.

**Comment by ReinerBforartists** [comment]
Fixed with this commit: Sculpt Mode - New Cavity mask mode for Brushes #370
