### ISSUE TITLE
Nodes - new method to "duplicate linked" with hotkey ALT+D

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#373]
![bforartists_0jIYxGt2ZZ](https://user-images.githubusercontent.com/35357409/197365375-fba0620a-3dd0-4240-b6cd-37788a2b645a.png)

New operator in the node editors (shader, geometry nodes and compositor) means new documentation, and a new default hotkey `ALT+D`

Pending two tasks:
https://github.com/Bforartists/Bforartists/issues/3286
https://github.com/Bforartists/Bforartists/issues/3285

**Comment by ReinerBforartists** [comment]
Fixed
