### ISSUE TITLE
Node Editors - Update Context Menu manual

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#409]
![image](https://user-images.githubusercontent.com/35357409/221384607-85aa4d82-de4f-4344-b403-46a5a7410b16.png)
![bforartists_ui79vlhfL6](https://user-images.githubusercontent.com/35357409/221384614-e2577511-3a33-4ed3-8761-5b345aafa37a.png)

In the Node Editors, there is a new node context menu which is dynamic per node to some degree - and may need some mention. But first see if it's well mentioned.

**Comment by ReinerBforartists** [comment]
We have a chapter here, but it needs updating. Context menus are always covered at the beginning of a section.

12 - Geometry Node Editor.odt

**Comment by ReinerBforartists** [comment]
Fixed
