### ISSUE TITLE
Image Editor - Select Similar needs updating

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#417]
According to this task, these operators are now relatively exposed to the top level GUI instead of a floating panel. it has a little quirk that on first use, it won't poll the enums correctly. So.. ehm.. probably should add a warning about it there

https://github.com/Bforartists/Bforartists/issues/3204

**Comment by ReinerBforartists** [comment]
Don't add it when it does not work correct !

**Comment by ReinerBforartists** [comment]
Closing this task as invalid. I have reverted the change for now.
