### ISSUE TITLE
Geometry Nodes - Document new dropdown to select group socket subtype for node group input/output

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#426]
![image](https://user-images.githubusercontent.com/35357409/231610833-81a82f10-6566-48c5-a11d-ed04f284dace.png)

New option needs documentation - as now geometry nodes sub-types can be defined. 

## Relevant Task
> SHA-1: e7f395dd206dcd46ff9d8e89682b33cd9e95abe7
> 
> * Nodes: Add dropdown to select group socket subtype
> 
> Previously the only way to control the subtype was to remove the group
> input or output and create it again. This commit adds a dropdown to
> change an existing socket, for supported socket types.
> 
> Based on a patch by Angus Stanton: https://developer.blender.org/D15715
> 
> It was necessary to fix the UI code slightly; the layout's context
> wasn't being used in calls to an operator's enum items callback.
> 
> Pull Request: https://projects.blender.org/blender/blender/pulls/105614

**Comment by ReinerBforartists** [comment]
Done
