### ISSUE TITLE
Image Editor - New Overlaping Island support for UV Packing

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#429]
Should be documented
![bforartists_HqfPUdLlvT](https://user-images.githubusercontent.com/35357409/232844483-d2fe83d9-2dc5-45b7-9232-19da1ba6fbcb.png)

> 
> Revision: b601ae87d064cbde29e8ae7191ebba54213c709a
> Author: Chris Blackbourn <chrisbblend@gmail.com>
> Date: 12-Apr-23 18:12:36
> Message:
> UV: add overlapping island support for uv packing
> 
> From the UV Packing options, choose:
> 
>  "Merge Overlapped" / "Overlapping islands stick together"
> ----
> Modified: source/blender/editors/uvedit/uvedit_unwrap_ops.cc
> Modified: source/blender/geometry/GEO_uv_pack.hh
> Modified: source/blender/geometry/intern/uv_pack.cc
> 
>

**Comment by ReinerBforartists** [comment]
Hmmm. last operator gone. And we have differences to Blender in the panel. First we need to check what is going on here.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Manual/assets/35357409/a4ad9f4c-b27d-419c-bbb0-2ce7b46b0454)

Seems to be there, maybe it's a toolbar issue, where the last operator is not called if unpack is used elsewhere?

I can call it with the **Unpack** operator.

**Comment by ReinerBforartists** [comment]
This is a popup menu. The last operator resides usually down left. But it is also gone in Blender.

I made it an issue: https://github.com/Bforartists/Bforartists/issues/3552

**Comment by ReinerBforartists** [comment]
Fixed
