### ISSUE TITLE
Node Editors - Invert node now is called "Invert Color"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#433]
Update relevant chapters.

**Relevant task:**
> SHA-1: 9344deed8981cbb1d8ac9488b552708083beae12
> 
> * UI: Change the name of Invert nodes to Invert Color
> 
> The nodes for inverting a color are named simply Invert, which begs the question: invert what?
> 
> This patch changes the naming for the node in Shading, Texture and Compositing nodes to *Invert Color*
> 
> This matches the naming of other color dedicated nodes like Separate Color or Combine Color
> 
> Pull Request: https://projects.blender.org/blender/blender/pulls/106750

**Comment by ReinerBforartists** [comment]
Fixed
