### ISSUE TITLE
Sequencer - New Retiming tool in toolshelf needs documentation

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#434]
![image](https://user-images.githubusercontent.com/35357409/236639873-da7239b2-0e95-40f2-81b9-4802ab4e22ba.png)

New Retiming operators needs documetnation. You can retime things with it.

**Comment by ReinerBforartists** [comment]
Done

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Manual/assets/35357409/9743d82b-7460-4dd3-8f8a-e6d6aa1e34fb)
Really cool how this works.
