### ISSUE TITLE
UV Editor - Pack - new Scale prop

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#435]
![image](https://user-images.githubusercontent.com/35357409/236640995-1bff4d3b-45f6-43a3-8ecb-7de46d71790f.png)

Needs some documentation here. 

To see, hit the Pack UV 

```
SHA-1: bf56df3236cc4d075e6f474f7d18b17d0ed318ed

* UV: Add new packing option, scale_to_fit

When `scale_to_fit` is enabled, the existing behavior is used,
UVs will be scaled to fill the unit square.

If disabled, UVs will not be rescaled. They will be packed to the
bottom-left corner, possibly overflowing the unit square, or not
filling space.
```

**Comment by ReinerBforartists** [comment]
Related, and will be fixed in the same task. So closing this one here.

Image Editor - New Overlaping Island support for UV Packing #429
