### ISSUE TITLE
3D View - Proportional Size Slider needs documentation

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#438]
![image](https://github.com/Bforartists/Manual/assets/35357409/dab5d817-e510-4a4a-ace5-edb65fbc531b)

Relevant new slider needs documentation

> Relevant Blender task:
> SHA-1: 6b5b777ca3ea9e2b7654bf5d85a744c9e1aced8b
> 
> * UI: add Proportional Size to Proportional Edit popover
> 
> Rather than forcing the user to initiate a transform operation to edit the `Proportional Size`, allow editing of the `Proportional Size` through the UI.
> 
> The affected headers are:
> - View 3D
> - Dop Sheet
> - Image Editor
> - Graph Editor
> - Mask Editor
> 
> Pull Request: https://projects.blender.org/blender/blender/pulls/107507
>

**Comment by ReinerBforartists** [comment]
Done
