### ISSUE TITLE
UV Editor - Document the "Pinned" options when UV Packing

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#439]
![bforartists_iVAzZpV5he](https://github.com/Bforartists/Manual/assets/35357409/7c2c8c58-8096-41f6-90f6-5ad3d9f4f9cd)

When UV Unwrapping in the Last Operator menu, you have some new props, the pinned props. These should be documented.

**Relevant Blender Task**
```
SHA-1: 5abb3c96cfa5e16f4432241aafab8712c70945e9

* UV: Add pinned island support to uv packer

New pinned modes:
 * Ignore pinned islands
 * Normal (default)
 * Lock scale
 * Lock rotation
 * Lock position of pinned UV islands.
```

**Comment by ReinerBforartists** [comment]
Pack islands panel is already redocumented. Which makes this taks a duplicate. Closing as such.
