### ISSUE TITLE
UV Editor - UV Pack has new Rotation options, should be documented. 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#441]
![image](https://github.com/Bforartists/Manual/assets/35357409/30b0009e-d17f-4146-b769-9e6c0431b6ae)

When packing UV's, you get new rotation methods. Should be documented. 

<details>
<summary>Blender</summary>

SHA-1: f96e108b6399440fc63be909cc97359a73bbea6a

* UV: Complete options for rotation during uv packing

The rotation options are now:
* None
* Axis-Aligned (Blender 3.3 default)
   - Rotate to a minimal rectangle, either vertical or horizontal.
* Cardinal (new)
   - Only 90 degree rotations are allowed.
* Any
   - Blender 3.6 default.

</details>

**Comment by ReinerBforartists** [comment]
Whoopsie, already fixed

https://github.com/Bforartists/Manual/commit/bc27e4d73e0d1c6e7adb16ee2c79cd7f9c6fc4cd
