### ISSUE TITLE
Property Editor - Modifiers - Geometry Nodes - Internal Dependencies has a Bake path

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#442]
![image](https://github.com/Bforartists/Manual/assets/35357409/a55c7acb-6295-4812-a445-624000801c20)

Probably should be documented. This only shows when you have simulation nodes activated and used. 

<details>
<summary>Relevant Blender Task</summary>

SHA-1: edf4cb8b673edd37dd38dc79dd92dfdcd1488ba6

* Geometry Nodes: store path to simulation bake in modifier

This adds `char *simulation_bake_directory` to the nodes modifier. The path is automatically generated the first time the modifier is baked. It is _not_ automatically changed afterwards. The path is relative to the .blend file by default. For now, the path is not exposed in the UI or Python API.

This fixes issues where renaming objects/modifiers can cause the baked data to not work anymore.

Pull Request: https://projects.blender.org/blender/blender/pulls/108201

</details>

**Comment by ReinerBforartists** [comment]
This should be part of the new simulation nodes chapter. Related task: https://github.com/Bforartists/Manual/issues/444

**Comment by Draise14** [comment]
Documented. Also updated hierarchy of the simulation zone.
