### ISSUE TITLE
Document new simulation area nodes

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Manual#444]
Follow up of this task here: https://github.com/Bforartists/Bforartists/issues/3534

The whole simulation feature needs to be documented. It is not done with describing the two nodes. Which is something bigger. And cannot be done as a simple follow up of the above task. So making it a own task in the manual tracker.

![twonodes](https://github.com/Bforartists/Manual/assets/13919702/3c22787b-0202-438a-973d-3943b5b6492f)

**Comment by Draise14** [comment]
Created a new chapter
