### ISSUE TITLE
Asset Browser - Link as Instance toggle, new feature should be documented

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#445]
![image](https://github.com/Bforartists/Manual/assets/35357409/ae09599b-2434-4373-ab02-6cad999af66a)

New Link as Instance toggle added to the Asset Browser, should be documented. When it's on, you link collections as instances. When off, it links to scene.

**Comment by ReinerBforartists** [comment]
Fixed

**Comment by Draise14** [comment]
I thought I did this one when the task was complete! 🥴
