### ISSUE TITLE
Sequencer - Freeze Frame feature for Retiming tool needs documentation.

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#446]
> Freeze frames can be added now using retiming tool with no need to hold
> splitting strips or using hold offsets. To use this feature, add
> retiming handle where you want to freeze the frame, hold ctrl key and
> drag the handle. 
> 

<details>
<summary>Blender task</summary>

SHA-1: 6d215b87ce5d1c524c17a06535b6c324a9366945

* VSE: Freeze frame feature for retiming tool

Freeze frames can be added now using retiming tool with no need to hold
splitting strips or using hold offsets. To use this feature, add
retiming handle where you want to freeze the frame, hold ctrl key and
drag the handle. It is not possible to freeze frame of transition handle
and it is not possible to add transition to or from freeze frame.
Retiming system would handle these cases, but they are not useful in
practice.

When freeze frame is created, start handle of frozen segment is flagged
as `FREEZE_FRAME`. Most handling is similar to `SPEED_TRANSITION`
type handle. For evaluation, there is no special case for this type, as
it's just 2 handles with same `retiming_factor` value. It is possible to
recreate this behavior without using freeze frame feature by adding
handle between 2 consecutive content frames, but this would not be
recognized by UI or treated as freeze frame segment/handle.

Eventually this feature should replace hold offsets, leaving `Sequence`
struct with single offset type, see PR 105620 for reference.

</details>

**Comment by ReinerBforartists** [comment]
A screenshot could do a miracle here. I don't even have the slightest idea where this resides.

**Comment by Draise14** [comment]
This was reverted by blender, no-longer a feature.
