### ISSUE TITLE
3D View - Snap menu has a large update

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#448]
![image](https://github.com/Bforartists/Manual/assets/35357409/7dcdd40e-3e0c-49dd-9c5d-a04ebeec6ba6)

Snap menu has quite a large update, with new sections and features. 

<details>
<summary>Blender Task</summary>

SHA-1: 8e059b569b8b9e6c18a8774a806b627d1c98e371

* UI: move 'Face Nearest' snap option to another section

The snap mode called "Face Nearest" (and the "Increment" but that's for
another time) doesn't behave like the other snap modes.

Unlike the other snap modes, "Face Nearest" does not act on a Snap
Base (or Snap Source).

It always acts on the origin of individually transformed elements, (such
as each vertex individually).

It works just like the "Project Individual Elements" option.

So this commit makes the following changes:
- `Snap With` was moved to the beginning of the popover
- `Align Rotation to Target` and `Backface Culling` have been moved closer to the snap targets
- `Snap With`, `Target Selection` and `Align Rotation to Target` are no longer hidden by varying the mode and options
- `Project Individual Elements` has been replaced with the `Face Project` option
- `Face Nearest` has been moved to stick together with the `Face Project` option

Co-authored-by: Germano Cavalcante <germano.costa@ig.com.br>
Pull Request: https://projects.blender.org/blender/blender/pulls/108555

</details>

**Comment by ReinerBforartists** [comment]
Fixed
