### ISSUE TITLE
User Preferences - File Paths - Applications - New external Text Editor options

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#449]
![image](https://github.com/Bforartists/Manual/assets/35357409/963d5272-6ef8-4f41-907d-00ad0e2d3ce4)

New external text editor options are now possible, meaning you can open docs in an external IDE of a sort. Should be documented. 

This task is pending another. 
https://github.com/Bforartists/Bforartists/issues/3595

**Comment by ReinerBforartists** [comment]
Wow, implemented in the typical Blender manner. You cannot fingure out how to use it first. And then it is simpyl buggy. BFA crashes with opening a UI file externally.

**Comment by ReinerBforartists** [comment]
We have a bug here. Blender becomes unresponsible with an external editor when using it at a Blender UI element. So we might want to change the information once this is cleared. 

https://projects.blender.org/blender/blender/issues/109149
