### ISSUE TITLE
Compositor - Preview Toggles now also under Overlay Options and should be update

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#453]
![bforartists_RFMEfia3Lz](https://github.com/Bforartists/Manual/assets/35357409/939ebb2f-3c06-477a-87d5-f7b32ac6b9b3)

New prop in the overlays to toggle the previews of the nodes needs updating and documentation. This also changes how images are drawn. 

> Move the node previews to the overlay region, atop each node.
It allows nodes to keep the same size when the preview is toggled,
which is more convenient for large nodes and large nodetrees.

<details>
<summary>Blender Task</summary>

SHA-1: 1ebdd2d9cf8e7abc81041fb3ae4240c54ab130ac

* Nodes: Move preview images to an overlay

Move the node previews to the overlay region, atop each node.
It allows nodes to keep the same size when the preview is toggled,
which is more convenient for large nodes and large nodetrees.

The preview has to be drawn from `node_draw_extra_info_panel`
because there could be overlapping between info text and the preview.
When the node is out of the view, it also has to make sure that the
preview is also out of the view before exiting the draw function.

Pull Request: https://projects.blender.org/blender/blender/pulls/108001

</details>

**Comment by ReinerBforartists** [comment]
Can't wrap my head around the nodes noodles to document this, sorry ^^
