### ISSUE TITLE
Fcurve Editor - Key - Smooth - New Buttersworth Smooth operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#455]
![image](https://github.com/Bforartists/Manual/assets/35357409/563e5eca-69cf-455a-907e-85aaf4713a31)

There is a new operator, but could be the same icon. 

This will require additional documentation, so will make a task for that. 

<details>
<summary>Blender Info</summary>

SHA-1: 7acd6e61ab11b6ade31fbf135801742cbf8c6cd3

* Animation: Butterworth Smoothing filter

Implements the Butterworth Filter
(https://en.wikipedia.org/wiki/Butterworth_filter) for smoothing FCurves.

This filter is ideal for smoothing dense data, like motion capture recordings.
It has the advantage of keeping the shape of the curve
intact while reducing minimal fluctuations.
The disadvantage is the impulse response has a twang,
meaning extreme spikes cause fluctuations to either side.

The implementation is based on the GPL code found here:
https://exstrom.com/journal/sigproc/dsigproc.html

In order to avoid phase shifting, the filter is run forward and backward,
effectively doubling the filter order.

The Redo panel offers the following options

* Frequency Cutoff: 0-n value, where 0 means it cuts everything
so the curve will become straight, the max value is the Nyquist frequency
and depends on the frame rate and the "Samples per Frame" option

* Filter Order: Higher values mean the frequency cutoff is steeper

* Samples per Frame: Before the filter is applied, the curve is resampled
at this interval to avoid errors when there are uneven spaces between frames.
If the keys are on subframes, e.g. a 60fps file in a 30fps scene, increase this value to 2

* Blend: 0-1 value to blend between the original curve and the filter result

* Blend In/Out: The number of frames at the start and end for which
to blend between the filtered and unfiltered curve.
This can help reduce any resulting jumps in the animation at the selection border

The operator can be called from the Key menu. (Key->Smooth->Butterworth Smooth)

Pull Request: https://projects.blender.org/blender/blender/pulls/106952

</details>

**Comment by ReinerBforartists** [comment]
Already fixed
