### ISSUE TITLE
Shader Nodes - Velvet BSDF is now Sheen BSDF

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#456]
![image](https://github.com/Bforartists/Manual/assets/35357409/edfedeb1-fd7b-4c9f-b29a-b12d972aad89)

> The old model is still available, but new nodes now default to the
"Microfiber" model, which is an implementation of

<details>
<summary>Blender Task</summary>

SHA-1: b220ec27d7db68aca9a8c500ecd8c99efcdecbc5

* Cycles: Update Velvet BSDF to Sheen BSDF with new Microfiber sheen model

This patch extends the old Velvet BSDF node with a new shading model,
and renames it to Sheen BSDF accordingly.

The old model is still available, but new nodes now default to the
"Microfiber" model, which is an implementation of
https://tizianzeltner.com/projects/Zeltner2022Practical/.

Pull Request: https://projects.blender.org/blender/blender/pulls/108869

</details>

**Comment by ReinerBforartists** [comment]
Already fixed.
