### ISSUE TITLE
Nodes Editors - Add Lacunarity and Normalize inputs to Noise node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#459]
![image](https://github.com/Bforartists/Manual/assets/35357409/03f698e0-3c5d-47ff-8a4c-ec48394814d0)

New sliders means new documentation. 

> The Lacunarity input controls the scale factor by which each
> successive Perlin noise octave is scaled. Which was previously hard
> coded to a factor of 2.
> 
> The Noise node normalizes its output to the [0, 1] range by default.
> The Normalize option makes it possible for the user to disable that.
> To keep the behavior consistent with past versions it is enabled by
> default.

<details>
<summary>Blender Details</summary>

SHA-1: 0702c24a36b221e8a1c3a8d660f8c9fe01d0d31e

* Nodes: Add Lacunarity and Normalize inputs to Noise node

This PR adds the Lacunarity and Normalize inputs to the Noise node
similar to the Voronoi node.

The Lacunarity input controls the scale factor by which each
successive Perlin noise octave is scaled. Which was previously hard
coded to a factor of 2.

The Noise node normalizes its output to the [0, 1] range by default.
The Normalize option makes it possible for the user to disable that.
To keep the behavior consistent with past versions it is enabled by
default.

To make the aforementioned normalization control easer to implement,
the fractal noise code now accumulates signed noise and remaps the
final sum, as opposed to accumulating positive [0, 1] noise.

Pull Request: https://projects.blender.org/blender/blender/pulls/110839

</details>

**Comment by ReinerBforartists** [comment]
Fixed
