### ISSUE TITLE
USD Import - new Blend Shapes and Skeletons options

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#460]
![bforartists_Fig7Z7szPZ](https://github.com/Bforartists/Manual/assets/35357409/41521dff-4f54-401a-9b8a-3ee2a69d83c9)

USD import is more viable, should be documented. 

<details>
<summary>Blender Task</summary>

SHA-1: 6f4cb9bc56e43343ab2a58eade516e5c7dbc77a3

* USD:  Skeleton and blend shape import

Added support for UsdSkel animation import.

This addresses #110076.

Added USDSkeletonReader class which imports UsdSkelSkeleton primitives
as armatures.

Extended USDMeshReader to import UsdSkelBlendShape as shape keys.

Extended USDMeshReader to import USD skinning data as as deform groups
and an armature modifier on the mesh object.

Added USDMeshReader::get_local_usd_xform() to override the transform
computation to account for the binding transformation for skinned meshes.

Pull Request: https://projects.blender.org/blender/blender/pulls/110912

</details>

**Comment by ReinerBforartists** [comment]
Fixed
