### ISSUE TITLE
3D View - Armature - Pose Mode - New Asset Shelf toggle and shelf

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#465]
![image](https://github.com/Bforartists/Manual/assets/35357409/d69801e9-4d5a-487e-8ecd-307b1593e0c3)

New asset shelf (that ONLY works with pose assets on Armatures) is now available and no-longer experimental. Should be exposed to documentation somewhere....

**Comment by ReinerBforartists** [comment]
I find this ugly UX. The switch would fit better into the Pose options. And sheesh, why horizontal at the bottom ...

**Comment by Draise14** [comment]
Yeah this shelf won't be pose only but all asset types maybe eventually.... It's a quick method of using the browser assets being designed for brush assets. 

I wish they would allow marking all data types and allow drag and drop to relevant areas from the asset browser and viola.. but most effort is to create brush overrides and this new shelf. 😂

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Manual/assets/35357409/0e2ee729-981a-48d2-8a87-af1dd5820332)

Had a lot more love this one.
