### ISSUE TITLE
Preferences - New Playback Frame Rate (FPS)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#466]
![image](https://github.com/Bforartists/Manual/assets/35357409/7105b2c2-8e6a-4c58-b63a-ad760f50a52d)

New preference with samples for framerate as the playback overlay. 

<details>
<summary>Details</summary>

SHA-1: b150b477202dc6d2a595b51be8cc34f8d6269731

* UI: add a preference for the number of samples used for FPS playback

This was hard coded to 8, which can still result in a number that
jitters making the overall FPS difficult to measure.

The default is still 8, but this is now a preference that can be
increased for values that don't jitter as much.

</details>

**Comment by ReinerBforartists** [comment]
Fixed
