### ISSUE TITLE
3D View - Overlays - New Random wireframe colours

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#467]
![image](https://github.com/Bforartists/Manual/assets/35357409/af5d4690-09dc-43ad-bcdf-794edf3b063d)

New random wireframe colours was merged in! Yay! Love this. This was a Rclickselect request of mine. 

<details>
<summary>Details</summary>

SHA-1: 1f4c7a36df6adf022feb273c1e2f68860d70dacb

* Wireframe color option for all shading modes

Enables three options of wireframe color for all shading modes: theme color, object color
and random color.  Previously this was exclusive to the wireframe shading mode.

Pull Request: https://projects.blender.org/blender/blender/pulls/111502

</details>

**Comment by ReinerBforartists** [comment]
Not happy with this UX. To see this result you need to activate wireframe first. So you are searching through two panels.

Either way, let's document this.

**Comment by ReinerBforartists** [comment]
Fixed
