### ISSUE TITLE
User Preferences - Fresnel Wireframes for Edit Mode

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#468]
![image](https://github.com/Bforartists/Manual/assets/35357409/a0916ac3-3cfe-4c06-90d9-22a9c657dbe0)

New Fresnel toggle for edit mode overlays. 

May need a float left checkbox before being documented. 

<details>
<summary>Details</summary>

SHA-1: fb6687a79043fb00e2dcaa3478a547917be2a63a

* Viewport: Add toggle for edit mode overlays fresnel

Adds a userpref toggle for the edit mode overlays fresnel.
The edit mode fresnel is only a bit useful in edge cases, like
very dense photogrametry, and the problem is that it causes
more eye strain when modeling for many hours. And it's
benefit on shape readability is small compared to it's negative
impact on selection visibility. It makes the selection color to a
darker less saturated color instead of the theme color, which
leads to worse contrast between the selection and the mesh
or with the background, and also makes the unselected (black)
brighter, also reducing contrast. So it's off by default.

This was split up from https://projects.blender.org/blender/blender/pulls/110097

Pull Request: https://projects.blender.org/blender/blender/pulls/111494

</details>

**Comment by ReinerBforartists** [comment]
Already fixed. Closing
