### ISSUE TITLE
Node Editors - Group Tab - Interface panel - New panel and functionality should replace old one. 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#469]
![image](https://github.com/Bforartists/Manual/assets/35357409/65c5d231-4df3-4785-b6a5-281e893ad262)

They changed the complete way the node groups work now that we can have sub-groups in the panels - which is very nice. It still needs love, but it should start to be documented. 

<details>
<summary>Details</summary>

SHA-1: e071288ab2901f43a5cde82a49c02101cd579aad

* Nodes: Panels integration with blend files and UI

Part 3/3 of #109135, #110272

Switch to new node group interfaces and deprecate old DNA and API.
This completes support for panels in node drawing and in node group
interface declarations in particular.

The new node group interface DNA and RNA code has been added in parts
1 and 2 (#110885, #110952) but has not be enabled yet. This commit
completes the integration by
* enabling the new RNA API
* using the new API in UI
* read/write new interfaces from blend files
* add versioning for backward compatibility
* add forward-compatible writing code to reconstruct old interfaces

All places accessing node group interface declarations should now be
using the new API. A runtime cache has been added that allows simple
linear access to socket inputs and outputs even when a panel hierarchy
is used.

Old DNA has been deprecated and should only be accessed for versioning
(inputs/outputs renamed to inputs_legacy/outputs_legacy to catch
errors). Versioning code ensures both backward and forward
compatibility of existing files.

The API for old interfaces is removed. The new API is very similar but
is defined on the `ntree.interface` instead of the `ntree` directly.
Breaking change notifications and detailed instructions for migrating
will be added.

A python test has been added for the node group API functions. This
includes new functionality such as creating panels and moving items
between different levels.

This patch does not yet contain panel representations in the modifier
UI. This has been tested in a separate branch and will be added with a
later PR (#108565).

Pull Request: https://projects.blender.org/blender/blender/pulls/111348

</details>

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Manual/assets/35357409/053b0a07-7f6d-4e7d-b4b1-04939fbf6eac)

Can now include both too. 

<details>
<summary>Details</summary>

SHA-1: 9433a1701a47a625dacc6b249f90aecc524e72fb

* Nodes: Support for input/output sockets in same vertical space

Declarations can use the `add_input_output` method to create a combined input/output socket. The drawing code supports moving sockets up one vertical slot to align them with the predecessor.

Closes #112235

Pull Request: https://projects.blender.org/blender/blender/pulls/112250


</details>

**Comment by Draise14** [comment]
Both was removed. 

<details>
<summary>Details</summary>

SHA-1: 354915cf3c87bdebff6c63c8e88579e87eb0b8dc

* Nodes: revert the inline (pass-through) socket feature

Inlined sockets in the same vertical space are no longer supported.
This removes `input_output` socket declarations, the inlining feature in
node drawing, and the `Both` option for node group interface sockets.

Versioning code splits existing node group sockets into individual
sockets again. Unfortunately some links may get lost in versioning files
using the feature, because of an unnoticed bug: Socket identifiers have
to be unique in the node group items list but inlined input/output
sockets have the same identifier. This still works for most situations
because uniqueness is only required within input/output lists. Creating
proper unique identifiers will discard any link from the previous output
socket. This cannot easily be fixed without `after_linking` versioning
code, which should be avoided.

Pull Request: https://projects.blender.org/blender/blender/pulls/112560


</details>

**Comment by ReinerBforartists** [comment]
Is this task still valid?
