### ISSUE TITLE
Properties Editor - New method to add modifiers, needs updating

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#473]
![bforartists_4sKdTi0RvY](https://github.com/Bforartists/Manual/assets/35357409/b10559a7-3aa5-46a1-a296-773b6ed6375a)

The Modifier add menu got a face lift with sub menus.......... we should udpate that till we think of something better. 

New Features:
- new empty "geometry nodes" on top level
- Sub categories
- New asset libraries that get listed.

**Comment by ReinerBforartists** [comment]
Next biggie ...

**Comment by ReinerBforartists** [comment]
Hm, i am in trouble to find out what Output Attributes and Internal Dependencies is good for. They show up in all of the hair modifiers.

Can hair node groups be baked?

![attributes_dependencies](https://github.com/Bforartists/Manual/assets/13919702/db41f51f-0eab-463f-9de3-ef905f629c73)

**Comment by ReinerBforartists** [comment]
Fixed. Finally.
