### ISSUE TITLE
Node Editors - Add menus - Instant Search 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#476]
![image](https://github.com/Bforartists/Manual/assets/35357409/51c9849a-4a42-4ff6-918b-bc7f36a39913)

You can now instantly search from an add menu to add things - should be mentioned in documentation somewhere.

**Comment by ReinerBforartists** [comment]
Let's put a short note in every add menu chapter.

**Comment by ReinerBforartists** [comment]
Fixed
