### ISSUE TITLE
Properties Editor - Armature Tab - New Custom Properties sub-panel for Bone Collection panel

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#477]
![image](https://github.com/Bforartists/Manual/assets/35357409/f93cc079-db08-4f14-9490-83af6d6a259f)

This may need a lot more work before this one is done - since we now have bone collections. 

<details>
<summary>Details</summary>

SHA-1: e6bb1374f9cb27b51f8fe59c843932b267a3dd00

* Anim: add bone collection custom properties sub-panel

Add a 'Custom Properties' sub-panel to the Bone Collections panel.

Custom properties for bone collections were introduced in 9eee076a299,
this just adds the GUI.

Ref: #108941

</details>

**Comment by ReinerBforartists** [comment]
Manual is already up to date here. Closing
