### ISSUE TITLE
Properties Editor - Bone tab - Viewport Display - Bone Colours

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#479]
![image](https://github.com/Bforartists/Manual/assets/35357409/b7d66507-6b35-41d5-887b-f654ba22903b)

![bforartists_o6noLkY1no](https://github.com/Bforartists/Manual/assets/35357409/61778ee0-f073-4529-af7b-86b7f5216f24)

Bone colours are now no-longer attached to bone group colours, but independant based on the bone viewport display settings...

_It's more flexible, but much more messy........._

**Comment by ReinerBforartists** [comment]
Not this much to do here, just updating two images.
