### ISSUE TITLE
Preferences - Editing - Text Editor "Auto Close Character Pairs"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#482]
![image](https://github.com/Bforartists/Manual/assets/35357409/41e0c735-29d2-4450-925b-6378b7865009)

New toggle for text editor in preference 

<details>
<summary>Details</summary>

SHA-1: 96339fc3131789e6caa41f7ef01cc1edf5a38a28

* Text Editor: Auto Close Pairs on Selected Text

When the auto-close preference is enabled & brackets or quotes are
entered with a selection, the selection is surrounded by those
characters - instead of replacing the selection.

Match functionality from visual-studio code.

Ref !111900.

</details>

**Comment by ReinerBforartists** [comment]
Already documented. Closing.
