### ISSUE TITLE
3D View - Object mode dependant overlays dropdown

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#483]
![image](https://github.com/Bforartists/Manual/assets/35357409/dc9a4aa4-9c45-4b30-8fd9-4f8be4e76458)

Now the overlays panel has a seperate dropdown for object specific overlay settings. 

<details>
<summary>Details</summary>

SHA-1: 4fa4f5432d39b1d942d603436232a00a79db491d

* UI: Viewport: Split object/mode overlays into own popover

Move object/mode-specific overlays into their own popover
in order to reduce scrolling and improve discoverability.

Pull Request: https://projects.blender.org/blender/blender/pulls/112156

</details>

**Comment by ReinerBforartists** [comment]
Bigger problem is as usual a outdated manual -.-

**Comment by ReinerBforartists** [comment]
... and that i need to fix the tools first -.-

**Comment by ReinerBforartists** [comment]
Fixed
