### ISSUE TITLE
Shader Nodes - Cycles - Hair BSDF - removed "normals" socket

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#484]
![image](https://github.com/Bforartists/Manual/assets/35357409/8778e8e3-8c0e-4746-a494-e32c7e8367f5)

Quick update, "Normals" is removed. 

<details>
<summary>Details</summary>

SHA-1: 5939810b3c7954f13ac4c0c8cc32b1e924767f4f

* Cycles: Remove unused Normal input on Hair BSDF

This was causing a warning when using OSL, since the OSL implementation
didn't implement the input.
Since the socket isn't really implemented on the Blender side anyways,
just get rid of it.

Also, the SVM code uses the shading normal while OSL used the geometric normal.

</details>

**Comment by ReinerBforartists** [comment]
I triple checked now, nothing to do here. This change happened under the hood.
