### ISSUE TITLE
Shader Nodes - Principled BSDF - Has panels now

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#485]
![bforartists_jd4UUCxlLO](https://github.com/Bforartists/Manual/assets/35357409/3bccf750-7131-4406-b233-856b50c95ae6)

Has panels now. Update! 

<details>
<summary>Details</summary>

SHA-1: 88ad79c2d19b0dc705df06cebf6829cf31f62aaa

* Add panels to Principled BSDF node

Add panels to the Principled BSDF node to organize
and reduce the size of the node.

Layout inspired by previous work from @LukasStockner

Pull Request: https://projects.blender.org/blender/blender/pulls/112314

</details>

**Comment by Draise14** [comment]
More changes:

<details>
<summary>Move subsurface scale input below radius </summary>

SHA-1: 3d986b81c54ba2e12652568c2e909625d740ca78

* Shaders: move subsurface scale input below radius in Principled BSDF

To help clarify that this is a scale on the radius.

Ref #99447
Ref #112848


</details>

<details>
<summary>use single Principled BSDF input for metallic and specular tint</summary>

SHA-1: 334027063eb77d547a3d3e232faa4656f193619e

* Shader: use single Principled BSDF input for metallic and specular tint

To match Standard Surface and OpenPBR.

Ref #99447
Ref #112848


</details>

<details>
<summary>rename Principled BSDF Emission to Emission Color</summary>

SHA-1: ca5f1c0f008ae703bd00a08919848c766ee76bfb

* Shaders: rename Principled BSDF Emission to Emission Color

Ref #99447
Ref #112848


</details>

**Comment by ReinerBforartists** [comment]
Ah, forgot to close ...
