### ISSUE TITLE
Create new chapter for asset shelf

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Manual#486]
The asset shelf is a new browser element which we haven't documented yet. It is part of the 3d view in pose mode, and should be documented somehow in this conjunction. I am just unsure where. Ideas?

![assetshelf](https://github.com/Bforartists/Manual/assets/13919702/1a14c29d-9752-4a6d-a74a-abbb2876d98b)

**Comment by Draise14** [comment]
Mention of it in the editor chapter 7 is there. Now it's it's own chapter.

**Comment by Draise14** [comment]
New 7.4 chapter.
