### ISSUE TITLE
Document Simulation nodes panel in the physics tab in properties editor

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Manual#488]
We have new simulation nodes. And we have a new panel in the physics tab then. Needs documentation.

![simu](https://github.com/Bforartists/Manual/assets/13919702/12ab9a18-053a-4c30-8513-a9677e7a5e9b)

**Comment by Draise14** [comment]
Already partially documented in **12.1.32 Editors - Geometry Nodes Editor - Header - Add Menu - Simulation** but should also be added to the Physics tab chapter. I'll do that. I'm working on clearing the documentation tracker today a bit.
