### ISSUE TITLE
Change the header of all chapters to Bforartists version 4

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Manual#491]
Bforartists 4 is near, we need to go through all manual chapters and change it to version 4.

**Comment by Draise14** [comment]
on it. Up to chapters 8

**Comment by Draise14** [comment]
Up to Chapter 10. Will unassign, got a headache. Will continue morrow.

**Comment by Draise14** [comment]
Up to chapters 15

**Comment by Draise14** [comment]
Up to chapter 19. Will continue morrow and try knock it out and done.

**Comment by Draise14** [comment]
Ok, let's finish this.

**Comment by Draise14** [comment]
Finally done.. phew... we need a better system with equal feature parity as this...........

**Comment by ReinerBforartists** [comment]
I don't know of any good one. The usual ones are the nerdy ones where you need tech skills.

It's luckily just once every new major version.
