### ISSUE TITLE
Geometry Nodes - Node Groups - "Single Value" for input

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#494]
![image](https://github.com/Bforartists/Manual/assets/35357409/104e60d8-5860-4de0-808e-b91c940d94ed)

> orce inputs to be single values and not accept varying fields.

<details>
<summary>Details</summary>

SHA-1: 6875925efa2acdd25eec5165915b2c79533746d8

* Geometry Nodes: Add option to force inputs to be single values

Add a checkbox to node group inputs to force inputs to be single values
and not accept varying fields. While this could also be done more
automatically, and it could be argued that requiring the flexibility is
helpful for users who want to use attributes, there are cases where the
field inferencing doesn't work, or the "use attribute" option is just
unhelpful. People use workarounds with primitive nodes to get the same
behavior anyway.

Pull Request: https://projects.blender.org/blender/blender/pulls/112745

</details>

**Comment by ReinerBforartists** [comment]
Fixed
