### ISSUE TITLE
File Browser - Recen - Changed name "Clear Recent Items" instead of "Reset"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#495]
![bforartists_uqah4PA7hc](https://github.com/Bforartists/Manual/assets/35357409/3fe9b122-f5da-4014-b208-8747666081b0)

Something small, but an update. 
<details>
<summary>Details</summary>

SHA-1: 90d8a07213f712cb0ce138d2030cffe91f6de9a6

* UI: Move "Reset Recent" inside a menu

Move the File Browser's `Reset Recent` button into a menu to prevent
accidental clicks of a destructive operation.

Also rename it to a more descriptive  `Clear Recent Items`, and since
the word "Reset" is used for resetting values to default.

Pull Request: https://projects.blender.org/blender/blender/pulls/112853

</details>

**Comment by ReinerBforartists** [comment]
Fixed
