### ISSUE TITLE
Properties Eidtor - Object - Light Options - Light Linking has check boxes now...

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#496]
![image](https://github.com/Bforartists/Manual/assets/35357409/0db20dc3-e539-4e3b-a6f9-ad68af12fdd5)

before it was a light icon. But now it's not. 

<details>
<summary>Details</summary>

SHA-1: 489693ef6dd2fc42b4470538fc19e49788df9354

* Light linking: Use checkbox icons for state indication

This is as per design task #104972

The same icons as exclusion in the outliner are used.

Pull Request: https://projects.blender.org/blender/blender/pulls/112857

</details>

**Comment by ReinerBforartists** [comment]
Also here, where does this hide? It is not clear from the screenshot.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Manual/assets/35357409/33aab5c8-6e48-4463-8e3f-67fbd9efa732)

Cycles Only, any object that can emit light (mesh [with emission] or light)

Properties Panel > Object Tab > Light Options Panel > Light Linking sub-panel

Only shows when you have it assigned to a light group + a collection to light linking sub-panel.

**Comment by ReinerBforartists** [comment]
Same here, where does it hide?

![nope](https://github.com/Bforartists/Manual/assets/13919702/c8a23c3e-00e4-45e9-a61c-fac3e3c1a83f)

**Comment by Draise14** [comment]
Switch to cycles, this is cycles only.

**Comment by ReinerBforartists** [comment]
Ah, this explains it :D

Many thanks :)

**Comment by ReinerBforartists** [comment]
Fixed
