### ISSUE TITLE
Properties Eidtor - Object - Light Options - Show you can drag and drop 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#497]
![image](https://github.com/Bforartists/Manual/assets/35357409/b1b62e28-2a20-4c04-86e7-0cb61c467137)
You can now drag and drop to change object order of light group collection... not sure why. But you can. 

> This commit utilizes the generic tree view reordering operations to
allow insertion of elements to a specific location and to re-order
existing objects and collections in the light linking collection.

> It is possible to re-order both collections and objects, even tough
re-ordering objects does not really make a difference for the light
linking behavior. It is not possible to place an object before
collections.

<details>
<summary>Details</summary>

SHA-1: 19db9a213e2d2523362346ed63d3871caeca5068

* Light linking: Allow re-ordering in the light linking collections

The order of collections in the light linking collection is important
as it is used for tie-breaking when the same object is reachable from
multiple linked collections with different light linking state.

This commit utilizes the generic tree view reordering operations to
allow insertion of elements to a specific location and to re-order
existing objects and collections in the light linking collection.

It is possible to re-order both collections and objects, even tough
re-ordering objects does not really make a difference for the light
linking behavior. It is not possible to place an object before
collections.

Pull Request: https://projects.blender.org/blender/blender/pulls/112849

</details>

**Comment by ReinerBforartists** [comment]
Cannot find the light linking panel. With what object, in what tab?

@Draise14 , could you please be a bit more generous in your screenshots? I always start to search what is meant and where it hides. A simple screenshot that shows the whole would make my life so much easier :)

**Comment by ReinerBforartists** [comment]
I don't have these options. What step do i miss?

![nope](https://github.com/Bforartists/Manual/assets/13919702/2a5d0109-a6de-4ca4-94e7-b46e746c7a7d)

**Comment by Draise14** [comment]
Cycles only. 😉

**Comment by ReinerBforartists** [comment]
This is mean :'3

**Comment by Draise14** [comment]
Yeah, the light linking workflow is really bizzare... Not intuitive aaaat all.

**Comment by ReinerBforartists** [comment]
I'm too far away from any useful workflow nowadays. Too long away from making graphics. I fear i am of no big help to make this one more useful ...

**Comment by ReinerBforartists** [comment]
Fixed

**Comment by ReinerBforartists** [comment]
Hmh, where's mah commit? O_O
