### ISSUE TITLE
Shaders - Principled BSDF Coat tint is now a colour

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#498]
![image](https://github.com/Bforartists/Manual/assets/35357409/08357d53-a66d-4ad4-aa1a-a054edee1587)

Yep, a color. Nice.

<details>
<summary>Details</summary>

SHA-1: def9b762070131979905affb36e10efdb3cc42d2

* Shader: Change specular tint in Principled BSDF from float to color

For more artistic control. Tints the reflection of dielectric materials
at normal incidence.

Ref #99447

Pull Request: https://projects.blender.org/blender/blender/pulls/112192

</details>

**Comment by ReinerBforartists** [comment]
Fixed
