### ISSUE TITLE
Geometry Nodes - Repeat Zone - Node - New Inspection Index prop

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#500]
![image](https://github.com/Bforartists/Manual/assets/35357409/5fdceeab-eec0-401b-9047-5a171778b531)

New Repeat Zone inspection index... this getting more and more complex! But useful this one. 

>  Previously, it was only possible to inspect the data from the first iteration. That applied to both, the viewer node as well as socket inspection. It specifies which iteration should be used by the inspection features.

<details>
<summary>Details</summary>

SHA-1: c8cc169d6fee3dc763075ff9d6fa5ac6722d5dd7

* Geometry Nodes: add Inspection Index to Repeat Zone

Previously, it was only possible to inspect the data from the first iteration. That
applied to both, the viewer node as well as socket inspection. Now, there is a
new `Inspection Index` setting in the zone properties. It specifies which iteration
should be used by the inspection features.

In theory we could support features like counting the index from the end, but
that can be done separately as well, as it likely requires more UI.

Pull Request: https://projects.blender.org/blender/blender/pulls/112818

</details>

**Comment by ReinerBforartists** [comment]
Fixed
