### ISSUE TITLE
Asset Shelf - Now has library selector

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#501]
![image](https://github.com/Bforartists/Manual/assets/35357409/622e92c5-431b-4979-8f4b-ebf0a1be5010)

Yep, document it. 

<details>
<summary>Details</summary>

SHA-1: 1da08a55563da3614d3818b74379e82a8bf6022f

* Asset shelf: Add asset library selector

Adds a menu to choose the asset library to use to the asset shelf
catalogs selector popover. This is consistent with the asset browser.
After talking to animators and some artists, this is likely something
they would want to have, since they don't always want all their assets
and catalogs to populate the asset shelf. It's also necessary for the
pose library UI to provide the same features roughly than the old one
(in the sidebar, before the asset shelf was introduced).

</details>

**Comment by ReinerBforartists** [comment]
Nevermind, this fits. 

Other question, it is not documented how to add any content to this lib. And i cannot find any way to add a pose to any of the asset libs. Just mark as asset, which makes the whole skeleton then a asset, but not the pose.

**Comment by ReinerBforartists** [comment]
Done. Misses the information though how one can add a pose here ...

**Comment by ReinerBforartists** [comment]
Meow? How do i add a pose?

**Comment by Draise14** [comment]
Record one keyfram on rig. Store as animclip. Mark clip as asset or use the mark pose as asset from the file browser menu.

**Comment by ReinerBforartists** [comment]
I am in trouble with step 2 :(
How do i store as animation clip?

**Comment by ReinerBforartists** [comment]
Sheesh what a lousy UX. I always end in having an asset in the asset library. But no pose. What ass forward step do i miss here? What file browser do you mean? Where do i mark the clip as an asset?

![whatstepismissing](https://github.com/Bforartists/Manual/assets/13919702/491169d9-e2e8-4491-9003-ff95f0f4c768)

**Comment by Draise14** [comment]
I'll document this later today.

**Comment by Draise14** [comment]
There is an operator for this in the Asset Browser editor, so maybe adding that to the asset shelf might also make sense.

**Comment by ReinerBforartists** [comment]
Worth a look !

**Comment by ReinerBforartists** [comment]
Found this operator. But am still lost ...

![stillgreyedout](https://github.com/Bforartists/Manual/assets/13919702/b6ca0fe8-f08c-430c-ba9b-77f010d9f077)

**Comment by Draise14** [comment]
Added the info and note for how to use it.
