### ISSUE TITLE
Properties Editor - Armature - Skelaton panel now Pose panel

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#502]
![image](https://github.com/Bforartists/Manual/assets/35357409/b01f4858-b84f-42a6-99af-def6892d64fd)

<details>
<summary>Details</summary>

SHA-1: 007cea465373789ad57813f23405f4dcd9d39aae

* Anim: rename the 'Skeleton' panel to 'Pose'

In the Armature properties, rename the 'Skeleton' panel to 'Pose'. This
panel used to house the armature layers, but they have been transformed
into bone collections, which have their own panel. Also the term 'skeleton'
is not used in Blender, so having that as title here felt out of place.

There are some ideas to introduce different 'poses', to disconnect the
mesh binding pose from the animation reference pose. This rename sets
things up for exposing such functionality.

</details>

**Comment by ReinerBforartists** [comment]
Fixed
