### ISSUE TITLE
Properties Editor - Bone - Viewport Display - Has a button to copy color to selected

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#503]
![image](https://github.com/Bforartists/Manual/assets/35357409/f9a98252-e5d8-4ee8-9c77-4c3700c50834)

New operator. 

<details>
<summary>Details</summary>

SHA-1: 1930ebdb4fff510411c8d8ddeb6936c698fa57bc

* Anim: add operator to sync bone colors between selected bones

Blender's "Copy to Selected" feature only copies single properties, while
bone colors consist of four properties (palette + 3 custom colors). These
can now be copied with a single click.

</details>

**Comment by ReinerBforartists** [comment]
Fixed
