### ISSUE TITLE
Properties editor - Bones - Bone Collection Overview

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#504]
![image](https://github.com/Bforartists/Manual/assets/35357409/f109131d-82c5-4163-8bc6-9ea32a579046)

They show the visibility and bone collection toggle now.

**Comment by ReinerBforartists** [comment]
What a lousy UX. How do you add back the bone to the bone collection when you accidentally remove it here?

**Comment by ReinerBforartists** [comment]
Fixed. Added as much information as i could evaluate.
