### ISSUE TITLE
NLA - Repeate Last Options - Bake Action has new Channels methods

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#505]
![image](https://github.com/Bforartists/Manual/assets/35357409/b48a3917-69df-408f-9ec5-1a2d2fc2b4a0)

Bake Action operator now can filter channel types.

**Comment by ReinerBforartists** [comment]
This is a 3d view tool from the object menu in object mode.

**Comment by ReinerBforartists** [comment]
Fixed
