### ISSUE TITLE
Document node based tools

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Manual#506]
Node based tools needs documentation

https://docs.blender.org/manual/en/4.0/modeling/geometry_nodes/tools.html

https://projects.blender.org/blender/blender/issues/101778

**Comment by ReinerBforartists** [comment]
Unassigning. This is a job for somebody who actually really uses nodes. I am already lost again to create a node group to randomize some objects at the surface of the base mesh ...

**Comment by Draise14** [comment]
Added it to the Geometry Nodes Header and Tools chapter.
