### ISSUE TITLE
Properties Editor - Armature object - Pose Mode - Bone Tab - Update Sync to Selected operator name

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#508]
<details>
<summary>Details</summary>

SHA-1: cf591606d13f432df4c18b58c235ce222ad8524b

* Anim: change "Sync to Selected" to "Copy Colors to Selected"

"Sync" may imply that things are kept synchronous, while the operator
only performs a one-time copy. The new name & identifier reflect this
better.

</details>

**Comment by ReinerBforartists** [comment]
I guess this issue is fixed since there is a commit?

Closing.

Oh, and could you please assing yourself when you work at an issue? This can make trouble ...
