### ISSUE TITLE
Properties Editor - document new renderer Eevee Next

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Manual#517]
Eevee next has arrived. Needs documentation.

![next](https://github.com/Bforartists/Manual/assets/13919702/328a98b7-1518-4df1-9ea5-60609b578d00)

**Comment by Draise14** [comment]
They also renamed this to "EEVEE" meaning the old EEVEE is now "EEVEE (Legacy)"

**Comment by ReinerBforartists** [comment]
Yeah, super confusing. Since Eevee (next) is not Eevee (legacy). But yeah ...

**Comment by Draise14** [comment]
I think I need to see how we documented Eevee before doing this one. I don't know if the documentation is mixing cycles with eevee or if you seperated them. Seems like a mammoth task, that should have high priority for 4.0.0 release...

**Comment by ReinerBforartists** [comment]
It is separated by tabs and panels in the properties editor as far as i remember, How it looks with eevee, how it looks with cycles ...

And yes, this is quite a task.

**Comment by ReinerBforartists** [comment]
Let's have a look how far i can go here.

**Comment by Draise14** [comment]
Ah. You grabbed it. Good luck! If it's too much, I can take over.

**Comment by ReinerBforartists** [comment]
You sound so sad :D

It's not this much as it looks like. Good amount of copy n paste will help to speed things up :)

**Comment by ReinerBforartists** [comment]
And fixed
