### ISSUE TITLE
New select by attribute operator in VIEW3D_MT_select_edit_mesh

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Manual#521]
New operator in the select menu with mesh in edit mode.  Screenshot and issue follows once i go through the log.

![byattribute](https://github.com/Bforartists/Manual/assets/13919702/4136778b-4df3-4ab4-9a2a-fb45b8dc5b3d)

**Comment by ReinerBforartists** [comment]
Related Edit Mode with mesh object - select menu - new by attribute operator needs icon #3935

![byattribute](https://github.com/Bforartists/Manual/assets/13919702/2b47afcc-7dfe-41f9-9355-755c09edf284)

**Comment by ReinerBforartists** [comment]
I'm lost with documenting this one. How does one add a boolean attribute to where here?

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Manual/assets/35357409/5710c089-7f91-48c9-8f15-423c98e89d07)

Documented.
