### ISSUE TITLE
Document Metal renderer in preferences - Cycles Render Device

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Manual#523]
This is a tough one. We need a mac user who makes a screenshot from the Render devices. Metal is now not longer experimental.

> SHA-1: af629b8c208e06149b5dea448571dc30f1ed4d24
> 
> * Cycles: Remove MetalRT experimental status, and add "auto enable" option
> 
> This PR removes the "experimental" disclaimer from the MetalRT control now that the unit tests all render correctly with it enabled. As well as "Off" and "On", this adds a third "Auto" setting  - a new default which can be used to pick the best option.
> 
> Pull Request: https://projects.blender.org/blender/blender/pulls/114067

![oneapiornot](https://github.com/Bforartists/Manual/assets/13919702/71cfc067-2308-405f-8d3d-9b296a3f4f7a)

**Comment by Blenux** [comment]
Can do this today on my daughter's one.

**Comment by Blenux** [comment]
almost there, the libs take forever to download for us Aussies!

**Comment by ReinerBforartists** [comment]
I feel your pain ^^

**Comment by ReinerBforartists** [comment]
Mh, it should have been enough to simply download BFA. Not necessary to compile here. We just need a screenshot how it looks like at a mac with metal :)

**Comment by Blenux** [comment]
well shiz lol, anyways done.

**Comment by ReinerBforartists** [comment]
Well, we would always be happy about a M2 devbuild :)

**Comment by ReinerBforartists** [comment]
Where's mah screenie :'3

**Comment by Blenux** [comment]
Already in the manual...

<img width="661" alt="image" src="https://github.com/Bforartists/Manual/assets/25260650/f13619ba-1c8b-4ef4-9ec3-dfbecdfbab93">

**Comment by ReinerBforartists** [comment]
Many thanks. Had overlooked it since the issue is still open :)

I found nevertheless a few things to adjust. So we have nevertheless a commit here.
