### ISSUE TITLE
Properties Editor - Object Data Properties - Mesh - Remove Normals panel from the manual

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Manual#524]
Panel is gone. We need to remove it from the manual.

![gone](https://github.com/Bforartists/Manual/assets/13919702/3c0feab9-7051-4e42-9af4-cd2a9bdea4a3)

**Comment by Draise14** [comment]
What? What happened to it?

**Comment by ReinerBforartists** [comment]
Fixed
