### ISSUE TITLE
File - Import/Export - PLY now has Custom Vertex Attributes

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#526]
![image](https://github.com/Bforartists/Manual/assets/35357409/1773d49e-2549-4903-ad3d-d42d28c5be10)
![image](https://github.com/Bforartists/Manual/assets/35357409/fd77f4aa-87e0-4a57-afe2-90fb3326bdae)

Chapter 5.1.1 has this info. 

<details><summary>Details</summary>
<p>

SHA-1: 0eb6aef3b0009fc7fc0c1588097e09df8cf6aaaf

* PLY: import/export custom vertex attributes (#108948)

Implements #108948 - support for custom point domain attributes for PLY
import and export. Notes:

- Custom attributes are always represented as scalar floats. PLY itself
  has some data types that blender can't fully represent, e.g. double or
  uint32, or some that fit into a float just fine but blender does not have
  them as separate types (e.g. int16).
- When importing, any PLY vertex attribute that is not one of "standard"
  names (position, normal, etc.) gets turned into a custom attribute.
- For exporting, more complex custom attributes (e.g. 2D/3D floats,
  quaternions, colors) get turned into several PLY attributes, with "_x"
  like suffix.

Custom attribute import/export is on by default in the UI.

Pull Request: https://projects.blender.org/blender/blender/pulls/114320
Reviewed By: Hans Goudey

</p>
</details>

**Comment by ReinerBforartists** [comment]
Ah this lovely outdated manual where you just would have to fix one line and end in rewriting the whole chapter ...

**Comment by ReinerBforartists** [comment]
Fixed
