### ISSUE TITLE
User Preferences - Animation - New default "keying set" settings

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#531]
![imagen](https://github.com/Bforartists/Manual/assets/35357409/91c1b794-7955-4eb0-92b4-90d0ec8baa37)

New Default Key Channels settings, needs documentation

<details><summary>Details</summary>
<p>

SHA-1: a99e419b6e841d673a3542c372d5faec82c0d138

* Anim: Insert keyframes without keying sets

When animators want to key something in the viewport,
the code needs to know *which properties* should be keyed of that selected thing.
So far that was done with keying sets, and a pop-up that let's
you choose the keying set to use. You can get rid of the popup by
choosing a keying set ahead of time. But that is also not always desirable.

That pop-up is quite confusing and gives way too many options.
To simplify this process this PR adds a User Preference option to choose one or more of:
* Location
* Rotation
* Scale
* Rotation Mode
* Custom Properties

Now whenever the `I` key is pressed in the viewport,
and no keying set is enabled, it reads the preferences for which channels to insert.

# User Facing changes
* The popup will not be shown when pressing the hotkey,
 but you can still explicitly use keying sets by going to the menu
* Which channels are keyed is defined by a User Preference setting under animation
* when a keying set is used explicitly, the User Preference settings are ignored

Part of #113278

Pull Request: https://projects.blender.org/blender/blender/pulls/113504

</p>
</details>

**Comment by ReinerBforartists** [comment]
Fixed
