### ISSUE TITLE
Properties Editor - Materials - EEVEE new displacement panel

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#532]
![imagen](https://github.com/Bforartists/Manual/assets/35357409/be6841c4-1b31-4085-a854-6514b95aa61b)

New panel, new documentation

<details><summary>Details</summary>
<p>

SHA-1: a001cf9f2b08a67aa3b20f1857eac5c915f5ef33

* EEVEE-Next: Displacement Option

This add the displacement option to EEVEE materials.
This unifies the option for Cycles and EEVEE.

The displacement only option is not matching cycles
and not particularly useful. So we decided to not
support it and revert to displacement + bump.

Pull Request: https://projects.blender.org/blender/blender/pulls/113979

</p>
</details>

**Comment by ReinerBforartists** [comment]
Displacement panel is already documented. Nothing to do here ...
