### ISSUE TITLE
Editors - Properties Editor - Render Properties Tab - Split per render engine

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#533]
This chapter is getting quite large, and EEVEE (legacy) and EEVEE are very different. It would be easier to track each render engine if they were their own chapter and to search the chapters for the render engine sub-chapters on the index would make it easier to filter and find depending on the engine. 

Chapter 26.2 to 3 new sub chapters. Common panels would show in the parent chapter possibly.

![imagen](https://github.com/Bforartists/Manual/assets/35357409/6de35b30-8027-4c31-94f3-84ab67e76588)

**Comment by ReinerBforartists** [comment]
Sure, just go ahead :)
