### ISSUE TITLE
NLA Editor - Edit header menu is now "Strip"

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#539]
![bforartists_nAPsMwMN4D](https://github.com/Bforartists/Manual/assets/35357409/8601ae44-b68e-4db7-bbaa-9eef4847d65c)
## Previous 

![bforartists_p0PReF2XSi](https://github.com/Bforartists/Manual/assets/35357409/a6d4e8d5-b1d9-419f-bf5e-507c3d01c81a)
## Now

**Comment by ReinerBforartists** [comment]
Fixed
