### ISSUE TITLE
3D View - Weight Paint Mode - New indicator for bone selection mode to weight paint.

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#540]
![image](https://github.com/Bforartists/Manual/assets/35357409/2ba3d8a0-2618-4668-9a28-2349400dfc41)

A nice addition, now there is an indicator that you're in bone selection mode to weight paint. 

<details><summary>Details</summary>
<p>

SHA-1: edcac1f48b92aee693f01a9bb4d23c03870a8f29

* Fix #44834: Add bone selection icon next to face and vertex selection in weight paint mode

Currently, in weight paint mode, there is an icon for
face and vertex selection mode, but there isn't one
for the default mode where the user can select a bone
in any tool by alt clicking.
This lack of indication might lead to confusion for the users
when they are not able to select a bone by
alt clicking during weight painting.

By adding a bone selection icon when there is a pose
mode armature, we can communicate to the user that:
1. they can select a bone while the bone selection icon is active.
(when they are not in face or vertex selection mode)
2. they have forgot to select an armature when entering
weight paint mode by not showing the bone selection
icon at all when there is no pose mode armature.

When the bone selection icon is inactive,
the user can't select a bone.
(alt clicking selects face and vertex mode's respective element)

When no armature is selected when entering weight paint mode,
the bone selection icon doesn't show up indicating that the user
has forgot to select an armature.
(The user is also unable to select a bone by alt clicking.)

## Selection tool for bone selection mode
Currently, while selection tools exist for face and vertex
selection mode, one doesn't exist for the default mode
(bone selection mode). As the default mode will be getting
a clear indicator that it will function as a bone selection mode,
I added a selection tool entry for the bone selection mode.

Face and vertex selection modes has the shortcut 1 and 2,
so it seemed natural to give bone selection mode the shortcut of 3.

Pull Request: https://projects.blender.org/blender/blender/pulls/115409

</p>
</details>

**Comment by ReinerBforartists** [comment]
:D

Nice indeed. It's not just an indicator. But a button to switch to a mode where you can select the bones for weightpainting. Moar work at the documentation end ^^
