### ISSUE TITLE
General - Edit Mode - Update screen captures for mesh mode face sub-selection wireframe colours

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#541]
![image](https://github.com/Bforartists/Manual/assets/35357409/f1c1621d-1d08-467b-9d41-207df59cff0c)

We updated the face sub-selection wireframe colours to be blue, now that you can while in vertex or edge selection mode in Edit mode. 

It's a big task, so may need some good sample files to do this.

**Comment by ReinerBforartists** [comment]
This is theming dependant, and should not be part of rewriting the manual. The functionality is still given, no matter what colors are used.

So i will close this issue.
