### ISSUE TITLE
Compositor - Split Viewer now is Split node under Utilities

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#544]
![image](https://github.com/Bforartists/Manual/assets/35357409/798be063-754f-45c9-ae19-5dfa6c7af520)

Split viewer now.. a utility with an image out. Needs documentation updated. 
<details><summary>Details</summary>
<p>

SHA-1: 153f14be2b67fba0d3d92eb08eff7659f2dffae7

* Compositor: Make split viewer a regular split node

Changes:
- Renamed Split Viewer Node to Split Node
- Split Node is now under `Utilities` (similar to Switch node)
- Versioning: split viewer from 4.0 and before is replaced with the new split node connected to a new viewer node.

Pull Request: https://projects.blender.org/blender/blender/pulls/114245

</p>
</details>

**Comment by ReinerBforartists** [comment]
Fixed
