### ISSUE TITLE
File Import - OBJ - New Path Seperator prop

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#545]
![image](https://github.com/Bforartists/Manual/assets/35357409/68b10bf9-656d-4db9-8780-36a9742ced8a)

You can now split object name by path seperators into collections when importing. 

<details><summary>Details</summary>
<p>

SHA-1: 19f4f840050eb8952c87a4242f69d3a6b27d9f8a

* OBJ: add import option to create collection hierarchy by splitting names with a separator

Implements #105001 - new import option for name separator, e.g. "|" or "/".
Names found in the OBJ file are split by that, and a Collection hierarchy is
made, so you can have e.g. "o House/Roof/Tile" in the OBJ file.

Pull Request: https://projects.blender.org/blender/blender/pulls/115742

</p>
</details>

**Comment by ReinerBforartists** [comment]
Fixed
