### ISSUE TITLE
3D View - Curves (hair) Object - Edit Mode - Toolshelf New draw tool mode

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#546]
![bforartists_nbgyvFFuQu](https://github.com/Bforartists/Manual/assets/35357409/52b26828-c85f-45ed-9e55-0da8bc8251da)
![bforartists_gxrfFZCkpg](https://github.com/Bforartists/Manual/assets/35357409/9afa25fd-0c8b-452d-90ad-2291b08adb15)

You can now draw hair guide curves from toolshelf.

<details><summary>Details</summary>
<p>

SHA-1: feae0b417395873d72761b5fbe78721b68f12fea

* Curves: Support for edit mode draw tool

Adds new curves support to "Draw Curve" operator. This is a direct copy
and replace of the old code to the new editors directly, with a change to
create the new data structure instead of the old one. There is no attempt
at code deduplication, since that would complicate removing the old
curve type when it comes time.

To replace the "2D curve" option a new operator property is added
for projecting to the Z=0 plane.

Pull Request: https://projects.blender.org/blender/blender/pulls/115864

</p>
</details>

**Comment by ReinerBforartists** [comment]
Fixed
