### ISSUE TITLE
Sequencer - Retiming Operator - Preserve Retiming prop

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#549]
![image](https://github.com/Bforartists/Manual/assets/35357409/9848cdcc-a1ae-429c-a0d8-0b0cfd7b4d20)

Operator Prop, should be documented. 

<details><summary>Details</summary>
<p>

SHA-1: f372ac6f61599807fdd23d6fc70bf17190f431ac

* VSE: Keep exiting retiming when changing speed

Add "Preserve Current Retiming" option to set speed operator. This
option is enabled by default. When changing speed of retiming segment,
the strip changes length instead of changing next segment speed.

Ref: #112343

</p>
</details>

**Comment by ReinerBforartists** [comment]
Can of worms. This document is borked. Every new headline is inserted as a list. Let's have a look if redoing the document will help.

**Comment by ReinerBforartists** [comment]
Pasting it into a blank document did the trick.

Fixed
