### ISSUE TITLE
3D View - Curves Object (fur) - New Tilt operator in Toolshelf

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#551]
![bforartists_kOrNwxCbgS](https://github.com/Bforartists/Manual/assets/35357409/faecab1d-651e-4de4-8c75-42753e45e755)

Same as in the Curve object edit mode. 

<details>
<summary>Details</summary>

SHA-1: 0e8c8741665bf1d4e6a88b3614a3f5185ab34a31

* Curves: Add edit mode tilt control

Adds support for the tilt transform operator and a "Clear Tilt"
operator to mirror the functionality from the legacy curve type.

</details>

**Comment by ReinerBforartists** [comment]
Already fixed with another task
