### ISSUE TITLE
3D View - New string Attribute Text overlay

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#552]
![image](https://github.com/Bforartists/Manual/assets/35357409/cf6e3864-8686-43df-847d-d6009cc4f92e)
New Attribute Text

<details>
<summary>Details</summary>

SHA-1: b85011aee0c1a20062818cc380b2b9e42f2092f8

* Geometry Nodes: initial display of attribute values as text in 3d viewport

Previously, attribute values were only visualized as color overlay in the 3d viewport.
Now it's possible to optionally show the attribute values as text. This can be enabled
in the `Viewer Node` overlay settings in the 3d view.

This is just the first initial version. More work towards making it look better
will be done next.

Pull Request: https://projects.blender.org/blender/blender/pulls/115664

</details>

**Comment by ReinerBforartists** [comment]
Fixed
