### ISSUE TITLE
Sequencer - Overlays - Sound waveform settings improved

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#553]
![image](https://github.com/Bforartists/Manual/assets/35357409/962a7637-003b-4f71-afd3-e28057dfdda7)

With a nice improvement from Blender. 

<details>
<summary>Details</summary>

SHA-1: a95dd8438da1c98d91d3dd892182ebd9acfb3ce4

* VSE: add option to display half of audio waveform

Default is "full" waveform display. Adds overlay option to display absolute
value of the signal as upper half only. Part of design task #115274

Pull Request: https://projects.blender.org/blender/blender/pulls/116344

SHA-1: 4805b4f13fb1c5065c36ae9592b55c8cb1111233

* VSE: more intuitive UI control for waveform display mode

Use a more consistent radio selection for waveform display, not an
enum-radio hybrid. Part of design task at #115274

Pull Request: https://projects.blender.org/blender/blender/pulls/116336

</details>

**Comment by ReinerBforartists** [comment]
Fixed
