### ISSUE TITLE
Properties Editor - Render Tab -  EVEE (next) Raytracing presets

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#556]
![image](https://github.com/Bforartists/Manual/assets/35357409/c0161865-f845-42f0-acd2-f910d6e96a28)

Presets for raytracing is now a thing. 

<details><summary>Details</summary>
<p>

SHA-1: 2bb7d767c4d6bbc9c6128bef33a2caff132b7e99

* EEVEE-Next: Add Raytracing Presets

This PR adds raytracing presets. It contains a preset with default settings and
users are able to add their own.

Pull Request: https://projects.blender.org/blender/blender/pulls/116223

</p>
</details>

**Comment by ReinerBforartists** [comment]
Fixed here: Properties Editor - Render Tab - EEVEE (next) - Raytracing toggle #557
