### ISSUE TITLE
Properties Editor - Render Tab - EEVEE (next) - Raytracing toggle

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#557]
![image](https://github.com/Bforartists/Manual/assets/35357409/4dbb32a9-9cde-4461-8457-4e4c285c07f2)

New raytracing toggle, nice. 

<details>
<summary>Details</summary>

SHA-1: b7a7c2ac00526bd7f53f2554a6c389262816cf5b

* EEVEE-Next: Add lightweight deferred indirect lighting

This adds option to bypass the raytracing pipeline
entirely and use a cheaper evaluation option.

This reuse the same evaluation as the Blended materials.

This exhibits some artifacts on Apple hardware due to
synchronization issues.

Pull Request: https://projects.blender.org/blender/blender/pulls/116622

</details>

**Comment by ReinerBforartists** [comment]
Fixed
