### ISSUE TITLE
NLA - Action Bake now supports Custom Properties.

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#558]
![image](https://github.com/Bforartists/Manual/assets/35357409/12ac3ab6-fc39-4732-a23c-509420dee244)

Yep, as the title says.. Should be documented. 

<details>
<summary>Details</summary>

SHA-1: 4ddb52a775950fe14733f675a4804883a2e4dce3

* Anim: Action bake custom properties

Add custom properties to Action Bake.

objects will bake all animatable custom properties. Armatures will bake all bone custom properties,
as well as object (armature) custom properties.

Pull Request: https://projects.blender.org/blender/blender/pulls/113208

</details>

**Comment by ReinerBforartists** [comment]
Fixed
