### ISSUE TITLE
Document right click menus in the properties editor

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Manual#559]
In the properties editor we have documented the context menu. But we haven't documented all these little right click menus for when you click at an element.

In the 3d view we have documented all these right click menus in the first chapter, and not where they happen. Which would make sense since we avoid too much double entries then. 

Some rmb menus happens to have the same content than in the 3d view. Which might save us some time.

Related: https://github.com/Bforartists/Bforartists/issues/3996

![rmbmenus](https://github.com/Bforartists/Manual/assets/13919702/f9a621a3-7d87-42ee-bd6f-9cfa33cf84df)

**Comment by ReinerBforartists** [comment]
Let's have a look here

**Comment by ReinerBforartists** [comment]
Hmm, cannot find the place anymore where we documented the rmb menus for the 3d view. For the outliner we have documented it in its chapter. But the outliner contains just one chapter. So i am not sure if we should add a right click menu to every chapter. It would make sense though. To document the rmb menus at the place where they happen would produce a lot of double menu entries.

Either way, it makes me unhappy that we don't have the rmb menus documented in a proper way. So let's have a look how this turns out. It's a bigger operation for sure.

**Comment by Draise14** [comment]
The interface chapter talks of the right click menus. I think that's enough... there is no other way to document it per editor without being redundant by logging it's operators... Twice.

Unless we briefly mention it exists in every single editor.... With screen cap... Which would be wild.

**Comment by ReinerBforartists** [comment]
There is unfortunately not this much information int he interface chapter. I see a few ways to improve things here. Let me do some changes :)

**Comment by ReinerBforartists** [comment]
Ah, it is in chapter 6. rmb menus at tools. Okay, this work was more or less for the birds.

**Comment by ReinerBforartists** [comment]
Merged all the relevant rmb menu info in chapter 6 now.
