### ISSUE TITLE
Header - File - Recent Files - New operator Clear Recent Files list

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#561]
![image](https://github.com/Bforartists/Manual/assets/35357409/fa6789e3-6027-42d1-9de6-71343d4c9593)

Icon could be improved.. but it's there now. 

<details>
<summary>Details</summary>

SHA-1: a1bcba0598d77da413747556e883849fa5a8eb50

* UI: Implement a Clear Recent Files List Operator

Add a "Clear Recent Files List" item to the bottom of the File / Open
Recent List.

Pull Request: https://projects.blender.org/blender/blender/pulls/116494

</details>

**Comment by ReinerBforartists** [comment]
Already documented with updating the icon
