### ISSUE TITLE
Sequencer - Scopes updated, update screenshots

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#562]
Sequencer scopes in preview mode have been updated... 
<details>
<summary>Details</summary>

SHA-1: 423e54b00095020610c01a69e72d369b6ee05a90

* VSE: Scopes improvements

- Improve the look of them, so they feel less like from year
  1998 (more details and images in the PR).
- Some of the scopes got slightly faster in the process, others
  stayed the same performance (details below).
- Remove VSE Scopes related data from SpaceSeq DNA, move it into
  runtime instead.

</details>

<details>
<summary>Details</summary>

SHA-1: 5ff0feee52d4af484e9c91443a492c19295f45f9

* VSE: tweak look of Vectorscope to match upcoming Image vectorscope

Image vectorscope is getting some visual updates (#116974), here make the
Sequencer vectorscope match the look fairly closely:

- Use same scaling factor for both U & V, instead of trying to use all
  the texture space.
- Instead of drawing hexagonal area between color primary "pure" and
  "75% saturation safe" points, draw a circle with colored background
  and five inner rings.
- Indicate "75% saturation primaries" as wire rectangles with a text label.

Images in PR.

Pull Request: https://projects.blender.org/blender/blender/pulls/117738

</details>

**Comment by ReinerBforartists** [comment]
I cannot find any scopes in the VSE. Not in Blender, not in BFA. Do you have an idea where it hides?

![noscopes](https://github.com/Bforartists/Manual/assets/13919702/f92f21f7-1016-4ba9-87d6-a78f0c94f6ac)

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Manual/assets/35357409/0e4f52ed-9f02-4260-b7b8-d84227f06b93)

They are in the preview view, top right then you can swap the image to another scope.. not like the Image Editor because Blender is consistently inconsistent.

**Comment by ReinerBforartists** [comment]
Found it. But still don't want to fix this :D

**Comment by ReinerBforartists** [comment]
Fixed
