### ISSUE TITLE
Sequencer - Transform Effect Strip - New Bicubic Interpolation method

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#564]
![image](https://github.com/Bforartists/Manual/assets/35357409/38c345c9-21c6-4aa6-9b88-3e6588e8fc90)

Document the new option. 

<details>
<summary>Details</summary>

SHA-1: 709b00179f34e8ac4c272a2e1d7d40a8328f9704

* VSE: add Bicubic filtering option, and optimize bicubic performance

Part of overall "improve filtering situation" (#116980) task:

* Add Bicubic filtering option to strip Transform "Filter" setting.
Previously this option only existed in Transform Effect "Interpolation"
setting.
  - With this addition, it feels like the transform effect could
    possibly be marked as legacy/deprecated, since the regular Transform
    that is on all strips can do everything that Transform Effect did?
* Speed up bicubic filtering (used now in VSE, but also in CPU Compositor,
  image paint, etc.) by slightly simplifying the code and using some SIMD.
  Upscaling 96x54 image to 3840x2160 resolution, using Bicubic filtering:
  - Windows (VS2022, Ryzen 5950X): 35.5ms -> 15.1ms
  - Mac (clang 15, M1 Max): 29.6ms -> 24.4ms
* Add gtest coverage for bicubic functionality.

Pull Request: https://projects.blender.org/blender/blender/pulls/117100

</details>

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Manual/assets/35357409/8fa4d72e-eda1-469a-abce-2d67fdf1ee32)

This has another update. 

- New  Cubic Mitchell filtering 
- Bilinear is now Cubic BSpline
-
<details>
<summary>Details</summary>

SHA-1: b7cf71d567996fc7bbd6be719d3e0dba08d4b9f2

* VSE: add Cubic Mitchell filtering, rename previous cubic to Cubic BSpline

Part of overall "improve filtering situation" (#116980) task:

Add "Cubic Mitchell" filtering option to VSE strips. This is a cubic (4x4)
filter that generally looks better than bilinear, while not blurring the image
as much as the Cubic BSpline filter that exists elsewhere within Blender. It is
also default in many other apps.

Rename the (very recently added) VSE Bicubic filter option to Cubic BSpline.

Images in the PR.

Pull Request: https://projects.blender.org/blender/blender/pulls/117517


</details>

**Comment by ReinerBforartists** [comment]
This task is confusing. 

Part 1 is no issue, the dropdown box still shows just two options Bilinear and Bicubic, which are already documented.

Part 2 should be its own issue, and has nothing to do with this task.

**Comment by ReinerBforartists** [comment]
Closing this one, and splitting the second part away.
