### ISSUE TITLE
Properties Editor - Mesh Data Tab - Shape keys can now lock and unlock (with new operators)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#566]
![image](https://github.com/Bforartists/Manual/assets/35357409/31830ecb-37c8-4b32-820a-bb6738ceca99)

Locking is nice. Now possible with Shape Keys. 

<details>
<summary>Details</summary>

SHA-1: b350d7a4c311ec6a3065ac89febafc3ba6bd43a2

* Shape Keys: support locking to protect from accidental editing.

It is very common for graphical editors with layers to support
locking individual layers to protect them from accidental edits due
to misclicks. Blender itself already supports locking vertex groups.
This adds lock toggles for shape keys, with lock/unlock all operators.

The flags are checked by sculpt brushes, edit mode transform tools,
and Smooth, Propagate and Blend From Shape operators. This selection
aims to cover operations that only deform the mesh, where the shape
key selection matters.

Topology changing operations always apply to all keys, and thus
incorrect shape key selection is less impactful. Excluding them
from the new feature greatly reduces the patch size.

Pull Request: https://projects.blender.org/blender/blender/pulls/104463

</details>

**Comment by ReinerBforartists** [comment]
Fixed
