### ISSUE TITLE
Compositor - Map UV node has new Nearest sampling mode

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#567]
![image](https://github.com/Bforartists/Manual/assets/35357409/1821c2ec-9084-4826-a736-c092000a82f1)

New method. 

<details>
<summary>Details</summary>

SHA-1: a3b7674c6ef9490bb80bcea6802cb51ee3e0b825

* Compositor: Add a Nearest sampling to Map UV node

When using the MapUV node for certain NPR workflows (for example palette
based remapping of colors) it can be useful to not use the default
anisotropic filtering.

In preparation of potentially adding more filter modes at a later stage
and to keep things consistent with the 'transform' node we use the full
set of interpolation modes in the enum, but expose only the implemented
ones in RNA..

</details>

**Comment by ReinerBforartists** [comment]
Fixed
