### ISSUE TITLE
Properties Editor - Armatuer - Bone Collections - "Solo" column added

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#569]
![bforartists_c0yAlR6e8J](https://github.com/Bforartists/Manual/assets/35357409/56e1525b-5936-496c-9d5b-f30d1eef10f8)

Kinda nice, you can now solo. 

<details>
<summary>Details</summary>

SHA-1: a7f41fc938246589aec879741466fa9bd14bcaca

* Anim: bone collections, add 'solo' flag

Add the 'solo' flag to bone collections, effectively adding another
layer of visibility controls.

If there is _any_ bone collection with this flag enabled, only this
collection (and others with this flag enabled) will be visible.

In RNA, the following properties are exposed:
- `bone_collection.is_solo`: writable property to manage the solo flag.
- `armature.is_solo_active`: read-only property that is `True` when any
  bone collection has `is_solo = True`.

The RNA property `bone_collection.is_visible_effectively` now also takes
the solo flag into account.

Pull Request: https://projects.blender.org/blender/blender/pulls/117414

</details>

**Comment by ReinerBforartists** [comment]
Solo was already documented. But there was an outdated image.
