### ISSUE TITLE
Image Editor - Vector Scopes improves

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#572]
![image](https://github.com/Bforartists/Manual/assets/35357409/28245837-47da-4e6e-a17b-d9521737e3db)

Update thumbs
<details>
<summary>Details</summary>

SHA-1: 567455124d6161cea3b157c1628ceb20c128bec3

* UI: Image Editor Vectorscope Improvement

Update the look of image editor Vectorscope widget (design #116973):
- Colored and Luma options for the point cloud,
- The circles are no longer very low poly,
- Overall grid/background colors are tuned.
- Primary color locations have text labels.

Images in the PR.

Pull Request: https://projects.blender.org/blender/blender/pulls/116974

</details>

**Comment by ReinerBforartists** [comment]
Related: Seqeucner - Scopes updated, update screenshots #562

**Comment by ReinerBforartists** [comment]
Fixed
