### ISSUE TITLE
Graph Editor - Options - New Auto Lock Translation Axis property

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#573]
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/f130862e-dc6c-4a84-b492-2e68c6db06a2)

New property added to blender, should be exposed to the option drop down of the graph editor

`layout.prop(st, "autolock_translation_axis")`

![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/9a3ab3b4-61f1-4a9b-af8b-a3134b2f324a)

<details>
<summary>Details</summary>

SHA-1: 446b92d2cecab1caa6c7aa1b63ae822461b9144b

* Anim: Graph Editor - automatically lock key translation to a single axis

When moving keys in the Graph Editor animators
usually only want to move them on one axis.
While this is possible in a few ways (G+X, or G + Middle Mouse Button click),
we could default the behavior to always lock on an axis.
This was suggested by Dreamworks animators during the
Animation & Rigging module meeting.
https://devtalk.blender.org/t/2024-01-26-animation-rigging-module-meeting/33081#patch-review-decision-time-5

This PR adds an option with which the movement is
always locked to a single axis by default.
The option can be found in the Graph Editor under "View->Auto-Lock Axis".

The movement will then be restricted to the axis along
which you've moved the cursor the most.
You can still manually override the lock behavior by pressing `X` or `Y`.

I am piggybacking off the auto locking feature you get when pressing the middle mouse button.
When the new feature is enabled I call that at the start of the transformation.
Except when:
* only handles are selected
* the tweak mode has been started on a handle

This is to not snap handles, which is a behavior that has
been requested by the artists.

Pull Request: https://projects.blender.org/blender/blender/pulls/117669

</details>

**Comment by ReinerBforartists** [comment]
>New property added to blender, should be exposed to the option drop down of the graph editor

Wrong tracker?

**Comment by ReinerBforartists** [comment]
I can just assume that you mean the new Auto Lock Key Axis. So in this regards the issue is fixed.


![fixed](https://github.com/Bforartists/Manual/assets/13919702/316d90b6-e9b5-48ac-a03d-a322f2f6b97b)
