### ISSUE TITLE
3D View - Object Edit Mode - Spin Duplicate removed

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#574]
It's gone now. Remove from documetnation. Has a new prop in the repeat last. 

> So expose the property in tool settings and remove the spin duplicate tool

<details>
<summary>Details</summary>

SHA-1: 8250502b7738f2bf109ce98eba6f2d53ff6b4620

* UI: Merge Spin and spin duplicate tools

Both tools calls the same operator, only difference is "dupli" bool
property value. So expose the property in tool settings and remove the
spin duplicate tool

Resolves #98094

Pull Request: https://projects.blender.org/blender/blender/pulls/117880

</details>

**Comment by ReinerBforartists** [comment]
Fixed
