### ISSUE TITLE
Geometry Nodes - Smaple Nearest Surface has Group ID now

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#575]
![imagen](https://github.com/Bforartists/Manual/assets/35357409/b581ad49-fefd-4fae-8ad9-deb9fc1ccd32)

> Three new sockets are added:
> * `Group ID`: Is evaluated on the face domain and splits the input mesh into  multiple
>   parts, each with its own id.
> * `Sample Group ID`: Determines in which group the closest nearest surface is detected.
> * `Is Valid`: Outputs true if a nearest surface was found, it's false if the group is empty.

<details>
<summary>Details</summary>

SHA-1: 75e9056cac24d319bd5bb65dd13115ddad9074a9

* Geometry Nodes: support group ids in Sample Nearest Surface node

This adds group ids to the `Sample Nearest Surface` node. This allows e.g. finding
the closest point on a specific mesh island.

Three new sockets are added:
* `Group ID`: Is evaluated on the face domain and splits the input mesh into  multiple
  parts, each with its own id.
* `Sample Group ID`: Determines in which group the closest nearest surface is detected.
* `Is Valid`: Outputs true if a nearest surface was found, it's false if the group is empty.

Pull Request: https://projects.blender.org/blender/blender/pulls/118150

</details>

**Comment by ReinerBforartists** [comment]
Related

https://github.com/Bforartists/Manual/issues/578

Grab text from here ...

**Comment by ReinerBforartists** [comment]
Fixed
