### ISSUE TITLE
Properties Editor - AVI JPEG and AVI RAW removed

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#577]
![image](https://github.com/Bforartists/Manual/assets/35357409/cad201ea-2569-4c6e-ab18-151930a1c405)

It's now all in FFMPEG, so redundant and slow code is removed. Nice cleanup. 

<details>
<summary>Details</summary>

SHA-1: f09c7dc4ba5865b82f4e9a030944e07905bda3ba

* Video: Remove non-ffmpeg AVI support

Blender had a very limited (only uncompressed or MJPEG frames) .avi file
support, for both reading and writing. This is something that ffmpeg can
fully do.

This removes all of that. 3500 lines of code gone, primary motivations being:
- ffmpeg can read and write .avi files just fine, including ones with
  uncompressed or MJPEG frames.
- Blender's ffmpeg integration could also be taught to produce uncompressed or
  MJPEG .avi files, but TBH I don't see a particular reason to do that. Modern
  formats like H264 are better in every way, and already support "lossless"
  option if needed.
- The "Lite" blender build configuration was excluding both ffmpeg and avi
  anyway, so that config is something that can't read nor write any movies.

User visible changes:

- In scene image output type, under Video section now there's only Ffmpeg Video
  (AVI Raw and AVI JPEG are gone)
- Whenever loading an existing file, if output was one of AVI Raw / AVI JPEG,
  it is set to Ffmpeg Video.

Pull Request: https://projects.blender.org/blender/blender/pulls/118409

</details>

**Comment by ReinerBforartists** [comment]
Fixed
