### ISSUE TITLE
Geometry Nodes - Geometry Proximity has Group ID now

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#578]
![image](https://github.com/Bforartists/Manual/assets/35357409/5accad94-6aad-4b73-8aa6-96016be29c51)

<details>
<summary>Details</summary>

SHA-1: 0494605e7e422ad0980b35e4cc5f3703c02982ea

* Geometry Nodes: support group ids in Geometry Proximity node

This is the same 75e9056cac but for the Geometry Proximity node.

Pull Request: https://projects.blender.org/blender/blender/pulls/118467

</details>

**Comment by ReinerBforartists** [comment]
Fixed
