### ISSUE TITLE
Properties Editor - Geometry Nodes add button now copies like in Materials UX

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#579]
![image](https://github.com/Bforartists/Manual/assets/35357409/81c75860-4d60-47ea-b49c-9ce555867f9c)
> Now it behaves the same as the materials list UI.
<details>
<summary>Details</summary>

SHA-1: fcc8a11370deae2d465581f16a43f5fc45c6e4f1

* Fix #118395: use copy instead of new for geometry nodes in modifiers list

Now it behaves the same as the materials list UI.

Pull Request: https://projects.blender.org/blender/blender/pulls/118420

</details>

**Comment by ReinerBforartists** [comment]
Shouldn't an add button add instead of copy? O_O

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Manual/assets/35357409/cdbd4c41-da27-4b9c-bb08-d559cebc29e8)

In the materials and others, after you make a new material, the plus sign then duplicates... I will make a new task to update the icon to be duplicate after making new. New is only made if the socket is empty. But meanwhile I have clarified it in the documentation.

**Comment by Draise14** [comment]
Made the relevant task:
#4367
