### ISSUE TITLE
Outliner - Orphan Data now Unused Data

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#580]
![image](https://github.com/Bforartists/Manual/assets/35357409/0cca36f4-50af-465a-8a47-ced8901b5f67)

Someone finally got rid of all the orphans. 

<details>
<summary>Details</summary>

SHA-1: 72be662af4b941d0d987e0282af8c9785650d23e

* UI: Change UI Name of Outliner "Orphan Data" mode to "Unused Data"

Change of name and tooltip for Outliner display mode "Orphan Data" to
"Unused Data"

Pull Request: https://projects.blender.org/blender/blender/pulls/118758

</details>

**Comment by ReinerBforartists** [comment]
Fixed
