### ISSUE TITLE
3D View + Image Editor - New Rotation Increments in Snapping mode 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#582]
![image](https://github.com/Bforartists/Manual/assets/35357409/6e60fd82-9bfd-408e-8ba7-e3836315080e)

![image](https://github.com/Bforartists/Manual/assets/35357409/8bc53201-7231-4821-8243-1719c961a06e)

> Add two snapping increment options: a regular value
(activated with Ctrl) and a precise value (activated with Ctrl+Shift).
These values are separate for 2D and 3D views.

<details>
<summary>Details</summary>

SHA-1: 060174cf149c2b05ce09a0dfed33005f1fe15c28

* Transform: customizable rotation snap increment values

Add two snapping increment options: a regular value
(activated with Ctrl) and a precise value (activated with Ctrl+Shift).
These values are separate for 2D and 3D views.

Ref !118760

</details>

**Comment by ReinerBforartists** [comment]
Fixed
