### ISSUE TITLE
Composiitor - New Bloom mode for the Glare node. 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#583]
![image](https://github.com/Bforartists/Manual/assets/35357409/b4cda0d4-d1bc-4955-8308-bd3d131e0226)

New bloom, prepping for EEVEE Next I guess. 

<details>
<summary>Details</summary>

SHA-1: f4f22b64ebfc99579d8b14bace9b2edaae6ec9a4

* Compositor: Add Bloom option to Glare node

This patch implements the GPU Bloom glare for the CPU compositor, and
adds a new option for it, leaving the Fog Glow option unimplemented once
again for the GPU compositor.

Pull Request: https://projects.blender.org/blender/blender/pulls/119128

</details>

**Comment by ReinerBforartists** [comment]
Fixed
