### ISSUE TITLE
3D View - Sculpt Mode - Sculpt - Show/Hide menu needs an update

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#584]
![image](https://github.com/Bforartists/Manual/assets/35357409/2a856c61-2242-436c-9bfe-bb1e26cbe72b)

Found some inconsistencies here, so may need an update.

**Comment by ReinerBforartists** [comment]
First fix the inconsistencies.

Related: https://github.com/Bforartists/Bforartists/issues/4153
