### ISSUE TITLE
Properties Editor - EEVEE Next - Render Tab - Performance - Viewport Pixel Size

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#585]
![image](https://github.com/Bforartists/Manual/assets/35357409/0175314c-c040-4cae-b467-5bcf84c1a3d6)

New viewport pixel sampling for EEVEE next
<details>
<summary>Details</summary>

SHA-1: f0f911590e08c1a223c306b76b4f52b44c41bb5c

* EEVEE-Next: Viewport pixel size with up-sampling

EEVEE-Next performes less on integrated GPUs then discrete GPUs.
Most shaders have been analyzed, but there will always be bottlenecks
related to architectural differences.

In order to make EEVEE-Next run smooth on integrated GPUs this change
will implement viewport pixel size option similar to Cycles. The main difference
is that the samples will still be weighted and up-sampled to the final film
resolution. This makes the pixels not look squared in the viewport but will
resolve to something close to the results without up-scaling.

This improves the performance especially on integrated GPUs. The improvement
for discrete GPUs are less noticeable. See here the stats when playing
`rain_restaurant.blend` back on a RAPHAEL_MENDOCINO iGPU.

| Pixel size | Frames per second |
|------------|-------------------|
| 1x         | 0.25 FPS          |
| 2x         | 4.14 FPS          |
| 4x         | 6.90 FPS          |
| 8x         | 9.95 FPS          |

Related to: #114597
See PR for some example images.

Pull Request: https://projects.blender.org/blender/blender/pulls/118903

</details>

**Comment by ReinerBforartists** [comment]
Fixed.

I have renamed the two chapters too. The new eevee is now eevee-next. And the old eevee is not longer labeled as legacy ...
