### ISSUE TITLE
Preferences - Interface - Language - some updates

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#586]
![image](https://github.com/Bforartists/Manual/assets/35357409/89f739e3-b722-4918-9cf0-a5ec6c4e66c5)

Some label changes
> Change Preferences panel "Translation" to "Language" and replace
"Affect" with "Translate".

<details>
<summary>Details</summary>

SHA-1: 73d76d436018e8f698688f636d0327cdfb91d52e

* UI: User Prefs Language Section

Change Preferences panel "Translation" to "Language" and replace
"Affect" with "Translate".

Pull Request: https://projects.blender.org/blender/blender/pulls/119430

</details>

**Comment by ReinerBforartists** [comment]
Shouldn't the stuff under the Translate label be indent?

I'll make a task
