### ISSUE TITLE
Properties Editor - Color Management - new Khronos PBR Nuetral tone mapper

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#588]
![image](https://github.com/Bforartists/Manual/assets/35357409/ab697c78-00b1-4a51-9b88-74cfc2fa04ed)
New Kronos PBR Nuertal tonemapper for Color Management

<details><summary>Details</summary>
<p>

SHA-1: d1cbb10d17d4965cfd93d048be6954af3e94d557

* Add Khronos PBR Neutral tone mapper

A tone mapper designed specifically for PBR color accuracy, to get sRGB
colors in the output render that match as faithfully as possible the input
sRGB baseColor under gray-scale lighting. This is aimed toward product
photography use cases, where the scene is well-exposed and HDR color values
are mostly restricted to small specular highlights.

Fixes #118824: Proposal: add a view transform for Khronos PBR Neutral Tone Mapper

Co-authored-by: Emmett Lalish <elalish@google.com>
Pull Request: https://projects.blender.org/blender/blender/pulls/118936

</p>
</details>

**Comment by ReinerBforartists** [comment]
Fixed
