### ISSUE TITLE
Graph Editor - Ease operator has new "sharpness" in Last Operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#589]
![image](https://github.com/Bforartists/Manual/assets/35357409/cc889782-3164-421a-a119-4f3aef9fe83c)

> This PR extends the existing `Ease` operator with a sharpness property.
<details>
<summary>Details</summary>

SHA-1: 62f140e048ad06d89d3bf89bb17783ca813a86a6

* Anim: Add Sharpness to Ease operator

This PR extends the existing `Ease` operator with a sharpness property.

This means it has two parameters:
* Curve Bend: Define which key to favor. At 0 it's exactly between the two keys.
* Sharpness: Higher values make the change more abrupt.

During modal operation it is possible to switch the slider between those two by pressing `TAB`.

Pull Request: https://projects.blender.org/blender/blender/pulls/117287

</details>

**Comment by ReinerBforartists** [comment]
Fixed
