### ISSUE TITLE
Splashscreen Text Updates

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#594]
![bforartists_utJrxxHwfn](https://github.com/Bforartists/Manual/assets/35357409/fb21e13a-6e48-40e6-8ec6-f86249ab88ba)

Start splashscreen has some changed text
- Settings to preferences
- Keymap is now "Shortcuts"

<details>
<summary>Details</summary>

SHA-1: d2d810f11a8446e8fdefdf3f5d396f88d65c2520

* UI: Splash Screen Import Changes

Removal of "What's New" button, addition of a section divider, and many
very small changes to the text, some reordering of items.

Pull Request: https://projects.blender.org/blender/blender/pulls/118224

</details>

**Comment by ReinerBforartists** [comment]
Fixed
