### ISSUE TITLE
3D View - Curves Object - Edit Mode - New Add menu

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#595]
![image](https://github.com/Bforartists/Manual/assets/35357409/6b8c49d7-1580-4482-a7bd-8ed3d6652b67)

New add menu, two new curves you can add. 

<details>
<summary>Details</summary>

SHA-1: 549d02637af6844dca697b068f4aad8c6358263d

* Curves: add menu to add some primitive curves in edit mode

This adds operators to add a bezier and circle primitive in curves
edit mode. The operators support the same settings as in the
legacy curve edit mode. The `shift+A` shortcut is added as well.

Pull Request: https://projects.blender.org/blender/blender/pulls/120513

</details>

**Comment by ReinerBforartists** [comment]
This is already in general covered in chapter 7.1.7 Editors - 3D Viewport - Header - Edit mode - Add menu

We could add one more screenshot to it. But the current description is clear enough. So closing this task.
