### ISSUE TITLE
Geometry Nodes - Curve to Points node now uses a rotation socket.

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#596]
![image](https://github.com/Bforartists/Manual/assets/35357409/445558ca-4e24-4f2b-b6f6-1c29eb709b66)
Update screenshot

<details>
<summary>Details</summary>

SHA-1: 248dafef74becf3f9176a5e93bf6d74dbbe2f88d

* Geometry Nodes: use rotation socket in Curve to Points node

Looks like this was forgotten before. Other similar sockets have been converted already.

Pull Request: https://projects.blender.org/blender/blender/pulls/120526

</details>

**Comment by ReinerBforartists** [comment]
There was nothing to fix here. Manual was already up to date. The change was most probably something under the hood.

However, the formatting of this chapter was damaged. A headline with size 5 always ended in a list content. And it did not help to remove the list. So i copied over the whole content into a new document.

This is not the first time that i have seen this. Libre Office ...

![list](https://github.com/Bforartists/Manual/assets/13919702/27530974-9b0a-4a3b-9001-01edf5150d18)
