### ISSUE TITLE
Image Editor - Asset Shelf added

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#599]
![image](https://github.com/Bforartists/Manual/assets/35357409/82333ce2-4bd8-4174-ad7a-c674d5fe6119)

Asset shelf is added, toggle is there but still not usable.... Should mention it. 

<details>
<summary>Details</summary>

SHA-1: c60a1006e571945640c517a378b3bbb54b8b84bc

* Asset Shelf: Add asset shelf region to image editor

As part of the brush assets project, the image editor needs an asset
shelf to display brush assets for texture paint mode. This commit adds
the unused asset shelf region, similar to the 3D viewport's region that
is currently just used for the pose library. For now, users will just
see an "Asset Shelf" toggle in the view menu.

Pull Request: https://projects.blender.org/blender/blender/pulls/121034

</details>

**Comment by ReinerBforartists** [comment]
Anyways, let's document it

**Comment by ReinerBforartists** [comment]
Done
