### ISSUE TITLE
Properties Editor - EEVEE Next - Materials - Thickness Panel

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#602]
![image](https://github.com/Bforartists/Manual/assets/35357409/a7c063c9-c367-4fa8-99d7-454cafddf128)

New thickness panel for EEVEE Next (and Cycles?)

Tasks
- Check if this panel is in cycles, then copy over to EEVEE-Next

<details>
<summary>Details</summary>

SHA-1: 918f87e9e621487465a0d48e3758ebfd221114b1

* EEVEE-Next: Material: Add thickness nodetree panel

This allows for simple modifications without openning
a node editor.

</details>

**Comment by ReinerBforartists** [comment]
We don't have this part documented. Since this all is shader nodes under the hood. So what is to document is the change in the material output node

**Comment by ReinerBforartists** [comment]
Not documented yet. I made an educational guess here. Hope it fits ...
