### ISSUE TITLE
Remove Eevee (Legacy) from manual

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#605]
![image](https://github.com/Bforartists/Manual/assets/35357409/74f0ad42-db80-4061-830c-b09ba4d31476)

Chapter titles and naming is now updating for 4.2.0

<details>
<summary>Details</summary>

SHA-1: 7859e0f606de6679f34892dc4a2c7760ff816f4b

* EEVEE-Next: Rename engines and set it default in startup file

Finally.

Pull Request: https://projects.blender.org/blender/blender/pulls/121592

</details>

**Comment by ReinerBforartists** [comment]
Done.
