### ISSUE TITLE
EEVEE Next - Shadows now moved to Sampling Panel (and remove Soft Shadow)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#606]
![image](https://github.com/Bforartists/Manual/assets/35357409/0e22bd49-d54f-4856-a9bc-714783a01385)
Now it's a sub-panel in sampling, and the soft shadow factor is removed. 

<details>
<summary>Details</summary>

SHA-1: 826d2ed4ecc553a8ef5365946a7da11133092b9b

* EEVEE-Next: Move shadow resolution scale to the sampling panel

</details>

<details>
<summary>Details</summary>

SHA-1: d9915b86a6da2241da43e4a947406c413b9e4188

* EEVEE-Next: Remove shadow softness factor parameter

This parameter was introduced to mitigate shadow tracing
artifacts. These are no longer present since #121317 and
leaving this parameter breaks PBR rules which opens other
issues with shadow disconnected from shading.

</details>

**Comment by ReinerBforartists** [comment]
Fixed with rewrite of chapter for issue [EEVEE-Next - Properties - Expose Fast GI ray and step count and other options](https://github.com/Bforartists/Manual/issues/627#top)
#627
