### ISSUE TITLE
EEVEE (Legacy) Properties Editor - Lights - Light Influence is now a sub-tab

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#611]
![image](https://github.com/Bforartists/Manual/assets/35357409/dbaf7fb7-2884-41df-abb7-14a6af1926b0)

Time to update. 

<details>
<summary>Details</summary>

SHA-1: 504c233d19609b6a5cfe86b03e382e08cfc5613e

* Fix #121485: Add EEVEE legacy in light influence panel

While options are moved in 0c50ec866f5, these influence values are not
assigned to EEVEE legacy in the influence panel, now fixed.

Pull Request: https://projects.blender.org/blender/blender/pulls/121510

</details>

**Comment by ReinerBforartists** [comment]
Legacy is gone. Task has become invalid.
