### ISSUE TITLE
3D View - Shade Auto Smooth operator updates

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#615]
![image](https://github.com/Bforartists/Manual/assets/35357409/05b8eaca-cee3-4f64-9cb3-9188e8cd9953)

No-longer and act-once destructive operator but it adds the node groups and pins to bottom of stack. Documentation should update. Glad they did this. Many users weren't big fans. 

<details>
<summary>Details</summary>

SHA-1: 2f289857afa8ebeaa8d81c9e7e12f15af4b6ea3a

* Object: add Shade Auto Smooth operator

Based on the design in #120230.
* Replaces the `Shade Smooth by Angle` operator with `Shade Auto Smooth`
  in the object context menu menu.
* The new operator automatically adds and removes the modifier instead
  of being a destructive operation.
* The `Shade Smooth` and `Shade Flat` operators now remove the
  `Smooth by Angle` modifier automatically.
* Add a pin option to modifiers, which limits dragging and keeps the
  modifier after newly added modifiers in the list.

Co-authored-by: Hans Goudey <hans@blender.org>
Pull Request: https://projects.blender.org/blender/blender/pulls/121494

</details>

**Comment by ReinerBforartists** [comment]
fixed
