### ISSUE TITLE
Nodegroups - Sidebar - Group - New color tag

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#616]
![image](https://github.com/Bforartists/Manual/assets/35357409/8e626d6d-c004-43db-acb9-a95bfd1007eb)
New colour tag for node groups, you can make them "be" any other kind of nodegroup. 

<details>
<summary>Details</summary>

SHA-1: f4b9ca758a10dbc295f608f1a56c97397c8dd884

* Nodes: add color tag to node groups

This allows setting a color tag for node groups which affects the header
color of group nodes. With this, node groups can look even more similar
to built-in nodes. The only remaining difference is the node group icon in
the node header.

Blender has quite a few different built-in color tags. Most of those are
exposed with very few exceptions. For example, the layout, interface
and pattern categories are not exposed because they are only for built-in
nodes or are not used anymore.

It's generally agreed upon that the set of different color tags is likely too
large. Some differences between color make more sense in some contexts
than in others. In the interest of consistency, it was decided to expose all
these categories anyway. If we ever decide to consolidate them, the worst
that can happen is that a group looses it's category, which wouldn't be too bad.

Pull Request: https://projects.blender.org/blender/blender/pulls/121385

</details>

**Comment by ReinerBforartists** [comment]
This setting changes nothing. No idea how this is meant to work.

**Comment by Draise14** [comment]
Whole chapter is out of date, so updating.
