### ISSUE TITLE
Geometry Nodes - Input - Scene - Object Info has a transform socket now

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#617]
![image](https://github.com/Bforartists/Manual/assets/35357409/add70179-8bba-4342-a257-74fa3d3f2b31)

New socket! A matrix one. 

<details>
<summary>Details</summary>

SHA-1: 4dfc1ede5836fff732e5d29be121fce4c3a7b8db

* Geometry Nodes: output transform matrix from object info node

This adds a new `Transform` output socket of matrix type to the Object Info node.

This is clearly useful, but we did not do this before for a couple of reasons:
* It's redundant with the location, rotation and scale outputs.
* We might want separate `Object Transform` and `Object Geometry` nodes.

For now just adding the socket is probably useful enough to justify it. Even more
so because it's addition doesn't really block other designs in the future either.

Pull Request: https://projects.blender.org/blender/blender/pulls/121437

</details>

**Comment by ReinerBforartists** [comment]
Fixed
