### ISSUE TITLE
Geometry Nodes - Geometry - Operations - Transform Geometry now supports Matrix mode

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#618]
![image](https://github.com/Bforartists/Manual/assets/35357409/5eab9c0a-cf81-45f9-91f5-dd0facafe466)

New mode. 

<details>
<summary>Details</summary>

SHA-1: 9fcf97d9784f9a08fa0a66ca41a20382e92b6270

* Geometry Nodes: support matrix in Transform Geometry node

Now the Transform Geometry node either has individual components (location,
rotation and scale) or a matrix as input. In many cases that is just more
convenient when working with matrices. Often this is identical to splitting
the matrix into it's individual components. However, if the matrix contains
shearing, information is lost when splitting it into individual components.

Pull Request: https://projects.blender.org/blender/blender/pulls/121438

</details>

**Comment by ReinerBforartists** [comment]
Fixed
