### ISSUE TITLE
Properties Editor - Cycles Denoising - Open Image Denoiser Quality 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#619]
![image](https://github.com/Bforartists/Manual/assets/35357409/d5ff1fbf-f9ae-42da-856c-13c73acd5440)

New quality selector should be documented. 

<details>
<summary>Details</summary>

Cycles: Add OpenImageDenoise quality option

This adds a new "Quality" option for OIDN to switch between the existing
"High" and "Balanced" modes and the new "Fast" mode introduced in OIDN 2.3.

Pull Request: [#121374](https://projects.blender.org/blender/blender/pulls/121374)

</details>

**Comment by ReinerBforartists** [comment]
Fixed
