### ISSUE TITLE
Asset Browser - Pose Asset Context Menu - New Blend Pose Flipped operator exposed

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#621]
![bforartists_mpNAfwioX1](https://github.com/Bforartists/Manual/assets/35357409/4172f04d-3899-4bcd-a01c-bc185fc1966e)

Now exposed, nice one Blender. 

<details>
<summary>Details</summary>

![image](https://github.com/Bforartists/Manual/assets/35357409/b0976de2-5a8f-4fed-b494-49363ef21aa9)

</details>

**Comment by ReinerBforartists** [comment]
I can't find it :(

**Comment by ReinerBforartists** [comment]
The whole asset manager remains a big mess. I guess i have to insert the armature as a pose. But how do i? All i can find is to insert it as an asset. And then we just have this asset menu here: 

![asset](https://github.com/Bforartists/Manual/assets/13919702/e0c85125-8771-446c-9bb3-c2ff062ca57c)

**Comment by ReinerBforartists** [comment]
Unassigning.

**Comment by Draise14** [comment]
Clarified how to make a pose asset in relevante section. Operator was documented.
