### ISSUE TITLE
EEVEE-Next - Properties - Light - Shadow Resolution Scale removed

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#624]
Might not have been documented, but shouldn't be there just in case. 
<details>
<summary>Details</summary>

SHA-1: 9f2f1a5c578e0c4f4b34e70467800d762a93df48

* EEVEE-Next: Shadow: Remove per light resolution scale

The reasonning is that we already have a resolution limit
slider per light.

The global shadow resolution scale is usefull as a quick
speedup option to reduce shadow cost for viewport regular
work or for quick rendering. For final render, the per
light resolution limit is more suited  than a LOD scale
since it doesn't modify the filtering of based on distance
from the camera.

This feature is really not hard to add back if there is
a compelling use case for it.

</details>

**Comment by ReinerBforartists** [comment]
Fixed with rewrite of chapter for issue [EEVEE-Next - Properties - Expose Fast GI ray and step count and other options](https://github.com/Bforartists/Manual/issues/627#top)
#627
