### ISSUE TITLE
 EEVEE-Next - Properties - Raytracing Panel - Rename Horizon Scan to Fast GI approximation with new props

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#625]
![image](https://github.com/Bforartists/Manual/assets/35357409/57d47dac-a19a-4c4c-bcaa-bac323309975)
Rename label.
<details>
<summary>Details</summary>

SHA-1: e323a7d3919421be72ffe349207989ef2d7e1e53

* EEVEE-Next: UI: Rename Horizon Scan to Fast GI approximation

This matches Cycles feature name and is less technical.

</details>

<details>
<summary>Details</summary>

SHA-1: c9c95e7e6454b0940d4bdcfc6d0da86dca3b142f

* EEVEE-Next: RNA: Rename horizon property to fast_gi

This avoid discrepancy between the UI and the API.

</details>

<details>
<summary>Details</summary>

SHA-1: 117bfc870d2cb5e823da93e67afb60eb512fa316

* EEVEE-Next: Fast GI: Add angular thickness

While easier to understand, the conventionnal global
scene thickness parameter have some downside:
- It doesn't scale with larger scenes since the
  distant samples have small thickness
- It doesn't handle fine geometric variation in
  foreground.

The proposed angular thicknes makes all sample
have the same angular span. This makes it
distance independant and capture different occluder
thickness with less artifacts. The downside is
that the occluders have the same angular span
at any distance which makes the same occluder inflate
with distance.

A downside is that the geometry near the shading point is
under-represented. Leaving light leaking or lack of AO
at contact points. To fix this, we introduce back a
geometric thickness parameter.

Pull Request: https://projects.blender.org/blender/blender/pulls/122334

</details>

**Comment by ReinerBforartists** [comment]
Fixed with rewrite of chapter for issue [EEVEE-Next - Properties - Expose Fast GI ray and step count and other options](https://github.com/Bforartists/Manual/issues/627#top)
#627
