### ISSUE TITLE
EEVEE-Next - Properties - Move simplify panel just before post processes

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#626]
![image](https://github.com/Bforartists/Manual/assets/35357409/45ef404c-5e50-4b36-82b3-93a31dc0c64b)
Update the order of documentation.
<details>
<summary>Details</summary>

SHA-1: eaf1454475286ba205dca367b13cbc9d6e2fe220

* EEVEE-Next: UI: Move simplify panel just before post processes

Follow Cycles order.

</details>

**Comment by ReinerBforartists** [comment]
Fixed with rewrite of chapter for issue [EEVEE-Next - Properties - Expose Fast GI ray and step count and other options](https://github.com/Bforartists/Manual/issues/627#top)
#627
