### ISSUE TITLE
 EEVEE-Next - Properties - Expose Fast GI ray and step count and other options

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#627]
![image](https://github.com/Bforartists/Manual/assets/35357409/301d2ed7-71f5-41b8-b79e-1275a7ede550)

New properties! Nice interesting stuff. You can also turn it off and on. 

<details>
<summary>Details</summary>
SHA-1: 0e11f168dbb26ee0b2e0161d76fec91664cdc3cb

* EEVEE-Next: Expose Fast GI ray and step count

This allow to reduce the amount of noise and reduce
the lost energy caused by low thickness and large
stride (low sample count).

Actual number of rays is twice the UI count.

</details>

<details>
<summary>Details</summary>

SHA-1: 8a7b9f6f6605e8bdae5f01b9a63a132db2121a96

* EEVEE-Next: Add option to turn off GI

This new `Method` property allows to replace Diffuse GI
by simple ambient occlusion. This can be desirable for
performance or look.

This doesn't add the memory savings but there are already
some performance gain by using this option.

</details>

<details>
<summary>Details</summary>

SHA-1: 66af5ed445821dd92f3e08b80e3ff08b6d83ead7

* EEVEE-Next: Add fast GI max distance

This is implemented as a separate parameter from AO
since the AO can be tweaked for the AO pass.

</details>

**Comment by ReinerBforartists** [comment]
While at it, 26.2.3 Editors - Properties Editor - Render Properties Tab - EEVEE-Next.odt needs a rename. Eeevee next became Eevee again.

**Comment by ReinerBforartists** [comment]
The whole chapter is outdated it seems :/

**Comment by ReinerBforartists** [comment]
Fixed
