### ISSUE TITLE
Preferences - Move Themes to Extensions tab, update chapters

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#628]
![bforartists_Swu6aVUteA](https://github.com/Bforartists/Manual/assets/35357409/304046e5-0028-48ae-93f3-8cf04e2746ee)

Now they are grouped together, makes sense. 

<details>
<summary>Details</summary>

SHA-1: bdde38eff1253a7d51b8ab08d651b87b6c2537ee

* UI: Preferences: Group the Themes tab with the Extensions

Co-authored by Pablo Vazquez.

</details>

**Comment by ReinerBforartists** [comment]
Done
