### ISSUE TITLE
Compositor - Switch View Node - Remove the "Update Views" buttons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#629]
![image](https://github.com/Bforartists/Manual/assets/35357409/f02c6ed1-afc6-4ec2-9bbf-e3bc7f8d8771)

A small update, refresh button no-longer there. 

<details>
<summary>Details</summary>

SHA-1: 94847705517529a475d618406d529456c6eb3406

* Compositor: Switch View: automatically update views when render views are enabled/disabled

Remove the button "Update Views" that requires the user to update visible views manually. This is now consistent with the automatic update of compositor tree, when views are added or deleted, see #120685.

The patch also addresses #109866 (not really a fix since behavior in that bug report is intentional).

Pull Request: https://projects.blender.org/blender/blender/pulls/122290

</details>

**Comment by ReinerBforartists** [comment]
Switch node, not Split node ...

**Comment by ReinerBforartists** [comment]
Hm, task is invalid, there is no update button at the node in the manual. All is already up to date. Closing.
