### ISSUE TITLE
Properties Editor - Modifier Stack - Pin to Last needs updating

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#630]
![image](https://github.com/Bforartists/Manual/assets/35357409/b4bdaa1b-13b0-480e-9636-97d96baf675b)

Now there is a pin icon, thank goodness. It is also called "Pin to last". 

<details>
<summary>Details</summary>

SHA-1: 7ee189416c0d48e727ea186b4c58e2fd54fcf894

* UI: Show modifier pinning with icon, adjust name

User feedback has been that the pinned modifier looks broken because
there is no feedback in the UI showing that it's pinned (related to the
recently reported #121620). It's also inconvenient to disable the pinning
if it's required to move the modifier up (before another modifier that
controls normals for example). Now the "Pin" icon is displayed here,
and clicking on it turns off the pinning.

Also, change the property name from "Stick to Last" to "Pin to Last".
"Stick" is a weird word in the UI, it sounds uncommon and strangely
physical. "Pin" is more associated with this concept.

---

![Screenshot from 2024-05-29 11-41-06](/attachments/4581d362-e2fb-4edf-83dd-7f1e1b71ec4d)

Pull Request: https://projects.blender.org/blender/blender/pulls/122444

</details>

**Comment by ReinerBforartists** [comment]
Do we have a double now here? I can see a pin icon in the header and in the menu ...

**Comment by Draise14** [comment]
Right now it's NOT a double. 

Check box to pin and unpin in the sub-menu.
The pin icon only unpins, it is a visual indicator. There is no way to pin from the top-level. 

# Task 
If documentation exists, update with this info. 

Come to think of this, this pinning should be exposed to the top level right?

**Comment by ReinerBforartists** [comment]
So two pins? O_O

**Comment by Draise14** [comment]
Yeah, I'll make a task to make it... one pin system. And top level.

**Comment by ReinerBforartists** [comment]
Thanks 

Just realize that this is the manual tracker, i thought this is in the regular one. Sorry buddy. 

But in fact, we don't do checkboxes in menus. So there is a task hiding here, and not just updating the manual.

**Comment by Draise14** [comment]
Task created. 
https://github.com/Bforartists/Bforartists/issues/4338

**Comment by Draise14** [comment]
https://github.com/Bforartists/Manual/assets/35357409/99463ad9-dbdc-4a44-a511-bd815832b6ac

Will document it now.
