### ISSUE TITLE
3D View - Overlays - New Camera Guides in Viewport Overlays

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#631]
![image](https://github.com/Bforartists/Manual/assets/35357409/47f628af-c41b-4d2e-a381-f126adb908ae)

When in the camera view, you now can turn on or off the camera guides - instead of per camera. 

<details>
<summary>Details</summary>

SHA-1: 4e838fdae7ae8e0cc557b77af844d8862d967623

* UI: Toggle Camera Guides in 3D View Overlay

Commit of #122337 removed this functionality by removing the exit this
used. This PR just brings back this functionality so you can toggle
both camera guides and passepartout.

Pull Request: https://projects.blender.org/blender/blender/pulls/122514

</details>

<details>
<summary>Details</summary>

SHA-1: 2a287dc23cadc0c7971f0fc4bcd1bef0f66d3ee1

* UI: Toggle Camera Passepartout in Viewport Overlays

Allow toggling camera passepartout in the 3DView Overlay popover while
in camera view.

Pull Request: https://projects.blender.org/blender/blender/pulls/122337

</details>

**Comment by ReinerBforartists** [comment]
Two lines, three shots ...
