### ISSUE TITLE
Geometry Nodes - Capture Attribute now can capture multiple attributes

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#632]
![image](https://github.com/Bforartists/Manual/assets/35357409/5379cd89-1829-4201-8fce-d30ae9753775)

Kinda neat new feature this. Will make trees cleaner and more performant. 

<details>
<summary>Details</summary>

SHA-1: 28cef56ad2866993a4bd7ef1a4bb42da69dffaa6

* Geometry Nodes: support capturing multiple attributes at once

By capturing multiple attributes with one node, the user can make sure that those
are evaluated together in the same context. This can be quite a bit more efficient
compared to capturing multiple fields separately (also because we don't optimize
grouping multiple capture nodes together yet).

The change is fully backward compatible. Forward compatibility has been added
for some cases. Especially, files created in older versions that are saved with this
newer version will still work in the older version.

Co-authored-by: Hans Goudey <hans@blender.org>
Pull Request: https://projects.blender.org/blender/blender/pulls/121665

</details>

**Comment by ReinerBforartists** [comment]
Fixed
