### ISSUE TITLE
3D View - Image Empty - Convert to Mesh Plane operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#637]
![image](https://github.com/Bforartists/Manual/assets/35357409/7c2ccdc3-4f5e-47d5-9cdd-f99c67d0ca0c)
New operator for the image empty convert sub-menu from the object header. 

<details>
<summary>Details</summary>
SHA-1: 1d894aa1a75daaecf40e66511841931b309c1b94

* Add Convert Image Empty to Mesh Plane operator

Since import images as mesh planes operator was added recently in core
Blender, it is now easy to also support converting image empties to mesh
planes by reusing the same code.

This results in a fast workflow where you can use Blender's drag & drop
& align feature for reference images, and quickly turn them into meshes
without registering second file handler and clicking anything before
import is finished.

Ref !122546

</details>

**Comment by ReinerBforartists** [comment]
Outdated chapter. Misses quite a few changes.

**Comment by ReinerBforartists** [comment]
Needs updating the add menu too. Mesh plane is missing there.

**Comment by ReinerBforartists** [comment]
Fixed
