### ISSUE TITLE
Geometry Nodes - support matrix socket in accumulate field node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#638]
![image](https://github.com/Bforartists/Manual/assets/35357409/4080c988-268f-4c82-87f0-82f5ace667ed)

Transform Socket supported 

<details>
<summary>Details</summary>
SHA-1: 78c1c1a1705eef442b06ea3f991d54f74fc9566a

* Geometry Nodes: support matrix socket in accumulate field node

This adds support for transform matrices in the accumulate field node. This is quite
useful to evaluate chains of parent matrices (although branching is not easily possible
with this approach).

The main tricky thing here is that matrices are generally accumulated using
multiplication and the order of multiplication matters. For other data types we
currently always use addition. I don't have use cases for other ways to accumulate
matrices right now, so maybe it's fine not to add additional options here for now.
It should be fairly straight forward to version this to support more accumulation
modes in the future. Additionally, I hope we get a more general solution for custom
accumulations at some point.

Pull Request: https://projects.blender.org/blender/blender/pulls/121326

</details>

**Comment by ReinerBforartists** [comment]
A None liner, just added a new screenshot. We don't explain the data types since they are self explaining.

This is one of these issues where writing the issue was more time than directly fixing it.
