### ISSUE TITLE
Write chapter 12.1.39 Editors - Geometry Nodes Editor - Header - Add Menu - Utilities - Matrix.odt

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Manual#640]
Whole chapter is missing. Has no icons yet. A placeholder chapter exists already.

![matrix](https://github.com/Bforartists/Manual/assets/13919702/a09f2f27-e66c-4eac-9246-f0316f1d2331)

**Comment by ReinerBforartists** [comment]
Related: Geometry nodes editor - add chapter for deprecated nodes in Add/Utilities menu #620

**Comment by ReinerBforartists** [comment]
And here is the related main tracker task: https://github.com/Bforartists/Bforartists/issues/4232

**Comment by Draise14** [comment]
Will postpone this till the icons are done...

**Comment by ReinerBforartists** [comment]
And fixed.
