### ISSUE TITLE
Properties Editor - EEVEE - Render Tab - Mention Raytracing Presets

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#643]
![image](https://github.com/Bforartists/Manual/assets/35357409/3e2aae93-6f87-4b28-9164-0bf1d01906af)

We can have raytracing presets here now. 
<details>
<summary>Details</summary>

SHA-1: bb9e3df6d248dc91dff76b04fd16472cecafbee0

* Fix #122766: Add missing Fast GI options to raytracing presets

The UI has changed and fast GI options was moved to the raytracing
panel in the UI. When this was done they were not added to the
raytracing presets what adds confusion when adding the presets.

This PR adds the fast GI options to the presets.

Pull Request: https://projects.blender.org/blender/blender/pulls/123061

</details>

**Comment by ReinerBforartists** [comment]
Task is invalid, Presets are already documented.
