### ISSUE TITLE
Compositor - Preview icon update

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#660]
![image](https://github.com/user-attachments/assets/aabdeedb-2a69-421f-9213-811f8dafc05b)

This change I agree with, the preview button is now an eye like the geometry nodes viewer. Let's keep it like that in the documentation too. 

<details>
<summary>Details</summary>

SHA-1: 5a99d5d3fc9225008904442f051baa22e9a66633

* Compositor: UI: Use hide icon for preview

Replace material icon with hide (eye) icon and enable toggling on/off. This makes it consistent with the UI of geometry nodes viewer node

Pull Request: https://projects.blender.org/blender/blender/pulls/127042

</details>

**Comment by ReinerBforartists** [comment]
One of those tasks where it would have been so much faster to simply add the image to the manual chapter instead of making an extra tracker entry for it.

**Comment by ReinerBforartists** [comment]
Fixed.
