### ISSUE TITLE
3D View- Edit Mode- Tris to Quads has new "Deselect Joined" toggle

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Manual#666]
![image](https://github.com/user-attachments/assets/a4f04517-7865-4c37-9984-e5b1f3b2e719)

> A new checkbox to leave only the remaining triangles selected has also
been added. This helps users visualize what remains to be fixed.

<details>
<summary>Details</summary>

SHA-1: dc57693b0c88b93847ec206f692bf51e0173839c

* Modeling: add support for merging triangles with reference to topology

A new parameter, topology influence, is added that causes the
join_triangles operator to prioritize edge joins that create quads with
sensible geometry relative to existing quads, instead of selecting the
'flattest' and 'squarest' next pair and then leaving leftover triangles
with no partners to merge with.

This produces its best results with the face and shape thresholds set to
180 degrees (no hard limits as a restriction against merging) and
topology influence somewhere between 100-130%, depending on the mesh.
Too low and many parallelograms and triangles are left, too high and the
algorithm tries too hard and starts making errors.

Note that both quads already present in the selection, as well as the
quads that are generated during the operator, will influence the
topology around them. This allows the modeler to manually merge a few
quads in key areas of the mesh, as a hint to the algorithm, indicating
what result they way they want to see, and the algorithm will then take
those quads into account and try to build around them according to the
modeler's guidance.

A new checkbox to leave only the remaining triangles selected has also
been added. This helps users visualize what remains to be fixed.

Ref !128610

</details>

**Comment by ReinerBforartists** [comment]
Fixed
