### ISSUE TITLE
Update chapter 13 Editors - Video Sequencer.odt to Bfa 2

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Manual#8]
Blender manual lacks of description of the single menu items in most cases, and has many outdated or no images at all. Plus other flaws. Like that they avoid to explain existing menus, since "they change too fast". Which makes it imho more a loose collection of explanations instead of a real manual. Which can be useful and fitting, or not.

Bforartists manual philosophy is to explain the UI and useage by the available tools and menus in the editors. One by one.

Task. Create new chapter Video Sequence Editor by tools.

**Comment by Draise14** [comment]
Dibs

**Comment by ReinerBforartists** [comment]
Any chance that you will ever touch this chapter? ^^

**Comment by Draise14** [comment]
Oh hey, yeah. I will this coming week.

**Comment by Draise14** [comment]
Ok, gonna embark on this one now before going back to VSE tasks.

**Comment by ReinerBforartists** [comment]
Good luck :)

**Comment by ReinerBforartists** [comment]
Forgot to say, fastest way is most probably first to grab the Blender manual part, and expand from there.

**Comment by Draise14** [comment]
Started working on it (30%). Blender has re-written a lot of this, so have started to copy/overwrite it over and will refine from BFA after. 

Finally, sorry for the delay. I was on holiday and also didn't have a good *.ODT software. I'm trying out Apache Open Office now.

**Comment by ReinerBforartists** [comment]
No problem. You decide if an when to do what. Why not Libre Office? Or Open Office?

**Comment by ReinerBforartists** [comment]
Two years. And no progress. Claiming this task now. We need it in our life time ;)

**Comment by ReinerBforartists** [comment]
Fixed in master
